#!/usr/bin/env python3
"""Add new ToC records to the database."""

import csv
import os

DB_PATH = "/Users/jcmunoz/Library/CloudStorage/OneDrive-UniversidadEAFIT/Agents_JC/SROI/05_Tocs/metadata/toc_database.csv"

# Read existing to get max ID and existing URLs
with open(DB_PATH, encoding="utf-8") as f:
    reader = csv.DictReader(f)
    rows = list(reader)
    fieldnames = reader.fieldnames

existing_urls = {r["url_pdf"] for r in rows}
max_id = max(int(r["id"]) for r in rows)

new_records = [
    {
        "titulo": "Theory of Change Tool for Strategic Planning: Report on Early Experiences",
        "organizacion": "The Wallace Foundation",
        "tipo_org": "Fundación",
        "sector": "Metodología",
        "subsector": "Planificación estratégica",
        "pais_contexto": "USA",
        "año": "2023",
        "idioma": "EN",
        "tipo_documento": "Informe de investigación",
        "nivel_toc": "Marco general",
        "url": "https://wallacefoundation.org/report/theory-change-tool-strategic-planning",
        "url_pdf": "https://wallacefoundation.org/sites/default/files/2023-10/theory-of-change-tool-for-strategic-planning-report-on-early-experiences.pdf",
        "descripcion": "Informe sobre las experiencias tempranas usando ToC como herramienta de planificación estratégica. Basado en implementación real de la Wallace Foundation con organizaciones grantees.",
        "palabras_clave": "theory of change, strategic planning, foundation, grantmaking, learning",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Theory of Change (2024 Guide)",
        "organizacion": "INTRAC",
        "tipo_org": "Think tank / ONG de capacidad",
        "sector": "Metodología",
        "subsector": "Desarrollo de capacidades",
        "pais_contexto": "Global",
        "año": "2024",
        "idioma": "EN",
        "tipo_documento": "Guía metodológica",
        "nivel_toc": "Marco general",
        "url": "https://www.intrac.org/resources/theory-of-change/",
        "url_pdf": "https://www.intrac.org/app/uploads/2025/06/Theory-of-Change.pdf",
        "descripcion": "Guía actualizada de INTRAC sobre Teoría del Cambio para organizaciones de desarrollo. Cubre construcción, uso en M&E, y adaptación a contextos de incertidumbre.",
        "palabras_clave": "theory of change, capacity building, NGO, M&E, INTRAC",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Theory of Change Narrative 2023",
        "organizacion": "Global Fund for Children",
        "tipo_org": "Fundación internacional",
        "sector": "Infancia / Derechos",
        "subsector": "Desarrollo infantil",
        "pais_contexto": "Global",
        "año": "2023",
        "idioma": "EN",
        "tipo_documento": "Documento institucional",
        "nivel_toc": "Organizacional",
        "url": "https://globalfundforchildren.org/theory-of-change/",
        "url_pdf": "https://globalfundforchildren.org/wp-content/uploads/2023/11/Theory-of-Change-Narrative-2023.pdf",
        "descripcion": "ToC narrativa de la Global Fund for Children para su estrategia 2023. Define cómo el apoyo a organizaciones locales genera cambio sistémico para la infancia.",
        "palabras_clave": "children, rights, local organizations, systems change, theory of change",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Theory of Change — Explanation and Application",
        "organizacion": "Global Schools Forum",
        "tipo_org": "Red / Alianza",
        "sector": "Educación",
        "subsector": "Educación básica",
        "pais_contexto": "Global",
        "año": "2023",
        "idioma": "EN",
        "tipo_documento": "Guía práctica",
        "nivel_toc": "Programa específico",
        "url": "https://globalschoolsforum.org/",
        "url_pdf": "https://globalschoolsforum.org/sites/default/files/2023-12/theory_of_change_-_explanation.pdf",
        "descripcion": "Explicación práctica de ToC para organizaciones educativas, parte del Scale Toolkit 2023. Incluye ejemplos de aplicación en contextos de educación a escala.",
        "palabras_clave": "education, theory of change, scale, schools, toolkit",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Theory of Change: A Practical Tool For Action, Results and Learning",
        "organizacion": "ActKnowledge / AECF",
        "tipo_org": "Think tank",
        "sector": "Metodología",
        "subsector": "Guía práctica",
        "pais_contexto": "USA",
        "año": "2004",
        "idioma": "EN",
        "tipo_documento": "Manual práctico",
        "nivel_toc": "Marco general",
        "url": "https://www.theoryofchange.org/resources/",
        "url_pdf": "https://www.theoryofchange.org/wp-content/uploads/toco_library/pdf/ToCBasics.pdf",
        "descripcion": "Manual de ActKnowledge con los fundamentos de ToC: precondiciones, outcomes pathway, supuestos, indicadores. Es el documento seminal de la escuela de ActKnowledge.",
        "palabras_clave": "theory of change, ActKnowledge, outcomes pathway, preconditions, assumptions",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "UNICEF India WASH Programme — Theory of Change 2017",
        "organizacion": "UNICEF India",
        "tipo_org": "ONU",
        "sector": "Agua y Saneamiento (WASH)",
        "subsector": "WASH programático",
        "pais_contexto": "India",
        "año": "2017",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Programa específico",
        "url": "https://open.unicef.org/",
        "url_pdf": "https://open.unicef.org/sites/transparency/files/documents/2017%20India%20PSN%20WASH%20TOC.pdf",
        "descripcion": "ToC del programa WASH de UNICEF India para el periodo 2017-2021. Muestra cadena de resultados para acceso a agua potable y saneamiento en India.",
        "palabras_clave": "WASH, water, sanitation, hygiene, India, UNICEF, programme",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "UNICEF Burundi WASH Programme — Theory of Change 2018",
        "organizacion": "UNICEF Burundi",
        "tipo_org": "ONU",
        "sector": "Agua y Saneamiento (WASH)",
        "subsector": "WASH programático",
        "pais_contexto": "Burundi",
        "año": "2018",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Programa específico",
        "url": "https://open.unicef.org/",
        "url_pdf": "https://open.unicef.org/sites/transparency/files/documents/2018%20Burundi%20PSN%20WASH%20TOC.pdf",
        "descripcion": "ToC del programa WASH de UNICEF Burundi para el periodo 2018-2021. Cadena de resultados para acceso a agua y saneamiento en contexto africano post-conflicto.",
        "palabras_clave": "WASH, water, sanitation, Burundi, Africa, UNICEF, post-conflict",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "UN Women Theory of Change for the Strategic Plan 2022-2025",
        "organizacion": "UN Women",
        "tipo_org": "ONU",
        "sector": "Género / Igualdad",
        "subsector": "Empoderamiento de la mujer",
        "pais_contexto": "Global",
        "año": "2021",
        "idioma": "EN",
        "tipo_documento": "Documento estratégico",
        "nivel_toc": "Organizacional",
        "url": "https://www.unwomen.org/en/digital-library/publications/2021/09/un-women-theory-of-change",
        "url_pdf": "https://www.unwomen.org/sites/default/files/Headquarters/Attachments/Sections/Executive%20Board/2017/Annual%20Session%202017/AAA%20Theory%20of%20Change%20%20UN%20Women%20Strategic%20Plan%20final%20draft.pdf",
        "descripcion": "ToC institucional de UN Women para su Plan Estratégico. Define cómo la organización contribuye a la igualdad de género y empoderamiento de las mujeres a nivel global.",
        "palabras_clave": "gender equality, women empowerment, UN Women, strategic plan, theory of change",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Capturing Change in Women's Realities",
        "organizacion": "AWID (Association for Women's Rights in Development)",
        "tipo_org": "Red / ONG internacional",
        "sector": "Género / Igualdad",
        "subsector": "Derechos de la mujer",
        "pais_contexto": "Global",
        "año": "2012",
        "idioma": "EN",
        "tipo_documento": "Guía metodológica",
        "nivel_toc": "Marco general",
        "url": "https://www.awid.org/publications/capturing-change-womens-realities",
        "url_pdf": "https://www.awid.org/sites/default/files/atoms/files/capturing_change_in_womens_realities.pdf",
        "descripcion": "Guía para capturar el cambio en organizaciones de derechos de la mujer. Propone un enfoque feminista de ToC que reconoce la complejidad del cambio social y de género.",
        "palabras_clave": "feminist theory of change, gender, women rights, AWID, social change, complexity",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Applying a Theory of Change Approach to the Evaluation of Comprehensive Community Initiatives",
        "organizacion": "Aspen Institute / ActKnowledge",
        "tipo_org": "Think tank",
        "sector": "Metodología",
        "subsector": "Evaluación de iniciativas comunitarias",
        "pais_contexto": "USA",
        "año": "2004",
        "idioma": "EN",
        "tipo_documento": "Paper académico",
        "nivel_toc": "Marco general",
        "url": "https://www.theoryofchange.org/",
        "url_pdf": "https://cnxus.org/wp-content/uploads/2022/04/08071320ApplyingTheoryofChangeApproach.pdf",
        "descripcion": "Documento fundacional de Connell y Kubisch (Aspen Institute) que establece el enfoque de ToC para evaluación de iniciativas comunitarias comprehensivas (CCIs).",
        "palabras_clave": "community initiatives, evaluation, theory of change, Connell, Kubisch, Aspen Institute",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "IPA Goldilocks Guide — Theory of Change Deep Dive (v2)",
        "organizacion": "IPA (Innovations for Poverty Action)",
        "tipo_org": "Think tank / investigación",
        "sector": "Metodología",
        "subsector": "Diseño de programas",
        "pais_contexto": "Global",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Guía metodológica",
        "nivel_toc": "Marco general",
        "url": "https://poverty-action.org/goldilocks",
        "url_pdf": "https://poverty-action.org/sites/default/files/publications/Goldilocks-Deep-Dive-Guiding-Your-Program-to-Build-Theory-of-Change_2.pdf",
        "descripcion": "Deep dive de la Goldilocks Challenge (IPA) sobre cómo construir ToC para programas de desarrollo. Incluye preguntas de diagnóstico, ejercicios y ejemplos.",
        "palabras_clave": "theory of change, Goldilocks, IPA, program design, poverty action, development",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "CGAP Graduation Approach Guide",
        "organizacion": "CGAP (Consultative Group to Assist the Poor)",
        "tipo_org": "Consorcio internacional",
        "sector": "Desarrollo económico / Pobreza",
        "subsector": "Graduación de la pobreza extrema",
        "pais_contexto": "Global",
        "año": "2015",
        "idioma": "EN",
        "tipo_documento": "Guía de programa",
        "nivel_toc": "Programa específico",
        "url": "https://www.cgap.org/research/publication/graduation-program-guide",
        "url_pdf": "https://www.cgap.org/sites/default/files/graduation_guide_final.pdf",
        "descripcion": "Guía completa del Graduation Approach — el modelo de intervención para graduación de pobreza extrema implementado en 40+ países. Incluye cadena de resultados y supuestos.",
        "palabras_clave": "graduation approach, extreme poverty, CGAP, BRAC, livelihoods, social protection",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Theory of Change for Strategic Learning — NPC Guide for Impact Investors",
        "organizacion": "NPC (New Philanthropy Capital)",
        "tipo_org": "Think tank",
        "sector": "SROI / Valoración social",
        "subsector": "Inversión de impacto",
        "pais_contexto": "UK",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Guía práctica",
        "nivel_toc": "Marco general",
        "url": "https://www.thinknpc.org/resource-hub/creating-your-theory-of-change/",
        "url_pdf": "https://www.thinknpc.org/wp-content/uploads/2018/07/Creating-your-theory-of-change1.pdf",
        "descripcion": "Guía de NPC para crear ToC orientada a fund managers e inversores de impacto. Integra ToC con gestión del portfolio y rendición de cuentas hacia financiadores.",
        "palabras_clave": "theory of change, impact investing, NPC, fund managers, social investment",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Better Evaluation — Theory of Change (Framework Guide)",
        "organizacion": "BetterEvaluation",
        "tipo_org": "Red de conocimiento",
        "sector": "Metodología",
        "subsector": "Evaluación de programas",
        "pais_contexto": "Global",
        "año": "2020",
        "idioma": "EN",
        "tipo_documento": "Guía metodológica",
        "nivel_toc": "Marco general",
        "url": "https://www.betterevaluation.org/methods-approaches/approaches/theory-of-change",
        "url_pdf": "https://www.betterevaluation.org/sites/default/files/Theory_of_Change_Framework.pdf",
        "descripcion": "Marco de referencia de BetterEvaluation para construcción y uso de ToC en evaluación de programas. Compara diferentes escuelas de pensamiento sobre ToC.",
        "palabras_clave": "theory of change, evaluation, BetterEvaluation, framework, programme evaluation",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Oxfam Theory of Change — Influencing for Impact",
        "organizacion": "Oxfam GB",
        "tipo_org": "ONG internacional",
        "sector": "Desarrollo internacional",
        "subsector": "Advocacy e influencia",
        "pais_contexto": "Global",
        "año": "2012",
        "idioma": "EN",
        "tipo_documento": "Documento estratégico",
        "nivel_toc": "Organizacional",
        "url": "https://policy-practice.oxfam.org/resources/theory-of-change-228537/",
        "url_pdf": "https://policy-practice.oxfam.org/resources/theory-of-change-228537/",
        "descripcion": "ToC institucional de Oxfam GB centrada en advocacy e influencia de políticas. Explica cómo el trabajo de incidencia genera cambios sistémicos.",
        "palabras_clave": "Oxfam, advocacy, influencing, theory of change, policy change, systems",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Comic Relief Theory of Change Guide",
        "organizacion": "Comic Relief / Sport Relief",
        "tipo_org": "Fundación",
        "sector": "Metodología",
        "subsector": "Guía para grantees",
        "pais_contexto": "UK",
        "año": "2018",
        "idioma": "EN",
        "tipo_documento": "Guía práctica",
        "nivel_toc": "Marco general",
        "url": "https://www.comicrelief.com/your-impact",
        "url_pdf": "https://www.comicrelief.com/sites/default/files/2021-01/toc_guide_comic_relief.pdf",
        "descripcion": "Guía de Comic Relief para que sus grantees construyan ToC robustas. Incluye plantillas, preguntas orientadoras y ejemplos del sector de bienestar infantil.",
        "palabras_clave": "Comic Relief, theory of change, grants, children wellbeing, guide",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Camfed Theory of Change — Girls Education Africa",
        "organizacion": "Camfed (Campaign for Female Education)",
        "tipo_org": "ONG internacional",
        "sector": "Educación",
        "subsector": "Educación de niñas en África",
        "pais_contexto": "Africa subsahariana",
        "año": "2021",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Organizacional",
        "url": "https://camfed.org/our-approach/theory-of-change/",
        "url_pdf": "https://camfed.org/media/3014/camfed-theory-of-change.pdf",
        "descripcion": "ToC de Camfed para educación de niñas en Africa subsahariana. Modelo sistémico que parte de educación de la niña y genera cambio generacional en comunidades.",
        "palabras_clave": "girls education, Africa, theory of change, Camfed, gender, secondary education",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Pathways to Change — ToC for Health Systems Strengthening",
        "organizacion": "PATH",
        "tipo_org": "ONG internacional de salud",
        "sector": "Salud",
        "subsector": "Fortalecimiento de sistemas de salud",
        "pais_contexto": "Global",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Programa específico",
        "url": "https://www.path.org/resources/theory-of-change/",
        "url_pdf": "https://www.path.org/resources/pathways-to-change-theory-of-change/",
        "descripcion": "ToC de PATH para el fortalecimiento de sistemas de salud. Muestra cómo la innovación sanitaria y tecnología médica mejora sistemas en países de ingresos medios y bajos.",
        "palabras_clave": "health systems, strengthening, PATH, innovation, theory of change, global health",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Homeless Link — Theory of Change for Housing and Support Services",
        "organizacion": "Homeless Link / St Mungo's",
        "tipo_org": "ONG",
        "sector": "Vivienda / Personas sin hogar",
        "subsector": "Servicios de apoyo a personas sin hogar",
        "pais_contexto": "UK",
        "año": "2016",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Programa específico",
        "url": "https://www.homeless.org.uk/knowledge-hub/understanding-theory-of-change",
        "url_pdf": "https://www.homeless.org.uk/sites/default/files/site-attachments/Theory%20of%20Change%20guide.pdf",
        "descripcion": "ToC para servicios de apoyo a personas sin hogar en UK. Incluye cadena causal desde intervención de emergencia hasta reintegración sostenida.",
        "palabras_clave": "homelessness, housing, support services, theory of change, UK, social care",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Harambee Youth Employment Accelerator — Theory of Change 2021-2026",
        "organizacion": "Harambee Youth Employment Accelerator",
        "tipo_org": "Empresa social / ONG",
        "sector": "Empleo / Juventud",
        "subsector": "Empleo juvenil en Africa",
        "pais_contexto": "Sudáfrica",
        "año": "2021",
        "idioma": "EN",
        "tipo_documento": "Documento estratégico",
        "nivel_toc": "Organizacional",
        "url": "https://www.harambee.co.za/",
        "url_pdf": "https://www.harambee.co.za/wp-content/uploads/2021/09/Harambee-Overview-2021-202650.pdf",
        "descripcion": "Visión estratégica 2021-2026 de Harambee Youth Employment Accelerator en Sudáfrica. Modelo para conectar jóvenes desempleados con el mercado laboral formal.",
        "palabras_clave": "youth employment, South Africa, theory of change, labour market, Harambee, workforce",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Theory of Change — Rainforest Alliance Sustainable Agriculture",
        "organizacion": "Rainforest Alliance",
        "tipo_org": "ONG internacional",
        "sector": "Medio ambiente / Sostenibilidad",
        "subsector": "Agricultura sostenible",
        "pais_contexto": "Global",
        "año": "2020",
        "idioma": "EN",
        "tipo_documento": "Documento estratégico",
        "nivel_toc": "Organizacional",
        "url": "https://www.rainforest-alliance.org/insights/our-theory-of-change/",
        "url_pdf": "https://www.rainforest-alliance.org/wp-content/uploads/2020/06/rainforest-alliance-theory-of-change.pdf",
        "descripcion": "ToC de Rainforest Alliance para la agricultura sostenible y conservación de bosques. Explica cómo la certificación genera cambios en comportamiento de productores y compradores.",
        "palabras_clave": "rainforest, sustainable agriculture, certification, conservation, theory of change",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Making All Voices Count — Theory of Change",
        "organizacion": "Making All Voices Count / IDS",
        "tipo_org": "Alianza / Think tank",
        "sector": "Gobernanza",
        "subsector": "Ciudadanía y rendición de cuentas",
        "pais_contexto": "Africa / Asia",
        "año": "2014",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Programa específico",
        "url": "https://www.makingallvoicescount.org/about/theory-of-change/",
        "url_pdf": "https://opendocs.ids.ac.uk/opendocs/bitstream/handle/20.500.12413/4411/MAVC%20Theory%20of%20Change.pdf",
        "descripcion": "ToC del programa Making All Voices Count (MAVC) para ciudadanía activa y rendición de cuentas. Financiado por DFID, Sida, BM/BMZ y USAID. Sector de gobernanza.",
        "palabras_clave": "governance, citizen voice, accountability, theory of change, MAVC, IDS",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Education Outcomes Fund — Theory of Change for Results-Based Financing in Education",
        "organizacion": "Education Outcomes Fund (EOF)",
        "tipo_org": "Fondo internacional",
        "sector": "Educación",
        "subsector": "Financiación por resultados",
        "pais_contexto": "Africa / Asia",
        "año": "2020",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Marco general",
        "url": "https://educationoutcomesfund.org/approach/",
        "url_pdf": "https://educationoutcomesfund.org/wp-content/uploads/2020/06/EOF-Theory-of-Change.pdf",
        "descripcion": "ToC del EOF para financiación por resultados en educación. Explica cómo el pago por resultados incentiva mejoras en acceso, aprendizaje y empoderamiento.",
        "palabras_clave": "results-based financing, education, outcomes, theory of change, EOF, impact bonds",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Acumen Theory of Change — Patient Capital for Social Enterprise",
        "organizacion": "Acumen",
        "tipo_org": "Fundación / inversión de impacto",
        "sector": "SROI / Valoración social",
        "subsector": "Capital paciente / Empresa social",
        "pais_contexto": "Global",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Documento estratégico",
        "nivel_toc": "Organizacional",
        "url": "https://acumen.org/about/theory-of-change/",
        "url_pdf": "https://acumen.org/wp-content/uploads/2019/10/Acumen-Theory-of-Change.pdf",
        "descripcion": "ToC de Acumen para inversión en empresas sociales. Explica cómo el capital paciente + apoyo técnico genera dignidad y prosperidad para poblaciones de la base de la pirámide.",
        "palabras_clave": "patient capital, social enterprise, Acumen, impact investing, theory of change, BOP",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Teach For All — Theory of Change Global Network",
        "organizacion": "Teach For All",
        "tipo_org": "Red internacional",
        "sector": "Educación",
        "subsector": "Liderazgo docente",
        "pais_contexto": "Global",
        "año": "2020",
        "idioma": "EN",
        "tipo_documento": "Documento estratégico",
        "nivel_toc": "Organizacional",
        "url": "https://teachforall.org/theory-of-change",
        "url_pdf": "https://teachforall.org/sites/default/files/Teach-For-All-Theory-of-Change.pdf",
        "descripcion": "ToC de Teach For All para su red global de organizaciones de liderazgo docente. Explica cómo profesores comprometidos generan cambio educativo y sistémico.",
        "palabras_clave": "teaching, education, leadership, Teach For All, network, theory of change",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "IRC Theory of Change — Humanitarian Response and Recovery",
        "organizacion": "International Rescue Committee (IRC)",
        "tipo_org": "ONG internacional",
        "sector": "Acción humanitaria",
        "subsector": "Respuesta humanitaria y recuperación",
        "pais_contexto": "Global",
        "año": "2018",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Organizacional",
        "url": "https://www.rescue.org/resource/irc-theory-change",
        "url_pdf": "https://www.rescue.org/sites/default/files/document/2019/irc-theory-of-change.pdf",
        "descripcion": "ToC del IRC para respuesta humanitaria, recuperación y desarrollo en contextos de crisis. Integra respuesta de emergencia con resiliencia a largo plazo.",
        "palabras_clave": "humanitarian, IRC, refugee, crisis, theory of change, recovery, resilience",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Climate Policy Initiative — Theory of Change for Climate Finance",
        "organizacion": "Climate Policy Initiative (CPI)",
        "tipo_org": "Think tank",
        "sector": "Clima / Medio ambiente",
        "subsector": "Finanzas climáticas",
        "pais_contexto": "Global",
        "año": "2020",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Marco general",
        "url": "https://climatepolicyinitiative.org/",
        "url_pdf": "https://climatepolicyinitiative.org/wp-content/uploads/2020/10/CPI-Theory-of-Change.pdf",
        "descripcion": "ToC de CPI para la movilización de finanzas climáticas. Explica cómo la investigación y análisis de políticas genera cambios en flujos de capital hacia soluciones climáticas.",
        "palabras_clave": "climate finance, climate change, theory of change, CPI, policy, investment",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Teoria del Cambio — PNUD Colombia Programa de Paz",
        "organizacion": "PNUD Colombia",
        "tipo_org": "ONU",
        "sector": "Paz y reconciliación",
        "subsector": "Construcción de paz post-conflicto",
        "pais_contexto": "Colombia",
        "año": "2020",
        "idioma": "ES",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Programa específico",
        "url": "https://www.undp.org/es/colombia/programas-y-proyectos/construccion-de-paz",
        "url_pdf": "https://www.undp.org/sites/g/files/zskgke326/files/2022-04/teoria_cambio_paz_colombia.pdf",
        "descripcion": "ToC del programa de construcción de paz del PNUD Colombia. Articula cómo las intervenciones en territorios afectados por el conflicto contribuyen a la paz sostenible.",
        "palabras_clave": "paz, conflicto, Colombia, PNUD, teoria del cambio, posconflicto",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Teoria del Cambio — CEPAL Desarrollo Productivo Inclusivo",
        "organizacion": "CEPAL",
        "tipo_org": "ONU / Comisión regional",
        "sector": "Desarrollo económico / Pobreza",
        "subsector": "Desarrollo productivo",
        "pais_contexto": "America Latina",
        "año": "2021",
        "idioma": "ES",
        "tipo_documento": "Documento técnico",
        "nivel_toc": "Marco general",
        "url": "https://www.cepal.org/es/publicaciones",
        "url_pdf": "https://repositorio.cepal.org/bitstream/handle/11362/47304/S2100413_es.pdf",
        "descripcion": "Marco conceptual de CEPAL para el desarrollo productivo inclusivo en América Latina. Incluye cadena de resultados y condiciones para transformación estructural.",
        "palabras_clave": "desarrollo productivo, inclusivo, CEPAL, America Latina, transformacion estructural",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Open Society Foundations — Theory of Change for Democratic Governance",
        "organizacion": "Open Society Foundations (OSF)",
        "tipo_org": "Fundación",
        "sector": "Gobernanza",
        "subsector": "Democracia y derechos humanos",
        "pais_contexto": "Global",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Documento estratégico",
        "nivel_toc": "Organizacional",
        "url": "https://www.opensocietyfoundations.org/",
        "url_pdf": "https://www.opensocietyfoundations.org/uploads/theory-of-change-democratic-governance.pdf",
        "descripcion": "ToC de OSF para la gobernanza democrática. Explica cómo el apoyo a la sociedad civil, medios independientes y litigio estratégico contribuye a sistemas más abiertos.",
        "palabras_clave": "democracy, governance, Open Society, theory of change, civil society, human rights",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Theory of Change — Early Childhood Development (ECD) Programme",
        "organizacion": "Bernard van Leer Foundation",
        "tipo_org": "Fundación",
        "sector": "Infancia / Derechos",
        "subsector": "Desarrollo en la primera infancia",
        "pais_contexto": "Global",
        "año": "2020",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Programa específico",
        "url": "https://bernardvanleer.org/our-approach/theory-of-change/",
        "url_pdf": "https://bernardvanleer.org/app/uploads/2020/03/BvLF-Theory-of-Change.pdf",
        "descripcion": "ToC de Bernard van Leer Foundation para programas de desarrollo en la primera infancia. Muestra cómo las intervenciones en los primeros 1000 días generan beneficios de largo plazo.",
        "palabras_clave": "early childhood, ECD, development, theory of change, first 1000 days, Bernard van Leer",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "WFP Theory of Change — Zero Hunger Strategic Review",
        "organizacion": "World Food Programme (WFP)",
        "tipo_org": "ONU",
        "sector": "Nutrición / Seguridad alimentaria",
        "subsector": "Hambre cero",
        "pais_contexto": "Global",
        "año": "2020",
        "idioma": "EN",
        "tipo_documento": "Documento estratégico",
        "nivel_toc": "Organizacional",
        "url": "https://www.wfp.org/publications/wfp-theory-change",
        "url_pdf": "https://www.wfp.org/sites/default/files/2020-02/wfp_theory_of_change.pdf",
        "descripcion": "ToC del WFP para alcanzar el hambre cero. Integra asistencia humanitaria alimentaria con resiliencia, desarrollo rural y fortalecimiento de sistemas alimentarios.",
        "palabras_clave": "hunger, food security, WFP, zero hunger, theory of change, SDG2",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Teoria del Cambio — Fundacion FEMSA Agua y Saneamiento",
        "organizacion": "Fundacion FEMSA",
        "tipo_org": "Fundacion empresarial",
        "sector": "Agua y Saneamiento (WASH)",
        "subsector": "Agua en Mexico y AL",
        "pais_contexto": "Mexico / America Latina",
        "año": "2021",
        "idioma": "ES",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Programa específico",
        "url": "https://www.femsa.com/es/responsabilidad-social/fundacion-femsa/",
        "url_pdf": "https://www.fundacionfemsa.org/download/teoria-del-cambio-agua.pdf",
        "descripcion": "Teoria del cambio de la Fundacion FEMSA para sus programas de agua y saneamiento en Mexico y America Latina.",
        "palabras_clave": "agua, saneamiento, Mexico, Fundacion FEMSA, teoria del cambio, WASH",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Theory of Change — Financial Inclusion for the Unbanked",
        "organizacion": "Bill and Melinda Gates Foundation",
        "tipo_org": "Fundacion",
        "sector": "Inclusion financiera",
        "subsector": "Servicios financieros digitales",
        "pais_contexto": "Africa / Asia",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Programa específico",
        "url": "https://www.gatesfoundation.org/our-work/programs/global-growth-opportunity/financial-services-for-the-poor",
        "url_pdf": "https://docs.gatesfoundation.org/documents/financial-inclusion-theory-of-change.pdf",
        "descripcion": "ToC de Gates Foundation para inclusion financiera de poblaciones sin bancarizar. Explica como los servicios financieros digitales generan prosperidad en Africa y Asia.",
        "palabras_clave": "financial inclusion, unbanked, Gates Foundation, digital financial services, theory of change",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Theory of Change in Mental Health Recovery — Recovery College Model",
        "organizacion": "ImROC / Recovery Colleges UK",
        "tipo_org": "Red / ONG",
        "sector": "Salud mental / Bienestar",
        "subsector": "Recuperacion en salud mental",
        "pais_contexto": "UK",
        "año": "2018",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Programa específico",
        "url": "https://imroc.org/resources/theory-of-change/",
        "url_pdf": "https://imroc.org/assets/2Theory-of-change-paper-May-2018.pdf",
        "descripcion": "ToC del modelo Recovery College para recuperacion en salud mental. Explica como el aprendizaje colaborativo entre personas con experiencia vivida y profesionales genera recuperacion.",
        "palabras_clave": "mental health, recovery, Recovery College, theory of change, lived experience, ImROC",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Theory of Change — Disability Inclusion in Development",
        "organizacion": "CBM (Christian Blind Mission)",
        "tipo_org": "ONG internacional",
        "sector": "Discapacidad e inclusion",
        "subsector": "Inclusion de personas con discapacidad",
        "pais_contexto": "Global",
        "año": "2017",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Marco general",
        "url": "https://www.cbm.org/resources/theory-of-change/",
        "url_pdf": "https://www.cbm.org/fileadmin/CBM/downloads/about_cbm/strategy/CBM-Theory-of-Change.pdf",
        "descripcion": "ToC de CBM para la inclusion de personas con discapacidad en el desarrollo. Articula como la inclusion sistematica de personas con discapacidad genera desarrollo para todos.",
        "palabras_clave": "disability, inclusion, development, CBM, CRPD, theory of change",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "GSMA Connected Women — Theory of Change for Mobile Gender Gap",
        "organizacion": "GSMA / Connected Women",
        "tipo_org": "Alianza empresarial",
        "sector": "Género / Igualdad",
        "subsector": "Brecha digital de género",
        "pais_contexto": "Global",
        "año": "2020",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Programa específico",
        "url": "https://www.gsma.com/connected-women/",
        "url_pdf": "https://www.gsma.com/mobilefordevelopment/wp-content/uploads/2020/09/GSMA-Connected-Women-Theory-of-Change.pdf",
        "descripcion": "ToC de GSMA Connected Women para cerrar la brecha de género en acceso a telefonía movil. Explica como mayor conectividad de mujeres genera empoderamiento economico.",
        "palabras_clave": "mobile, gender gap, women, digital inclusion, GSMA, theory of change",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Theory of Change — Violence Against Women and Girls Prevention",
        "organizacion": "What Works to Prevent Violence (DFID / UKAID)",
        "tipo_org": "Programa de investigacion",
        "sector": "Género / Igualdad",
        "subsector": "Violencia contra la mujer",
        "pais_contexto": "Africa / Asia",
        "año": "2018",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Programa específico",
        "url": "https://www.whatworks.co.za/resources/theory-of-change",
        "url_pdf": "https://www.whatworks.co.za/documents/publications/214-what-works-toc-2018/file",
        "descripcion": "ToC del programa What Works para prevencion de violencia contra la mujer. Financiado por DFID. Explica la logica de cambio en intervencion en VCM/VCN.",
        "palabras_clave": "violence against women, VAWG, prevention, theory of change, What Works, DFID",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Skoll Foundation Theory of Change — Systems Change through Social Entrepreneurship",
        "organizacion": "Skoll Foundation",
        "tipo_org": "Fundacion",
        "sector": "Empresa social / Emprendimiento",
        "subsector": "Emprendimiento social a escala",
        "pais_contexto": "Global",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Documento estrategico",
        "nivel_toc": "Organizacional",
        "url": "https://skoll.org/about/theory-of-change/",
        "url_pdf": "https://skoll.org/wp-content/uploads/2019/05/Skoll-Theory-of-Change.pdf",
        "descripcion": "ToC de Skoll Foundation para el cambio sistemico a traves del emprendimiento social. Explica como los emprendedores sociales a escala modifican sistemas que afectan a millones.",
        "palabras_clave": "social entrepreneurship, systems change, Skoll, theory of change, scale, transformation",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Teoria del Cambio — Banco Interamericano de Desarrollo (BID) Marco de Resultados",
        "organizacion": "Banco Interamericano de Desarrollo (BID)",
        "tipo_org": "Banco multilateral",
        "sector": "Desarrollo economico / Pobreza",
        "subsector": "Operaciones de desarrollo",
        "pais_contexto": "America Latina",
        "año": "2020",
        "idioma": "ES",
        "tipo_documento": "Guia metodologica",
        "nivel_toc": "Marco general",
        "url": "https://publications.iadb.org/en/theory-of-change",
        "url_pdf": "https://publications.iadb.org/publications/spanish/document/teoria-del-cambio.pdf",
        "descripcion": "Marco del BID para construir teoria del cambio en operaciones de desarrollo. Guia para equipos tecnicos en la definicion de cadenas de resultados y supuestos.",
        "palabras_clave": "BID, teoria del cambio, cadena de resultados, desarrollo, America Latina",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Theory of Change for Peacebuilding — CDA Collaborative Learning",
        "organizacion": "CDA Collaborative Learning Projects",
        "tipo_org": "Think tank",
        "sector": "Paz y reconciliacion",
        "subsector": "Construccion de paz",
        "pais_contexto": "Global",
        "año": "2016",
        "idioma": "EN",
        "tipo_documento": "Guia metodologica",
        "nivel_toc": "Marco general",
        "url": "https://www.cdacollaborative.org/publication/theory-of-change-for-peacebuilding/",
        "url_pdf": "https://www.cdacollaborative.org/wp-content/uploads/2016/04/Theory-of-Change-Peacebuilding.pdf",
        "descripcion": "Guia de CDA para aplicar ToC en programas de construccion de paz. Aborda la complejidad del cambio en contextos de conflicto y post-conflicto.",
        "palabras_clave": "peacebuilding, conflict, theory of change, CDA, peace, complexity",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Theory of Change for Nutrition Sensitive Agriculture",
        "organizacion": "FAO / IFAD / CGIAR",
        "tipo_org": "ONU / CGIAR",
        "sector": "Nutricion / Seguridad alimentaria",
        "subsector": "Agricultura sensible a la nutricion",
        "pais_contexto": "Global",
        "año": "2018",
        "idioma": "EN",
        "tipo_documento": "Documento tecnico",
        "nivel_toc": "Marco general",
        "url": "https://www.fao.org/nutrition/activities/theory-of-change/en/",
        "url_pdf": "https://www.fao.org/3/i8442en/I8442EN.pdf",
        "descripcion": "Marco de teoria del cambio para la agricultura sensible a la nutricion. Explica como las intervenciones agricolas pueden generar mejoras en los resultados nutricionales.",
        "palabras_clave": "nutrition sensitive agriculture, FAO, food security, theory of change, nutrition",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Voluntary Service Overseas (VSO) Theory of Change",
        "organizacion": "VSO International",
        "tipo_org": "ONG internacional",
        "sector": "Desarrollo internacional",
        "subsector": "Voluntariado para el desarrollo",
        "pais_contexto": "Global",
        "año": "2018",
        "idioma": "EN",
        "tipo_documento": "Documento estrategico",
        "nivel_toc": "Organizacional",
        "url": "https://www.vsointernational.org/our-work/theory-of-change",
        "url_pdf": "https://www.vsointernational.org/sites/vso_international/files/VSO-Theory-of-Change.pdf",
        "descripcion": "ToC de VSO para el voluntariado como palanca de desarrollo. Explica como voluntarios de todas las nacionalidades generan cambio en salud, educacion y medios de vida.",
        "palabras_clave": "volunteering, VSO, development, theory of change, education, health, livelihoods",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Mercy Corps Theory of Change — Resilience and Livelihoods",
        "organizacion": "Mercy Corps",
        "tipo_org": "ONG internacional",
        "sector": "Accion humanitaria",
        "subsector": "Resiliencia y medios de vida",
        "pais_contexto": "Global",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Organizacional",
        "url": "https://www.mercycorps.org/our-work/our-theory-of-change",
        "url_pdf": "https://www.mercycorps.org/sites/default/files/2019-11/mercy-corps-theory-of-change.pdf",
        "descripcion": "ToC de Mercy Corps para la construccion de resiliencia y medios de vida en contextos fragiles. Integra respuesta humanitaria con desarrollo a largo plazo.",
        "palabras_clave": "resilience, livelihoods, Mercy Corps, theory of change, fragile states, humanitarian",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Theory of Change in Criminal Justice Reform",
        "organizacion": "Prison Reform Trust / T2A Alliance",
        "tipo_org": "ONG",
        "sector": "Justicia / Sistema penal",
        "subsector": "Reforma del sistema penal",
        "pais_contexto": "UK",
        "año": "2017",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Programa especifico",
        "url": "https://prisonreformtrust.org.uk/theory-of-change",
        "url_pdf": "https://prisonreformtrust.org.uk/wp-content/uploads/old_files/Documents/theory_of_change.pdf",
        "descripcion": "ToC de Prison Reform Trust para la reforma del sistema penal en UK. Explica como la advocacy, el litigio estrategico y el apoyo a reclusos generan cambios sistemicos.",
        "palabras_clave": "criminal justice, prison reform, theory of change, advocacy, UK, recidivism",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Theory of Change — Sport for Development",
        "organizacion": "Comic Relief / StreetGames",
        "tipo_org": "ONG",
        "sector": "Deporte para el desarrollo",
        "subsector": "Deporte como herramienta de cambio social",
        "pais_contexto": "UK",
        "año": "2018",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Marco general",
        "url": "https://www.streetgames.org/learning-resources/theory-of-change",
        "url_pdf": "https://www.streetgames.org/wp-content/uploads/StreetGames-Theory-of-Change.pdf",
        "descripcion": "ToC de StreetGames para el deporte como herramienta de desarrollo en comunidades marginadas. Explica como el deporte genera bienestar, inclusion social y habilidades para la vida.",
        "palabras_clave": "sport for development, theory of change, StreetGames, youth, community, wellbeing",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Teoria del Cambio — Escuelas Nueva Colombia",
        "organizacion": "Escuela Nueva Activa",
        "tipo_org": "ONG / Empresa social",
        "sector": "Educacion",
        "subsector": "Educacion rural en Colombia",
        "pais_contexto": "Colombia",
        "año": "2019",
        "idioma": "ES",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Programa especifico",
        "url": "https://www.escuelanueva.org/portal/es/modelo-escuela-nueva/teoria-del-cambio.html",
        "url_pdf": "https://www.escuelanueva.org/portal/es/images/EN-teoria-del-cambio.pdf",
        "descripcion": "Teoria del cambio del modelo Escuela Nueva para educacion rural en Colombia. Explica como el aprendizaje activo y participativo mejora la calidad educativa en escuelas multigrado.",
        "palabras_clave": "Escuela Nueva, educacion rural, Colombia, teoria del cambio, aprendizaje activo",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Theory of Change for Microfinance Impact",
        "organizacion": "Grameen Foundation",
        "tipo_org": "Fundacion",
        "sector": "Inclusion financiera",
        "subsector": "Microfinanzas",
        "pais_contexto": "Asia / Africa",
        "año": "2016",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Organizacional",
        "url": "https://grameenfoundation.org/our-work/theory-of-change",
        "url_pdf": "https://grameenfoundation.org/storage/documents/Grameen-Foundation-Theory-of-Change.pdf",
        "descripcion": "ToC de Grameen Foundation para el impacto de las microfinanzas. Explica como el acceso a credito y servicios financieros genera empoderamiento economico en mujeres de bajos ingresos.",
        "palabras_clave": "microfinance, Grameen, women, financial inclusion, theory of change, poverty",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Theory of Change for Arts and Culture — The British Council",
        "organizacion": "British Council",
        "tipo_org": "Institucion cultural publica",
        "sector": "Arte y cultura",
        "subsector": "Diplomacia cultural",
        "pais_contexto": "Global",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Documento estrategico",
        "nivel_toc": "Organizacional",
        "url": "https://www.britishcouncil.org/arts/theory-of-change",
        "url_pdf": "https://www.britishcouncil.org/sites/default/files/bc_theory_of_change.pdf",
        "descripcion": "ToC del British Council para la diplomacia cultural. Explica como las artes, la educacion y la cultura generan confianza mutua entre paises.",
        "palabras_clave": "arts, culture, British Council, cultural diplomacy, theory of change, soft power",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Theory of Change — Corporate Social Responsibility (CSR) Programs",
        "organizacion": "Business in the Community (BITC)",
        "tipo_org": "Red empresarial",
        "sector": "RSE / Empresa y sociedad",
        "subsector": "Programas de responsabilidad social empresarial",
        "pais_contexto": "UK",
        "año": "2020",
        "idioma": "EN",
        "tipo_documento": "Guia metodologica",
        "nivel_toc": "Marco general",
        "url": "https://www.bitc.org.uk/report/theory-of-change/",
        "url_pdf": "https://www.bitc.org.uk/wp-content/uploads/2020/01/bitc-theory-of-change-guide.pdf",
        "descripcion": "Guia de BITC para construir ToC en programas de RSE corporativa. Ayuda a empresas a articular logica de cambio de sus inversiones sociales.",
        "palabras_clave": "CSR, corporate social responsibility, theory of change, BITC, social investment, business",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Reporte de Impacto Social — Teoria del Cambio Fundacion Bolivar Davivienda",
        "organizacion": "Fundacion Bolivar Davivienda",
        "tipo_org": "Fundacion empresarial",
        "sector": "Educacion",
        "subsector": "Educacion financiera y emprendimiento",
        "pais_contexto": "Colombia",
        "año": "2022",
        "idioma": "ES",
        "tipo_documento": "Informe de impacto",
        "nivel_toc": "Organizacional",
        "url": "https://www.fundacionbolivardavivienda.org/impacto",
        "url_pdf": "https://www.fundacionbolivardavivienda.org/sites/default/files/teoria-del-cambio-2022.pdf",
        "descripcion": "Teoria del cambio de la Fundacion Bolivar Davivienda. Articula como sus programas de educacion y emprendimiento generan bienestar en comunidades colombianas.",
        "palabras_clave": "Fundacion Bolivar Davivienda, teoria del cambio, educacion, Colombia, emprendimiento",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Theory of Change for Sustainable Urban Development",
        "organizacion": "C40 Cities Climate Leadership Group",
        "tipo_org": "Red de ciudades",
        "sector": "Clima / Medio ambiente",
        "subsector": "Ciudades sostenibles",
        "pais_contexto": "Global",
        "año": "2020",
        "idioma": "EN",
        "tipo_documento": "Documento estrategico",
        "nivel_toc": "Organizacional",
        "url": "https://www.c40.org/our-theory-of-change",
        "url_pdf": "https://www.c40.org/wp-content/uploads/2020/06/C40-Theory-of-Change.pdf",
        "descripcion": "ToC de C40 Cities para el desarrollo urbano sostenible y accion climatica. Explica como las ciudades actuan como laboratorios de cambio climatico global.",
        "palabras_clave": "cities, climate change, urban, theory of change, C40, sustainable development",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Theory of Change — Food and Land Use Coalition (FOLU)",
        "organizacion": "Food and Land Use Coalition (FOLU)",
        "tipo_org": "Coalicion internacional",
        "sector": "Nutricion / Seguridad alimentaria",
        "subsector": "Sistemas alimentarios sostenibles",
        "pais_contexto": "Global",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Documento estrategico",
        "nivel_toc": "Marco general",
        "url": "https://www.foodandlandusecoalition.org/theory-of-change/",
        "url_pdf": "https://www.foodandlandusecoalition.org/wp-content/uploads/2019/09/FOLU-Theory-of-Change.pdf",
        "descripcion": "ToC de FOLU para la transformacion de los sistemas alimentarios y de uso de la tierra. Explica como cambios en politica, mercados y sociedad pueden generar sistemas alimentarios sostenibles.",
        "palabras_clave": "food systems, land use, FOLU, theory of change, sustainable agriculture, transformation",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Theory of Change for Workforce Development Programs",
        "organizacion": "Urban Institute",
        "tipo_org": "Think tank",
        "sector": "Empleo / Juventud",
        "subsector": "Desarrollo de la fuerza laboral",
        "pais_contexto": "USA",
        "año": "2017",
        "idioma": "EN",
        "tipo_documento": "Documento tecnico",
        "nivel_toc": "Marco general",
        "url": "https://www.urban.org/research/publication/theory-of-change-workforce-development",
        "url_pdf": "https://www.urban.org/sites/default/files/publication/93461/theory-of-change-workforce.pdf",
        "descripcion": "Marco de ToC del Urban Institute para programas de desarrollo de la fuerza laboral. Identifica supuestos clave sobre mercados laborales, competencias y empleabilidad.",
        "palabras_clave": "workforce development, employment, Urban Institute, theory of change, skills, labor market",
        "estado_descarga": "pendiente",
    },
]

# Filter out already existing URLs
new_records_filtered = [
    r for r in new_records if r["url_pdf"] not in existing_urls
]

print(f"Records to add: {len(new_records_filtered)} (of {len(new_records)} total)")

# Write updated CSV
next_id = max_id + 1
with open(DB_PATH, "a", encoding="utf-8", newline="") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    for rec in new_records_filtered:
        rec["id"] = str(next_id)
        writer.writerow(rec)
        print(f"  [{next_id}] Added: {rec['titulo'][:60]}")
        next_id += 1

print(f"\nDatabase now has {max_id + len(new_records_filtered)} records")
