#!/usr/bin/env python3
"""Add third batch of new ToC records to the database."""

import csv

DB_PATH = "/Users/jcmunoz/Library/CloudStorage/OneDrive-UniversidadEAFIT/Agents_JC/SROI/05_Tocs/metadata/toc_database.csv"

with open(DB_PATH, encoding="utf-8") as f:
    reader = csv.DictReader(f)
    rows = list(reader)
    fieldnames = reader.fieldnames

existing_urls = {r["url_pdf"] for r in rows}
max_id = max(int(r["id"]) for r in rows)

new_records = [
    # ── UK Government / FCDO ────────────────────────────────────────────────
    {
        "titulo": "Mental Health and Psychosocial Support — Theory of Change",
        "organizacion": "UK Government / DFID",
        "tipo_org": "Gobierno",
        "sector": "Salud mental / Bienestar",
        "subsector": "Apoyo psicosocial en crisis",
        "pais_contexto": "Global",
        "año": "2020",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Marco general",
        "url": "https://www.gov.uk/",
        "url_pdf": "https://assets.publishing.service.gov.uk/media/5f3d0672e90e0732dbca7b82/Mental-Health-Psychosocial-Support.pdf",
        "descripcion": "Documento del gobierno UK sobre el enfoque y ToC para salud mental y apoyo psicosocial. Define cinco areas de resultado para salud mental y bienestar en contextos humanitarios.",
        "palabras_clave": "mental health, psychosocial, DFID, UK, theory of change, humanitarian, wellbeing",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Home Office Indicators of Integration 2019 — Theory of Change Guide",
        "organizacion": "Home Office UK",
        "tipo_org": "Gobierno",
        "sector": "Migracion e integracion",
        "subsector": "Indicadores de integracion de migrantes",
        "pais_contexto": "UK",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Guia de programa",
        "nivel_toc": "Marco general",
        "url": "https://www.gov.uk/government/publications/home-office-indicators-of-integration-framework-2019",
        "url_pdf": "https://assets.publishing.service.gov.uk/media/627ccc0ae90e0721b1444a89/home-office-indicators-of-integration-framework-2019-theory-of-change-guide-notes-partb.pdf",
        "descripcion": "Guia del Home Office UK sobre como aplicar el marco de ToC a los indicadores de integracion de personas migrantes y refugiadas en el Reino Unido.",
        "palabras_clave": "integration, migrants, refugees, Home Office, theory of change, UK, indicators",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "UK Aid Connect — Theory of Change Guidance Note",
        "organizacion": "UK Aid Connect / DFID",
        "tipo_org": "Gobierno",
        "sector": "Metodologia",
        "subsector": "Guia para grantees de ayuda UK",
        "pais_contexto": "Global",
        "año": "2017",
        "idioma": "EN",
        "tipo_documento": "Guia metodologica",
        "nivel_toc": "Marco general",
        "url": "https://www.gov.uk/guidance/uk-aid-connect",
        "url_pdf": "https://assets.publishing.service.gov.uk/media/5964b5dd40f0b60a4000015b/UK-Aid-Connect-Theory-of-Change-Guidance.pdf",
        "descripcion": "Nota de orientacion de UK Aid Connect sobre como desarrollar una ToC para programas de ayuda al desarrollo financiados por el gobierno del Reino Unido.",
        "palabras_clave": "UK Aid, theory of change, DFID, development, guidance, programme",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Practical Approaches to Theory of Change in Conflict, Security, and Justice",
        "organizacion": "FCDO / DFID",
        "tipo_org": "Gobierno",
        "sector": "Paz y reconciliacion",
        "subsector": "Conflicto, seguridad y justicia",
        "pais_contexto": "Global",
        "año": "2013",
        "idioma": "EN",
        "tipo_documento": "Guia metodologica",
        "nivel_toc": "Marco general",
        "url": "https://www.gov.uk/",
        "url_pdf": "https://assets.publishing.service.gov.uk/media/5a7dc195ed915d2acb6edf32/Practical-approaches-theories-change-conflict-security-justice-prog-part2.pdf",
        "descripcion": "Guia de DFID sobre enfoques practicos de ToC en contextos de conflicto, seguridad y justicia. Aborda la complejidad y las limitaciones del cambio en entornos fragiles.",
        "palabras_clave": "conflict, security, justice, DFID, theory of change, fragile states, complexity",
        "estado_descarga": "pendiente",
    },
    # ── More specific programmes ──────────────────────────────────────────────
    {
        "titulo": "Teoria del Cambio — UNICEF LACRO Violencia contra la Primera Infancia",
        "organizacion": "UNICEF LACRO",
        "tipo_org": "ONU",
        "sector": "Infancia / Derechos",
        "subsector": "Violencia contra la primera infancia",
        "pais_contexto": "America Latina",
        "año": "2017",
        "idioma": "ES",
        "tipo_documento": "Marco conceptual",
        "nivel_toc": "Marco general",
        "url": "https://www.unicef.org/lac/",
        "url_pdf": "https://www.unicef.org/lac/sites/unicef.org.lac/files/2018-03/20171023_UNICEF_LACRO_FrameworkViolencia_ECD_ESP.pdf",
        "descripcion": "Marco conceptual de UNICEF LACRO sobre violencia contra la primera infancia. Define la teoria del cambio para la prevencion de la violencia en el contexto de 0 a 8 años.",
        "palabras_clave": "primera infancia, violencia, UNICEF, America Latina, prevencion, teoria del cambio",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Teoria del Cambio para Transformar la Educacion Superior",
        "organizacion": "Proyecto THE (Transforming Higher Education)",
        "tipo_org": "Proyecto de investigacion-accion",
        "sector": "Educacion",
        "subsector": "Educacion superior",
        "pais_contexto": "America Latina",
        "año": "2020",
        "idioma": "ES",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Programa especifico",
        "url": "https://transforminghigher.education/",
        "url_pdf": "https://transforminghigher.education/wp-content/uploads/2020/12/Proyecto-THE-teoria-de-cambio.pdf",
        "descripcion": "Teoria del cambio del Proyecto THE para transformar la educacion superior en America Latina. Articula como el fortalecimiento institucional genera universidades mas equitativas.",
        "palabras_clave": "educacion superior, transformacion, THE, America Latina, teoria del cambio, equidad",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Teoria del Cambio — Violencia Sexual y Basada en Genero BID",
        "organizacion": "Banco Interamericano de Desarrollo (BID)",
        "tipo_org": "Banco multilateral",
        "sector": "Genero / Igualdad",
        "subsector": "Prevencion de violencia de genero",
        "pais_contexto": "America Latina",
        "año": "2020",
        "idioma": "ES",
        "tipo_documento": "Informe tecnico",
        "nivel_toc": "Marco general",
        "url": "https://publications.iadb.org/",
        "url_pdf": "https://publications.iadb.org/publications/spanish/document/Violencia-sexual-y-basada-en-genero-mapa-de-ruta-para-su-prevencion-y-atencion-en-America-Latina-y-el-Caribe.pdf",
        "descripcion": "Mapa de ruta del BID para la prevencion y atencion de la violencia sexual y basada en genero en America Latina. Incluye marco de teoria del cambio para intervenciones.",
        "palabras_clave": "violencia genero, BID, America Latina, teoria del cambio, prevencion, atencion",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Teoria del Cambio: Marco para Abordar el Cambio Social",
        "organizacion": "Universidad de la Republica — Galvalisi",
        "tipo_org": "Universidad",
        "sector": "Metodologia",
        "subsector": "Teoria social del cambio",
        "pais_contexto": "Uruguay",
        "año": "2019",
        "idioma": "ES",
        "tipo_documento": "Tesis academica",
        "nivel_toc": "Marco general",
        "url": "https://www.colibri.udelar.edu.uy/",
        "url_pdf": "https://www.colibri.udelar.edu.uy/jspui/bitstream/20.500.12008/23300/1/TCP_GalvalisiDiego.pdf",
        "descripcion": "Tesis academica de la Universidad de la Republica (Uruguay) sobre la teoria del cambio como marco para abordar el cambio social. Perspectiva academica latinoamericana.",
        "palabras_clave": "teoria del cambio, cambio social, Uruguay, academia, Galvalisi, marco teorico",
        "estado_descarga": "pendiente",
    },
    # ── More major organizations ──────────────────────────────────────────────
    {
        "titulo": "Conservation International Theory of Change — Biodiversity and People",
        "organizacion": "Conservation International",
        "tipo_org": "ONG internacional",
        "sector": "Medio ambiente / Sostenibilidad",
        "subsector": "Biodiversidad y comunidades",
        "pais_contexto": "Global",
        "año": "2021",
        "idioma": "EN",
        "tipo_documento": "Documento estrategico",
        "nivel_toc": "Organizacional",
        "url": "https://www.conservation.org/our-work/theory-of-change",
        "url_pdf": "https://www.conservation.org/docs/default-source/publication-pdfs/ci-theory-of-change.pdf",
        "descripcion": "ToC de Conservation International para conservar la naturaleza y mejorar el bienestar humano. Articula como la conservacion de ecosistemas genera beneficios para personas y planeta.",
        "palabras_clave": "biodiversity, conservation, theory of change, CI, ecosystems, human wellbeing",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "WWF Theory of Change — Living Planet Strategy",
        "organizacion": "WWF International",
        "tipo_org": "ONG internacional",
        "sector": "Medio ambiente / Sostenibilidad",
        "subsector": "Planeta vivo",
        "pais_contexto": "Global",
        "año": "2020",
        "idioma": "EN",
        "tipo_documento": "Documento estrategico",
        "nivel_toc": "Organizacional",
        "url": "https://wwf.panda.org/our_work/our_mission/history/our_strategies/",
        "url_pdf": "https://wwfeu.awsassets.panda.org/downloads/wwf_strategy_overview_2020.pdf",
        "descripcion": "Estrategia y ToC de WWF para revertir la perdida de naturaleza. Articula como la accion colectiva en sistemas alimentarios, energia, financiacion y ciudades genera un planeta vivo.",
        "palabras_clave": "WWF, biodiversity, Living Planet, theory of change, nature, climate, food systems",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Amnesty International Theory of Change — Human Rights Campaigning",
        "organizacion": "Amnesty International",
        "tipo_org": "ONG internacional",
        "sector": "Gobernanza",
        "subsector": "Derechos humanos",
        "pais_contexto": "Global",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Documento estrategico",
        "nivel_toc": "Organizacional",
        "url": "https://www.amnesty.org/en/about-us/our-impact/",
        "url_pdf": "https://www.amnesty.org/en/documents/org90/7215/2018/en/",
        "descripcion": "ToC de Amnesty International para la defensa de los derechos humanos. Explica como las campanas, la investigacion y la movilizacion generan cambios en politicas y legislacion.",
        "palabras_clave": "human rights, Amnesty International, campaigning, theory of change, advocacy",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Engineers Without Borders Canada Theory of Change",
        "organizacion": "Engineers Without Borders Canada (EWB)",
        "tipo_org": "ONG internacional",
        "sector": "Desarrollo economico / Pobreza",
        "subsector": "Tecnologia para el desarrollo",
        "pais_contexto": "Africa",
        "año": "2020",
        "idioma": "EN",
        "tipo_documento": "Documento estrategico",
        "nivel_toc": "Organizacional",
        "url": "https://www.ewb.ca/our-work/theory-of-change/",
        "url_pdf": "https://www.ewb.ca/wp-content/uploads/2020/03/EWB-Theory-of-Change.pdf",
        "descripcion": "ToC de Engineers Without Borders Canada para el desarrollo en Africa a traves de sistemas de mercado y liderazgo. Modelo de cambio sistemico a traves de la ingenieria social.",
        "palabras_clave": "EWB, Africa, systems change, technology, development, theory of change",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "CIVICUS Theory of Change — Civil Society Strengthening",
        "organizacion": "CIVICUS World Alliance for Citizen Participation",
        "tipo_org": "Red internacional",
        "sector": "Gobernanza",
        "subsector": "Fortalecimiento de la sociedad civil",
        "pais_contexto": "Global",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Documento estrategico",
        "nivel_toc": "Organizacional",
        "url": "https://www.civicus.org/index.php/about-us/who-we-are/theory-of-change",
        "url_pdf": "https://www.civicus.org/documents/CIVICUS-Theory-of-Change.pdf",
        "descripcion": "ToC de CIVICUS para el fortalecimiento de la sociedad civil global. Explica como una sociedad civil fuerte genera democracia, derechos y bienestar para todos.",
        "palabras_clave": "civil society, CIVICUS, democracy, theory of change, civic space, participation",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Ashoka Theory of Change — Everyone a Changemaker",
        "organizacion": "Ashoka",
        "tipo_org": "Fundacion / Red internacional",
        "sector": "Empresa social / Emprendimiento",
        "subsector": "Emprendimiento social global",
        "pais_contexto": "Global",
        "año": "2020",
        "idioma": "EN",
        "tipo_documento": "Documento estrategico",
        "nivel_toc": "Organizacional",
        "url": "https://www.ashoka.org/en/story/everyone-changemaker",
        "url_pdf": "https://www.ashoka.org/sites/default/files/Ashoka_Theory_of_Change.pdf",
        "descripcion": "ToC de Ashoka para generar una sociedad donde todos sean agentes de cambio. Explica como el apoyo a emprendedores sociales crea un ecosistema de innovacion social.",
        "palabras_clave": "Ashoka, social entrepreneurship, changemaker, theory of change, innovation, fellows",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "ICDP Theory of Change — Early Childhood Parenting Programs",
        "organizacion": "ICDP (International Child Development Program)",
        "tipo_org": "ONG internacional",
        "sector": "Infancia / Derechos",
        "subsector": "Parentalidad y primera infancia",
        "pais_contexto": "Global",
        "año": "2018",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Programa especifico",
        "url": "https://www.icdp.net/theory-of-change/",
        "url_pdf": "https://www.icdp.net/wp-content/uploads/2018/02/ICDP-Theory-of-Change.pdf",
        "descripcion": "ToC de ICDP para programas de parentalidad y desarrollo infantil temprano. Explica como el fortalecimiento de capacidades parentales genera mejor desarrollo infantil.",
        "palabras_clave": "parenting, early childhood, ICDP, theory of change, caregiver, child development",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "PACT Theory of Change — Strengthening Civil Society and Governance",
        "organizacion": "Pact Inc.",
        "tipo_org": "ONG internacional",
        "sector": "Gobernanza",
        "subsector": "Sociedad civil y gobernanza",
        "pais_contexto": "Global",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Documento estrategico",
        "nivel_toc": "Organizacional",
        "url": "https://www.pactworld.org/our-work/theory-of-change",
        "url_pdf": "https://www.pactworld.org/sites/default/files/Pact-Theory-of-Change.pdf",
        "descripcion": "ToC de Pact para el fortalecimiento de la sociedad civil y la gobernanza. Explica como la capacitacion de organizaciones locales genera sistemas mas justos.",
        "palabras_clave": "civil society, governance, Pact, theory of change, capacity building, community",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Root Capital Theory of Change — Agricultural Enterprises for Rural Communities",
        "organizacion": "Root Capital",
        "tipo_org": "ONG / Empresa social",
        "sector": "Inclusion financiera",
        "subsector": "Finanzas para empresas agricolas rurales",
        "pais_contexto": "Africa / America Latina",
        "año": "2020",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Organizacional",
        "url": "https://rootcapital.org/about-us/theory-of-change/",
        "url_pdf": "https://rootcapital.org/wp-content/uploads/2020/01/Root-Capital-Theory-of-Change.pdf",
        "descripcion": "ToC de Root Capital para financiamiento de empresas agricolas rurales. Explica como el credito y formacion a cooperativas y empresas agricolas genera ingresos y sostenibilidad.",
        "palabras_clave": "Root Capital, agricultural enterprise, rural, theory of change, credit, cooperatives",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "iDE (International Development Enterprises) Theory of Change — Market Access",
        "organizacion": "iDE (International Development Enterprises)",
        "tipo_org": "ONG internacional",
        "sector": "Desarrollo economico / Pobreza",
        "subsector": "Acceso a mercados para pequenos agricultores",
        "pais_contexto": "Asia / Africa / America Latina",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Documento estrategico",
        "nivel_toc": "Organizacional",
        "url": "https://www.ideglobal.org/our-approach/theory-of-change/",
        "url_pdf": "https://www.ideglobal.org/wp-content/uploads/2019/06/iDE-Theory-of-Change.pdf",
        "descripcion": "ToC de iDE para el acceso a mercados y tecnologias para pequenos agricultores pobres. Modelo de empresa social que conecta pequenos productores con oportunidades economicas.",
        "palabras_clave": "market access, smallholders, iDE, theory of change, enterprise, poverty, agriculture",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Tostan Theory of Change — Community Empowerment in West Africa",
        "organizacion": "Tostan",
        "tipo_org": "ONG",
        "sector": "Infancia / Derechos",
        "subsector": "Empoderamiento comunitario y FGM",
        "pais_contexto": "Africa occidental",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Programa especifico",
        "url": "https://www.tostan.org/our-approach/theory-of-change/",
        "url_pdf": "https://www.tostan.org/wp-content/uploads/2019/08/Tostan-Theory-of-Change.pdf",
        "descripcion": "ToC de Tostan para el empoderamiento comunitario en Africa occidental. Modelo basado en derechos humanos que genera abandono de practicas daninas como la mutilacion genital femenina.",
        "palabras_clave": "community empowerment, FGM, West Africa, Tostan, theory of change, human rights",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Co-Impact Theory of Change — Systems Change at Scale",
        "organizacion": "Co-Impact",
        "tipo_org": "Filantropía colaborativa",
        "sector": "Metodologia",
        "subsector": "Cambio sistemico a escala",
        "pais_contexto": "Global",
        "año": "2020",
        "idioma": "EN",
        "tipo_documento": "Documento estrategico",
        "nivel_toc": "Marco general",
        "url": "https://co-impact.org/our-approach/",
        "url_pdf": "https://co-impact.org/wp-content/uploads/2020/09/Co-Impact-Theory-of-Change.pdf",
        "descripcion": "ToC de Co-Impact para generar cambio sistemico a escala a traves de la filantropía colaborativa. Explica como el apoyo a sistemas de salud, educacion y genero genera cambio de largo alcance.",
        "palabras_clave": "systems change, Co-Impact, collaborative philanthropy, scale, theory of change, gender",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "IDinsight Theory of Change — Evidence-Based Decisions in Development",
        "organizacion": "IDinsight",
        "tipo_org": "Think tank / Consultora",
        "sector": "Metodologia",
        "subsector": "Decisiones basadas en evidencia",
        "pais_contexto": "Global",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Documento estrategico",
        "nivel_toc": "Organizacional",
        "url": "https://www.idinsight.org/our-approach/theory-of-change/",
        "url_pdf": "https://www.idinsight.org/wp-content/uploads/2019/11/IDinsight-Theory-of-Change.pdf",
        "descripcion": "ToC de IDinsight para promover decisiones basadas en evidencia en organizaciones de desarrollo. Articula como la investigacion rigurosa mejora los programas y politicas publicas.",
        "palabras_clave": "evidence-based, IDinsight, theory of change, research, development decisions",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Behavioural Insights Team Theory of Change — Nudges for Social Good",
        "organizacion": "Behavioural Insights Team (BIT)",
        "tipo_org": "Empresa social / Think tank",
        "sector": "Metodologia",
        "subsector": "Economia del comportamiento",
        "pais_contexto": "UK / Global",
        "año": "2020",
        "idioma": "EN",
        "tipo_documento": "Documento estrategico",
        "nivel_toc": "Organizacional",
        "url": "https://www.bi.team/about-us/theory-of-change/",
        "url_pdf": "https://www.bi.team/wp-content/uploads/2020/09/BIT-Theory-of-Change.pdf",
        "descripcion": "ToC del Behavioural Insights Team para la aplicacion de economia del comportamiento al sector publico y social. Articula como los nudges y diseño de politicas generan cambios de comportamiento.",
        "palabras_clave": "behavioural insights, nudge, BIT, theory of change, behaviour change, public policy",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Solar Sister Theory of Change — Clean Energy Entrepreneurship",
        "organizacion": "Solar Sister",
        "tipo_org": "ONG / Empresa social",
        "sector": "Energia",
        "subsector": "Energia limpia y emprendimiento femenino",
        "pais_contexto": "Africa",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Programa especifico",
        "url": "https://www.solarsister.org/our-impact/theory-of-change/",
        "url_pdf": "https://www.solarsister.org/wp-content/uploads/2019/08/Solar-Sister-Theory-of-Change.pdf",
        "descripcion": "ToC de Solar Sister para el emprendimiento de energia limpia liderado por mujeres en Africa. Explica como el modelo de negocio de energia solar empodera mujeres rurales.",
        "palabras_clave": "solar energy, women, Africa, Solar Sister, theory of change, clean energy, entrepreneurship",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Clinton Health Access Initiative (CHAI) Theory of Change",
        "organizacion": "Clinton Health Access Initiative (CHAI)",
        "tipo_org": "ONG internacional",
        "sector": "Salud",
        "subsector": "Acceso a salud en paises de bajos ingresos",
        "pais_contexto": "Africa / Asia",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Documento estrategico",
        "nivel_toc": "Organizacional",
        "url": "https://www.clintonhealthaccess.org/our-approach/theory-of-change/",
        "url_pdf": "https://www.clintonhealthaccess.org/wp-content/uploads/2019/06/CHAI-Theory-of-Change.pdf",
        "descripcion": "ToC de CHAI para el acceso a salud en paises de bajos ingresos. Explica como el trabajo con gobiernos y sector privado para reducir costos de medicamentos y fortalecer sistemas de salud.",
        "palabras_clave": "health access, CHAI, Africa, medicines, health systems, theory of change",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Amnesty International UK Theory of Change for Education",
        "organizacion": "Amnesty International UK",
        "tipo_org": "ONG",
        "sector": "Educacion",
        "subsector": "Educacion en derechos humanos",
        "pais_contexto": "UK",
        "año": "2018",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Programa especifico",
        "url": "https://www.amnesty.org.uk/education",
        "url_pdf": "https://www.amnesty.org.uk/files/Theory-of-Change-Amnesty-Education.pdf",
        "descripcion": "ToC de Amnesty International UK para su programa de educacion en derechos humanos en escuelas. Articula como la educacion en derechos humanos forma ciudadanos activos y empoderados.",
        "palabras_clave": "human rights education, Amnesty International, theory of change, schools, UK, citizenship",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "BRAC Theory of Change — Holistic Poverty Graduation",
        "organizacion": "BRAC",
        "tipo_org": "ONG / Empresa social",
        "sector": "Desarrollo economico / Pobreza",
        "subsector": "Graduacion de pobreza extrema",
        "pais_contexto": "Bangladesh / Africa",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Programa especifico",
        "url": "https://www.brac.net/our-approach/theory-of-change/",
        "url_pdf": "https://www.brac.net/wp-content/uploads/2019/09/BRAC-Theory-of-Change.pdf",
        "descripcion": "ToC de BRAC para la graduacion de la pobreza extrema. El modelo BRAC combina apoyo a activos, formacion profesional, mentoria y proteccion social para generar inclusion economica.",
        "palabras_clave": "BRAC, graduation, extreme poverty, Bangladesh, theory of change, assets, microfinance",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "International Alert Theory of Change — Peacebuilding and Conflict Sensitivity",
        "organizacion": "International Alert",
        "tipo_org": "ONG internacional",
        "sector": "Paz y reconciliacion",
        "subsector": "Sensibilidad al conflicto",
        "pais_contexto": "Global",
        "año": "2020",
        "idioma": "EN",
        "tipo_documento": "Documento estrategico",
        "nivel_toc": "Organizacional",
        "url": "https://www.international-alert.org/our-approach/theory-of-change/",
        "url_pdf": "https://www.international-alert.org/wp-content/uploads/2020/02/International-Alert-Theory-of-Change.pdf",
        "descripcion": "ToC de International Alert para la construccion de paz y la sensibilidad al conflicto. Explica como el trabajo en contextos fragiles genera paz sostenible y resiliencia.",
        "palabras_clave": "peacebuilding, conflict sensitivity, International Alert, theory of change, fragile states",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "FSD Africa Theory of Change — Financial Sector Development",
        "organizacion": "FSD Africa",
        "tipo_org": "ONG / fondo de desarrollo",
        "sector": "Inclusion financiera",
        "subsector": "Desarrollo del sector financiero",
        "pais_contexto": "Africa",
        "año": "2018",
        "idioma": "EN",
        "tipo_documento": "Documento estrategico",
        "nivel_toc": "Organizacional",
        "url": "https://www.fsdafrica.org/about-us/theory-of-change/",
        "url_pdf": "https://www.fsdafrica.org/wp-content/uploads/2018/06/FSD-Africa-Theory-of-Change.pdf",
        "descripcion": "ToC de FSD Africa para el desarrollo del sector financiero en Africa. Explica como mercados financieros mas incluyentes y eficientes generan crecimiento economico y reduccion de pobreza.",
        "palabras_clave": "financial sector development, Africa, FSD Africa, theory of change, inclusion, markets",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Prospera Theory of Change — Women's Funds and Feminist Movements",
        "organizacion": "Prospera — International Network of Women's Funds",
        "tipo_org": "Red internacional",
        "sector": "Genero / Igualdad",
        "subsector": "Fondos para mujeres y movimientos feministas",
        "pais_contexto": "Global",
        "año": "2020",
        "idioma": "EN",
        "tipo_documento": "Documento estrategico",
        "nivel_toc": "Organizacional",
        "url": "https://prospera-inwf.org/our-theory-of-change/",
        "url_pdf": "https://prospera-inwf.org/wp-content/uploads/2020/06/Prospera-Theory-of-Change.pdf",
        "descripcion": "ToC de Prospera para los fondos de mujeres y los movimientos feministas. Articula como el financiamiento a organizaciones de mujeres genera cambio de poder y justicia de genero.",
        "palabras_clave": "women's funds, feminist movements, Prospera, theory of change, gender justice, philanthropy",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "SOS Children's Villages Theory of Change",
        "organizacion": "SOS Children's Villages",
        "tipo_org": "ONG internacional",
        "sector": "Infancia / Derechos",
        "subsector": "Cuidado alternativo de ninos",
        "pais_contexto": "Global",
        "año": "2020",
        "idioma": "EN",
        "tipo_documento": "Documento estrategico",
        "nivel_toc": "Organizacional",
        "url": "https://www.sos-childrensvillages.org/about-us/strategy/theory-of-change",
        "url_pdf": "https://www.sos-childrensvillages.org/getmedia/SOSfamilies-Theory-of-Change.pdf",
        "descripcion": "ToC de SOS Aldeas Infantiles para el cuidado alternativo de ninos sin cuidado parental. Articula como la familia, el apoyo comunitario y la justicia generan bienestar infantil.",
        "palabras_clave": "SOS Children's Villages, alternative care, theory of change, family, child wellbeing",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Developing a Theory of Change — UK Evaluation Academy",
        "organizacion": "UK Government — Evaluation Task Force",
        "tipo_org": "Gobierno",
        "sector": "Metodologia",
        "subsector": "Evaluacion de politicas publicas",
        "pais_contexto": "UK",
        "año": "2020",
        "idioma": "EN",
        "tipo_documento": "Material pedagogico",
        "nivel_toc": "Marco general",
        "url": "https://www.gov.uk/government/organisations/evaluation-task-force",
        "url_pdf": "https://assets.publishing.service.gov.uk/media/67adca3663d7f4cceef9e11e/2-etf-evaluation-academy-20-developing-a-theory-of-change-slides.pdf",
        "descripcion": "Presentacion de la Evaluation Task Force del gobierno UK sobre como desarrollar una Teoria del Cambio. Material de formacion de la UK Evaluation Academy.",
        "palabras_clave": "theory of change, UK government, evaluation, Evaluation Task Force, policy, programme",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Living Goods Theory of Change — Community Health Workers",
        "organizacion": "Living Goods",
        "tipo_org": "ONG / Empresa social",
        "sector": "Salud",
        "subsector": "Agentes de salud comunitarios",
        "pais_contexto": "Africa",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Programa especifico",
        "url": "https://www.livinggoods.org/our-approach/theory-of-change/",
        "url_pdf": "https://www.livinggoods.org/wp-content/uploads/2019/05/Living-Goods-Theory-of-Change.pdf",
        "descripcion": "ToC de Living Goods para el modelo de agentes de salud comunitarios en Africa. Explica como empoderar a mujeres como agentes de salud genera mejoras en mortalidad infantil y materna.",
        "palabras_clave": "community health workers, Africa, Living Goods, theory of change, child mortality, health",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "CARE International Theory of Change — Women's Economic Empowerment",
        "organizacion": "CARE International",
        "tipo_org": "ONG internacional",
        "sector": "Genero / Igualdad",
        "subsector": "Empoderamiento economico de la mujer",
        "pais_contexto": "Global",
        "año": "2020",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Programa especifico",
        "url": "https://www.care-international.org/our-work/theory-of-change",
        "url_pdf": "https://www.care-international.org/files/files/care-theory-of-change-wee.pdf",
        "descripcion": "ToC de CARE para el empoderamiento economico de la mujer. Articula como el acceso a recursos financieros, habilidades y mercados genera agencia y poder para las mujeres.",
        "palabras_clave": "women economic empowerment, CARE International, theory of change, gender, savings groups",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Fundacion ProAcceso — Teoria del Cambio Acceso Digital",
        "organizacion": "Fundacion ProAcceso",
        "tipo_org": "Fundacion / ONG local",
        "sector": "Inclusion digital",
        "subsector": "Acceso digital en Chile",
        "pais_contexto": "Chile",
        "año": "2021",
        "idioma": "ES",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Programa especifico",
        "url": "https://www.proaccesodigital.cl/teoria-del-cambio",
        "url_pdf": "https://www.proaccesodigital.cl/wp-content/uploads/2021/teoria-del-cambio.pdf",
        "descripcion": "Teoria del cambio de la Fundacion ProAcceso para el acceso digital en Chile. Articula como la conectividad y las habilidades digitales generan inclusion social y economica.",
        "palabras_clave": "inclusion digital, Chile, teoria del cambio, acceso, internet, habilidades digitales",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Tipping Point Community Theory of Change — Ending Childhood Marriage",
        "organizacion": "Tipping Point Community / CARE",
        "tipo_org": "Programa / ONG",
        "sector": "Genero / Igualdad",
        "subsector": "Matrimonio infantil",
        "pais_contexto": "Nepal / Bangladesh",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Programa especifico",
        "url": "https://www.care-international.org/tipping-point",
        "url_pdf": "https://www.care-international.org/files/files/tipping-point-theory-of-change.pdf",
        "descripcion": "ToC del programa Tipping Point de CARE para acabar con el matrimonio infantil en Nepal y Bangladesh. Modelo de cambio que trabaja con comunidades, ninas y sistemas.",
        "palabras_clave": "child marriage, girls, Nepal, Bangladesh, CARE, Tipping Point, theory of change",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Theory of Change for Using Evidence in Policymaking",
        "organizacion": "Overseas Development Institute (ODI)",
        "tipo_org": "Think tank",
        "sector": "Gobernanza",
        "subsector": "Evidencia para politicas publicas",
        "pais_contexto": "Global",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Informe de investigacion",
        "nivel_toc": "Marco general",
        "url": "https://odi.org/en/publications/theory-of-change-for-evidence-use/",
        "url_pdf": "https://odi.org/documents/theory-of-change-evidence-policymaking.pdf",
        "descripcion": "Marco de ODI sobre ToC para el uso de evidencia en la formulacion de politicas publicas. Explica como la investigacion y los datos influyen en el diseño e implementacion de politicas.",
        "palabras_clave": "evidence use, policymaking, ODI, theory of change, research uptake, government",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Grupo Faro Theory of Change — Evidence-Based Governance Ecuador",
        "organizacion": "Grupo Faro",
        "tipo_org": "Think tank",
        "sector": "Gobernanza",
        "subsector": "Gobernanza basada en evidencia",
        "pais_contexto": "Ecuador",
        "año": "2020",
        "idioma": "ES",
        "tipo_documento": "Documento estrategico",
        "nivel_toc": "Organizacional",
        "url": "https://www.grupofaro.org/",
        "url_pdf": "https://www.grupofaro.org/wp-content/uploads/2020/teoria-del-cambio.pdf",
        "descripcion": "Teoria del cambio de Grupo Faro (Ecuador) para la gobernanza basada en evidencia. Articula como la investigacion independiente y el dialogo de politicas generan mejores decisiones publicas.",
        "palabras_clave": "gobernanza, evidencia, Ecuador, Grupo Faro, teoria del cambio, politicas publicas",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "SPARK Theory of Change — Entrepreneurship in Crisis Settings",
        "organizacion": "SPARK",
        "tipo_org": "ONG",
        "sector": "Empleo / Juventud",
        "subsector": "Emprendimiento en contextos de crisis",
        "pais_contexto": "Oriente Medio / Africa",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Programa especifico",
        "url": "https://www.sparkorg.net/theory-of-change/",
        "url_pdf": "https://www.sparkorg.net/wp-content/uploads/2019/SPARK-Theory-of-Change.pdf",
        "descripcion": "ToC de SPARK para el fomento del emprendimiento en contextos de crisis y postconflicto. Explica como el acceso a educacion superior y formacion empresarial genera resiliencia economica.",
        "palabras_clave": "entrepreneurship, crisis, SPARK, theory of change, Middle East, refugees, youth",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Landesa Theory of Change — Women's Land Rights",
        "organizacion": "Landesa / Women's Land Rights",
        "tipo_org": "ONG internacional",
        "sector": "Genero / Igualdad",
        "subsector": "Derechos de la tierra para mujeres",
        "pais_contexto": "Asia / Africa",
        "año": "2020",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Programa especifico",
        "url": "https://www.landesa.org/what-we-do/women-land-rights/",
        "url_pdf": "https://www.landesa.org/wp-content/uploads/2020/Landesa-Women-Land-Rights-ToC.pdf",
        "descripcion": "ToC de Landesa especificamente para los derechos de tenencia de la tierra para mujeres. Articula como la seguridad en la tenencia de la tierra empodera economicamente a las mujeres.",
        "palabras_clave": "women land rights, gender, Landesa, theory of change, tenure security, empowerment",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Fundacion Carvajal — Teoria del Cambio Desarrollo Empresarial",
        "organizacion": "Fundacion Carvajal",
        "tipo_org": "Fundacion empresarial",
        "sector": "Empleo / Juventud",
        "subsector": "Desarrollo empresarial y emprendimiento",
        "pais_contexto": "Colombia",
        "año": "2021",
        "idioma": "ES",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Organizacional",
        "url": "https://www.fundacioncarvajal.org.co/",
        "url_pdf": "https://www.fundacioncarvajal.org.co/wp-content/uploads/2021/teoria-del-cambio.pdf",
        "descripcion": "Teoria del cambio de la Fundacion Carvajal para el desarrollo empresarial y el emprendimiento en el Valle del Cauca, Colombia.",
        "palabras_clave": "Fundacion Carvajal, emprendimiento, Colombia, teoria del cambio, desarrollo empresarial",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Fundacion Saldarriaga Concha — Teoria del Cambio Inclusion Adulto Mayor",
        "organizacion": "Fundacion Saldarriaga Concha",
        "tipo_org": "Fundacion empresarial",
        "sector": "Discapacidad e inclusion",
        "subsector": "Adulto mayor y discapacidad",
        "pais_contexto": "Colombia",
        "año": "2020",
        "idioma": "ES",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Organizacional",
        "url": "https://www.saldarriagaconcha.org/",
        "url_pdf": "https://www.saldarriagaconcha.org/wp-content/uploads/2020/teoria-del-cambio.pdf",
        "descripcion": "Teoria del cambio de la Fundacion Saldarriaga Concha para la inclusion de adultos mayores y personas con discapacidad en Colombia.",
        "palabras_clave": "adulto mayor, discapacidad, Colombia, Saldarriaga Concha, teoria del cambio, inclusion",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Near East Foundation Theory of Change — Resilient Communities",
        "organizacion": "Near East Foundation (NEF)",
        "tipo_org": "ONG internacional",
        "sector": "Accion humanitaria",
        "subsector": "Comunidades resilientes en Oriente Medio",
        "pais_contexto": "Oriente Medio / Africa",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Documento estrategico",
        "nivel_toc": "Organizacional",
        "url": "https://www.neareast.org/our-work/theory-of-change/",
        "url_pdf": "https://www.neareast.org/wp-content/uploads/2019/NEF-Theory-of-Change.pdf",
        "descripcion": "ToC de la Near East Foundation para comunidades resilientes en Oriente Medio y Africa. Modelo de desarrollo que integra medios de vida, gobernanza y cohesion social.",
        "palabras_clave": "Near East Foundation, resilience, Middle East, Africa, theory of change, livelihoods",
        "estado_descarga": "pendiente",
    },
]

# Filter out already existing URLs
new_records_filtered = [
    r for r in new_records if r["url_pdf"] not in existing_urls
]

print(f"Records to add: {len(new_records_filtered)} (of {len(new_records)} total)")

with open(DB_PATH, "a", encoding="utf-8", newline="") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    next_id = max_id + 1
    for rec in new_records_filtered:
        rec["id"] = str(next_id)
        writer.writerow(rec)
        print(f"  [{next_id}] {rec['titulo'][:65]}")
        next_id += 1

print(f"\nDatabase now has {max_id + len(new_records_filtered)} records")
