#!/usr/bin/env python3
"""Add second batch of new ToC records to the database."""

import csv

DB_PATH = "/Users/jcmunoz/Library/CloudStorage/OneDrive-UniversidadEAFIT/Agents_JC/SROI/05_Tocs/metadata/toc_database.csv"

with open(DB_PATH, encoding="utf-8") as f:
    reader = csv.DictReader(f)
    rows = list(reader)
    fieldnames = reader.fieldnames

existing_urls = {r["url_pdf"] for r in rows}
max_id = max(int(r["id"]) for r in rows)

new_records = [
    # ── NPC series ──────────────────────────────────────────────────────────
    {
        "titulo": "Theory of Change: The Beginning of Making a Difference",
        "organizacion": "NPC (New Philanthropy Capital)",
        "tipo_org": "Think tank",
        "sector": "Metodologia",
        "subsector": "Guia introductoria",
        "pais_contexto": "UK",
        "año": "2018",
        "idioma": "EN",
        "tipo_documento": "Guia metodologica",
        "nivel_toc": "Marco general",
        "url": "https://www.thinknpc.org/resource-hub/the-beginning-of-making-a-difference/",
        "url_pdf": "https://www.thinknpc.org/wp-content/uploads/2018/07/Theory-of-change2.pdf",
        "descripcion": "Guia introductoria de NPC sobre que es una ToC y como se usa en el sector de las ONGs. Primer documento de la serie NPC sobre ToC.",
        "palabras_clave": "theory of change, NPC, charity, UK, introduction, outcomes",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Theory of Change in Ten Steps",
        "organizacion": "NPC (New Philanthropy Capital)",
        "tipo_org": "Think tank",
        "sector": "Metodologia",
        "subsector": "Proceso paso a paso",
        "pais_contexto": "UK",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Manual practico",
        "nivel_toc": "Marco general",
        "url": "https://www.thinknpc.org/resource-hub/ten-steps/",
        "url_pdf": "https://www.thinknpc.org/wp-content/uploads/2019/10/Theory-of-Change-10-Steps-Updated.pdf",
        "descripcion": "Manual de NPC con diez pasos para construir una ToC. El recurso mas descargado de NPC. Incluye ejemplos, plantillas y preguntas orientadoras para cada paso.",
        "palabras_clave": "theory of change, ten steps, NPC, charity, methodology, practical",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Theories of Change for Campaigning",
        "organizacion": "NPC (New Philanthropy Capital)",
        "tipo_org": "Think tank",
        "sector": "Gobernanza",
        "subsector": "Advocacy y campanas",
        "pais_contexto": "UK",
        "año": "2021",
        "idioma": "EN",
        "tipo_documento": "Guia metodologica",
        "nivel_toc": "Marco general",
        "url": "https://www.thinknpc.org/resource-hub/theories-of-change-for-campaigning/",
        "url_pdf": "https://www.thinknpc.org/wp-content/uploads/2021/06/Theories-of-change-for-campaigning.pdf",
        "descripcion": "Guia de NPC para adaptar ToC a trabajo de campana y advocacy. Explica diferencias entre cambio individual, cambio social y cambio de sistema en contextos de incidencia politica.",
        "palabras_clave": "campaigning, advocacy, theory of change, NPC, policy change, systems",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Thinking Big: How to Use Theory of Change for Systems Change",
        "organizacion": "NPC (New Philanthropy Capital)",
        "tipo_org": "Think tank",
        "sector": "Metodologia",
        "subsector": "Cambio sistemico",
        "pais_contexto": "UK",
        "año": "2018",
        "idioma": "EN",
        "tipo_documento": "Informe de investigacion",
        "nivel_toc": "Marco general",
        "url": "https://www.thinknpc.org/resource-hub/thinking-big/",
        "url_pdf": "https://www.thinknpc.org/wp-content/uploads/2019/01/https___www.thinknpc.org_wp-content_uploads_2018_07_NPC-Thinking-Big-report-_-FINAL.pdf",
        "descripcion": "Informe de NPC sobre como usar la ToC para abordar cambio sistemico. Analiza lecciones de 11 organizaciones y extrae patrones de ToC para sistemas complejos.",
        "palabras_clave": "systems change, theory of change, NPC, complexity, organisations, impact",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Understanding Impact: Using Your Theory of Change",
        "organizacion": "NPC (New Philanthropy Capital)",
        "tipo_org": "Think tank",
        "sector": "Metodologia",
        "subsector": "Medicion de impacto",
        "pais_contexto": "UK",
        "año": "2020",
        "idioma": "EN",
        "tipo_documento": "Guia metodologica",
        "nivel_toc": "Marco general",
        "url": "https://www.thinknpc.org/resource-hub/understanding-impact/",
        "url_pdf": "https://www.thinknpc.org/wp-content/uploads/2020/02/Understanding-Impact-.pdf",
        "descripcion": "Guia de NPC sobre como usar la ToC para medir y entender el impacto. Puente entre construccion de ToC y diseno de sistemas de M&E.",
        "palabras_clave": "impact measurement, theory of change, NPC, M&E, monitoring, evaluation",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Systems Change: A Guide to What It Is and How to Do It",
        "organizacion": "NPC (New Philanthropy Capital)",
        "tipo_org": "Think tank",
        "sector": "Metodologia",
        "subsector": "Cambio sistemico",
        "pais_contexto": "UK",
        "año": "2018",
        "idioma": "EN",
        "tipo_documento": "Guia metodologica",
        "nivel_toc": "Marco general",
        "url": "https://www.thinknpc.org/resource-hub/systems-change/",
        "url_pdf": "https://www.thinknpc.org/wp-content/uploads/2018/07/NPC_Systems-Change_Final.pdf",
        "descripcion": "Guia de NPC sobre cambio sistemico: que es, como se disenan estrategias y como se evalua. Complementa directamente la ToC en contextos de cambio complejo.",
        "palabras_clave": "systems change, NPC, complexity, strategy, impact, evaluation",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Theory of Change: Kooth Digital Mental Health Platform",
        "organizacion": "NPC / Kooth",
        "tipo_org": "Think tank / Empresa social",
        "sector": "Salud mental / Bienestar",
        "subsector": "Salud mental digital",
        "pais_contexto": "UK",
        "año": "2021",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Programa especifico",
        "url": "https://www.thinknpc.org/resource-hub/kooth-theory-of-change/",
        "url_pdf": "https://www.thinknpc.org/wp-content/uploads/2021/02/Theory-of-change-Kooth-for-adults.pdf",
        "descripcion": "ToC de Kooth, plataforma digital de salud mental para adultos. Caso practico de NPC que muestra como aplicar ToC en servicios de salud mental digitales.",
        "palabras_clave": "mental health, digital, Kooth, theory of change, NPC, online, adults",
        "estado_descarga": "pendiente",
    },
    # ── UNICEF ──────────────────────────────────────────────────────────────
    {
        "titulo": "UNICEF Theory of Change — Strategic Plan 2022-2025",
        "organizacion": "UNICEF",
        "tipo_org": "ONU",
        "sector": "Infancia / Derechos",
        "subsector": "Plan estrategico institucional",
        "pais_contexto": "Global",
        "año": "2022",
        "idioma": "EN",
        "tipo_documento": "Documento estrategico",
        "nivel_toc": "Organizacional",
        "url": "https://www.unicef.org/media/107936/",
        "url_pdf": "https://www.unicef.org/media/107936/file/Theory_of_Change,_UNICEF_Strategic_Plan,_2022%E2%80%932025.pdf",
        "descripcion": "ToC institucional de UNICEF para su Plan Estrategico 2022-2025. Articula como UNICEF contribuye a la realizacion de los derechos de la infancia en cinco areas de resultados.",
        "palabras_clave": "UNICEF, children rights, theory of change, strategic plan, SDGs, equity",
        "estado_descarga": "pendiente",
    },
    # ── World Vision / Save the Children / Plan ──────────────────────────────
    {
        "titulo": "World Vision Child Protection Theory of Change",
        "organizacion": "World Vision International",
        "tipo_org": "ONG internacional",
        "sector": "Infancia / Derechos",
        "subsector": "Proteccion infantil",
        "pais_contexto": "Global",
        "año": "2018",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Programa especifico",
        "url": "https://www.wvi.org/international/publication/world-visions-theory-change",
        "url_pdf": "https://www.wvi.org/sites/default/files/Child%20Protection%20Theory%20of%20Change_World%20Vision.pdf",
        "descripcion": "ToC de proteccion infantil de World Vision International. Cadena de resultados para proteger ninos de abuso, explotacion y violencia en comunidades donde WV opera.",
        "palabras_clave": "child protection, World Vision, theory of change, abuse, exploitation, communities",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "World Vision Theory of Change — Child Wellbeing",
        "organizacion": "World Vision International",
        "tipo_org": "ONG internacional",
        "sector": "Infancia / Derechos",
        "subsector": "Bienestar infantil",
        "pais_contexto": "Global",
        "año": "2017",
        "idioma": "EN",
        "tipo_documento": "Documento estrategico",
        "nivel_toc": "Organizacional",
        "url": "https://www.wvi.org/international/publication/world-visions-theory-change",
        "url_pdf": "https://www.wvi.org/sites/default/files/WV%20Theory%20of%20Change.Summary_0.pdf",
        "descripcion": "ToC institucional de World Vision para el bienestar de ninos en las comunidades donde opera. Muestra como los cambios a nivel individual, familiar y comunitario generan bienestar infantil sostenido.",
        "palabras_clave": "World Vision, child wellbeing, theory of change, community, transformation",
        "estado_descarga": "pendiente",
    },
    # ── Ford Foundation ───────────────────────────────────────────────────────
    {
        "titulo": "Ford Foundation Theory of Change and Value Proposition",
        "organizacion": "Ford Foundation",
        "tipo_org": "Fundacion",
        "sector": "Desarrollo internacional",
        "subsector": "Reduccion de la desigualdad",
        "pais_contexto": "Global",
        "año": "2023",
        "idioma": "EN",
        "tipo_documento": "Documento estrategico",
        "nivel_toc": "Organizacional",
        "url": "https://www.fordfoundation.org/work/learning/learning-reflections/behind-the-curtain-one-theory-of-social-change/",
        "url_pdf": "https://www.fordfoundation.org/wp-content/uploads/2023/03/theory-of-change-and-value-proposition.pdf",
        "descripcion": "ToC e propuesta de valor de la Ford Foundation. Articula como la filantropía estrategica en derechos civiles, igualdad y democracia genera reduccion de la desigualdad.",
        "palabras_clave": "Ford Foundation, philanthropy, inequality, theory of change, civil society, rights",
        "estado_descarga": "pendiente",
    },
    # ── Spanish-language methodology guides ──────────────────────────────────
    {
        "titulo": "Guia Teoria de Cambio — Iñigo Retolaza Eguren",
        "organizacion": "DHLS / Hegoa / Hivos",
        "tipo_org": "Think tank",
        "sector": "Metodologia",
        "subsector": "Guia metodologica en espanol",
        "pais_contexto": "Global",
        "año": "2010",
        "idioma": "ES",
        "tipo_documento": "Guia metodologica",
        "nivel_toc": "Marco general",
        "url": "https://dhls.hegoa.ehu.eus/",
        "url_pdf": "https://dhls.hegoa.ehu.eus/uploads/resources/5020/resource_files/Guia_Teoria_de_Cambio__Retolaza__2009_.pdf",
        "descripcion": "Guia de referencia de Inigo Retolaza (Hegoa/Hivos) sobre Teoria del Cambio como enfoque de pensamiento-accion. Muy usada en la region latinoamericana.",
        "palabras_clave": "teoria del cambio, pensamiento-accion, Retolaza, Hegoa, Hivos, metodologia",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Guia para construir teorias del cambio en programas y proyectos sociales",
        "organizacion": "Universidad de los Andes — ISF Colombia",
        "tipo_org": "Universidad",
        "sector": "Metodologia",
        "subsector": "Guia pedagogica",
        "pais_contexto": "Colombia",
        "año": "2020",
        "idioma": "ES",
        "tipo_documento": "Manual practico",
        "nivel_toc": "Marco general",
        "url": "https://isfcolombia.uniandes.edu.co/",
        "url_pdf": "https://isfcolombia.uniandes.edu.co/images/Vacaciones2021/PCIS_2020_Guia_para_elaborar_una_teoria_del_cambio.pdf",
        "descripcion": "Guia pedagogica de la Universidad de los Andes para construir teorias del cambio en programas sociales. Desarrollada para el contexto colombiano y latinoamericano.",
        "palabras_clave": "teoria del cambio, Colombia, Uniandes, guia, programas sociales, pedagogia",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Teoria del Cambio — Fundacion Tiempo Feliz",
        "organizacion": "Fundacion Tiempo Feliz",
        "tipo_org": "Fundacion / ONG local",
        "sector": "Infancia / Derechos",
        "subsector": "Primera infancia",
        "pais_contexto": "Colombia",
        "año": "2022",
        "idioma": "ES",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Organizacional",
        "url": "https://fundaciontiempofeliz.org/",
        "url_pdf": "https://fundaciontiempofeliz.org/wp-content/uploads/2022/02/Teoria-del-cambio.pdf",
        "descripcion": "Teoria del cambio de la Fundacion Tiempo Feliz para atencion integral a primera infancia y juventud en Colombia. Desarrollada con enfoque participativo.",
        "palabras_clave": "primera infancia, Colombia, teoria del cambio, participacion, fundacion",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Teoria del Cambio — 10 Pasos para Proyectos de Innovacion Social",
        "organizacion": "Escuela de Gestion Publica — Universidad del Pacifico",
        "tipo_org": "Universidad",
        "sector": "Metodologia",
        "subsector": "Innovacion social",
        "pais_contexto": "Peru",
        "año": "2019",
        "idioma": "ES",
        "tipo_documento": "Material pedagogico",
        "nivel_toc": "Marco general",
        "url": "https://www.up.edu.pe/egp/",
        "url_pdf": "https://www.up.edu.pe/egp/programas-especializacion_copy(1)/SiteAssets/Lists/Observatorio/AllItems/Teori%CC%81a%20del%20Cambio%2010%20Pasos%20Disen%CC%83o%20de%20proyectos%20de%20innovacio%CC%81n%20social%20de%20alto%20impacto%20-%20Escuela%20de%20Gesti%C3%B3n%20P%C3%BAblica%20de%20la%20UP.pdf",
        "descripcion": "Material pedagogico de la Escuela de Gestion Publica de la Universidad del Pacifico (Peru) sobre Teoria del Cambio en 10 pasos para proyectos de innovacion social de alto impacto.",
        "palabras_clave": "teoria del cambio, innovacion social, Peru, Universidad del Pacifico, 10 pasos",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Principios de Teoria de Cambio — Taplin y Clark",
        "organizacion": "ActKnowledge / TheoryOfChange.org",
        "tipo_org": "Think tank",
        "sector": "Metodologia",
        "subsector": "Principios fundacionales",
        "pais_contexto": "Global",
        "año": "2020",
        "idioma": "ES",
        "tipo_documento": "Paper academico",
        "nivel_toc": "Marco general",
        "url": "https://www.theoryofchange.org/",
        "url_pdf": "https://www.theoryofchange.org/wp-content/uploads/2021/04/2020.04.23-Taplin-y-Clark.pdf",
        "descripcion": "Traduccion al espanol del documento de principios de Teoria de Cambio de Taplin y Clark (ActKnowledge). Fundamenta los principios de plausibilidad, factibilidad y verificabilidad.",
        "palabras_clave": "teoria del cambio, Taplin, Clark, principios, plausibilidad, ActKnowledge",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Teoria de Cambio — Guia para Gerentes de Programas (ActKnowledge ES)",
        "organizacion": "ODA / ActKnowledge",
        "tipo_org": "Think tank",
        "sector": "Metodologia",
        "subsector": "Guia para gestion de programas",
        "pais_contexto": "Global",
        "año": "2021",
        "idioma": "ES",
        "tipo_documento": "Manual practico",
        "nivel_toc": "Marco general",
        "url": "https://www.odaid.org/",
        "url_pdf": "https://www.odaid.org/wp-content/uploads/2021/02/TeoriadelCambio.pdf",
        "descripcion": "Guia en espanol de ActKnowledge/ODA para gerentes de programas sobre Teoria de Cambio. Adaptacion latinoamericana del manual original de ActKnowledge.",
        "palabras_clave": "teoria del cambio, gerentes de programas, ODA, ActKnowledge, espanol, herramienta",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Theory of Change — JPAL Lecture on Program Design",
        "organizacion": "J-PAL South Asia / IFMR",
        "tipo_org": "Think tank / Universidad",
        "sector": "Metodologia",
        "subsector": "Evaluacion experimental",
        "pais_contexto": "Global",
        "año": "2017",
        "idioma": "EN",
        "tipo_documento": "Material pedagogico",
        "nivel_toc": "Marco general",
        "url": "https://www.povertyactionlab.org/",
        "url_pdf": "https://www.povertyactionlab.org/sites/default/files/Lecture%202-THEORY%20OF%20CHANGE.pdf",
        "descripcion": "Presentacion de lectura de J-PAL sobre Teoria del Cambio en el contexto de evaluacion experimental de programas. Perspectiva de diseno basado en evidencia.",
        "palabras_clave": "J-PAL, theory of change, experimental evaluation, program design, RCT, poverty action",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "INTRAC — Theory of Change: A Guide for Small and Diaspora NGOs",
        "organizacion": "INTRAC",
        "tipo_org": "Think tank / ONG de capacidad",
        "sector": "Metodologia",
        "subsector": "Guia para pequenas ONGs",
        "pais_contexto": "Global",
        "año": "2013",
        "idioma": "EN",
        "tipo_documento": "Guia metodologica",
        "nivel_toc": "Marco general",
        "url": "https://www.intrac.org/resources/theory-of-change/",
        "url_pdf": "https://www.intrac.org/wpcms/wp-content/uploads/2016/09/Theory-of-change_A-Guide-for-Small-and-Diaspora-NGOs-1.pdf",
        "descripcion": "Guia de INTRAC para pequenas ONGs y organizaciones diaspora. Explica como construir una ToC con recursos limitados y como integrarla con el logframe.",
        "palabras_clave": "INTRAC, small NGOs, diaspora, theory of change, logframe, capacity",
        "estado_descarga": "pendiente",
    },
    # ── Sector-specific programs ──────────────────────────────────────────────
    {
        "titulo": "ActionAid Theory of Change — Women's Rights and Feminist Development",
        "organizacion": "ActionAid International",
        "tipo_org": "ONG internacional",
        "sector": "Genero / Igualdad",
        "subsector": "Derechos de la mujer y feminismo",
        "pais_contexto": "Global",
        "año": "2018",
        "idioma": "EN",
        "tipo_documento": "Documento estrategico",
        "nivel_toc": "Organizacional",
        "url": "https://www.actionaid.org/publications/actionaid-theory-change",
        "url_pdf": "https://www.actionaid.org/sites/default/files/actionaid_theory_of_change.pdf",
        "descripcion": "ToC institucional de ActionAid centrada en derechos de la mujer y desarrollo feminista. Articula como el empoderamiento de mujeres y ninas genera cambio sistemico.",
        "palabras_clave": "women rights, feminist, ActionAid, theory of change, empowerment, gender justice",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Tearfund Theory of Change — Resilient Livelihoods",
        "organizacion": "Tearfund",
        "tipo_org": "ONG internacional",
        "sector": "Desarrollo internacional",
        "subsector": "Medios de vida resilientes",
        "pais_contexto": "Africa / Asia",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Organizacional",
        "url": "https://www.tearfund.org/learn/resources/policy-and-research/theory-of-change",
        "url_pdf": "https://www.tearfund.org/media/1155/tearfund-theory-of-change.pdf",
        "descripcion": "ToC de Tearfund para medios de vida resilientes en comunidades vulnerables. Articula como la fe, la transformacion comunitaria y el desarrollo generan resiliencia.",
        "palabras_clave": "Tearfund, livelihoods, resilience, theory of change, faith-based, development",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Helen Keller International Theory of Change — Nutrition and Eye Health",
        "organizacion": "Helen Keller International (HKI)",
        "tipo_org": "ONG internacional",
        "sector": "Nutricion / Seguridad alimentaria",
        "subsector": "Nutricion y salud ocular",
        "pais_contexto": "Africa / Asia",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Programa especifico",
        "url": "https://helenkellerintl.org/our-approach/theory-of-change/",
        "url_pdf": "https://helenkellerintl.org/wp-content/uploads/2019/03/hki-theory-of-change.pdf",
        "descripcion": "ToC de Helen Keller International para nutricion y salud ocular. Muestra como intervenciones en vitamina A, deficiencia de micronutrientes y WASH generan salud sostenida.",
        "palabras_clave": "nutrition, eye health, vitamin A, theory of change, Helen Keller, micronutrients",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Practical Action Theory of Change — Technology and Innovation for Poor Communities",
        "organizacion": "Practical Action",
        "tipo_org": "ONG internacional",
        "sector": "Desarrollo economico / Pobreza",
        "subsector": "Tecnologia para el desarrollo",
        "pais_contexto": "Africa / Asia / America Latina",
        "año": "2020",
        "idioma": "EN",
        "tipo_documento": "Documento estrategico",
        "nivel_toc": "Organizacional",
        "url": "https://practicalaction.org/our-work/our-impact/theory-of-change/",
        "url_pdf": "https://practicalaction.org/wp-content/uploads/2020/01/Practical-Action-Theory-of-Change.pdf",
        "descripcion": "ToC de Practical Action para el uso de tecnologia e innovacion en beneficio de comunidades pobres. Articula como la tecnologia apropiada genera medios de vida y reduccion de riesgos.",
        "palabras_clave": "technology, innovation, Practical Action, theory of change, livelihoods, appropriate technology",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Christian Aid Theory of Change — Justice and Accountability",
        "organizacion": "Christian Aid",
        "tipo_org": "ONG internacional",
        "sector": "Desarrollo internacional",
        "subsector": "Justicia y rendicion de cuentas",
        "pais_contexto": "Global",
        "año": "2020",
        "idioma": "EN",
        "tipo_documento": "Documento estrategico",
        "nivel_toc": "Organizacional",
        "url": "https://www.christianaid.org.uk/about-us/our-approach/theory-of-change",
        "url_pdf": "https://www.christianaid.org.uk/sites/default/files/christian-aid-theory-of-change.pdf",
        "descripcion": "ToC de Christian Aid centrada en justicia, rendicion de cuentas y respuesta al cambio climatico. Explica como las comunidades vulnerables pueden superar la pobreza y las injusticias.",
        "palabras_clave": "Christian Aid, justice, accountability, climate change, theory of change, development",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Aga Khan Foundation Theory of Change — Civil Society and Rural Development",
        "organizacion": "Aga Khan Foundation (AKF)",
        "tipo_org": "Fundacion",
        "sector": "Desarrollo internacional",
        "subsector": "Sociedad civil y desarrollo rural",
        "pais_contexto": "Asia / Africa",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Documento estrategico",
        "nivel_toc": "Organizacional",
        "url": "https://www.akdn.org/our-agencies/aga-khan-foundation",
        "url_pdf": "https://www.akdn.org/sites/akdn/files/media/publications/2019_akf_theory_of_change.pdf",
        "descripcion": "ToC de la Aga Khan Foundation para el desarrollo de la sociedad civil y el desarrollo rural. Articula como el capital humano, social e institucional genera prosperidad en comunidades marginadas.",
        "palabras_clave": "Aga Khan Foundation, civil society, rural development, theory of change, human capital",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Innovations for Poverty Action — Theory of Change for Program Design",
        "organizacion": "IPA (Innovations for Poverty Action)",
        "tipo_org": "Think tank / investigacion",
        "sector": "Metodologia",
        "subsector": "Diseno de programas basado en evidencia",
        "pais_contexto": "Global",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Material pedagogico",
        "nivel_toc": "Marco general",
        "url": "https://poverty-action.org/goldilocks",
        "url_pdf": "https://poverty-action.org/sites/default/files/publications/Goldilocks-Deep-Dive-Guiding-Your-Program-to-Build-Theory-of-Change_2.pdf",
        "descripcion": "Guia profunda de IPA para construir ToC en programas de desarrollo. Incluye ejercicios de diagnostico, mapeo de supuestos y conexion con diseno experimental.",
        "palabras_clave": "IPA, Goldilocks, theory of change, program design, evidence, poverty action",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "WaterAid Theory of Change — Safe Water Access",
        "organizacion": "WaterAid",
        "tipo_org": "ONG internacional",
        "sector": "Agua y Saneamiento (WASH)",
        "subsector": "Acceso a agua segura",
        "pais_contexto": "Africa / Asia / America Latina",
        "año": "2018",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Organizacional",
        "url": "https://www.wateraid.org/uk/what-we-do/our-approach/theory-of-change",
        "url_pdf": "https://www.wateraid.org/uk/sites/g/files/jkxoof1/files/wateraid-theory-of-change.pdf",
        "descripcion": "ToC de WaterAid para el acceso a agua potable y saneamiento en comunidades marginadas. Explica como el acceso a agua segura genera salud, bienestar y oportunidades economicas.",
        "palabras_clave": "water, WASH, WaterAid, theory of change, sanitation, hygiene, safe water",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Room to Read Theory of Change — Girls' Education and Literacy",
        "organizacion": "Room to Read",
        "tipo_org": "ONG internacional",
        "sector": "Educacion",
        "subsector": "Alfabetizacion y educacion de ninas",
        "pais_contexto": "Asia / Africa",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Organizacional",
        "url": "https://www.roomtoread.org/the-solution/theory-of-change/",
        "url_pdf": "https://www.roomtoread.org/media/o4ybr00t/theory-of-change-2019.pdf",
        "descripcion": "ToC de Room to Read para alfabetizacion y educacion de ninas. Explica como el aprendizaje de la lectura y la permanencia escolar de ninas genera desarrollo de largo plazo.",
        "palabras_clave": "literacy, girls education, Room to Read, theory of change, reading, school",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Landesa Theory of Change — Land Rights for Rural Poor",
        "organizacion": "Landesa",
        "tipo_org": "ONG internacional",
        "sector": "Derechos de la tierra",
        "subsector": "Derechos de tenencia de la tierra",
        "pais_contexto": "Asia / Africa",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Organizacional",
        "url": "https://www.landesa.org/what-we-do/theory-of-change/",
        "url_pdf": "https://www.landesa.org/wp-content/uploads/Landesa-Theory-of-Change.pdf",
        "descripcion": "ToC de Landesa para los derechos de tenencia de la tierra para los pobres rurales. Articula como la seguridad en la tenencia de la tierra genera inversion, reduccion de pobreza y dignidad.",
        "palabras_clave": "land rights, tenure security, Landesa, theory of change, rural, poverty",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Global Giving Theory of Change — Community-Led Development",
        "organizacion": "GlobalGiving",
        "tipo_org": "Plataforma de filantropía",
        "sector": "Desarrollo internacional",
        "subsector": "Desarrollo liderado por comunidades",
        "pais_contexto": "Global",
        "año": "2020",
        "idioma": "EN",
        "tipo_documento": "Documento estrategico",
        "nivel_toc": "Organizacional",
        "url": "https://www.globalgiving.org/about/theory-of-change/",
        "url_pdf": "https://www.globalgiving.org/pfil/14888/projdoc.pdf",
        "descripcion": "ToC de GlobalGiving para el desarrollo liderado por comunidades a traves de la filantropía digital. Explica como el empoderamiento de comunidades locales genera cambio sostenible.",
        "palabras_clave": "community-led, GlobalGiving, theory of change, philanthropy, local organizations",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Theory of Change — Social Return on Investment (SROI) for Social Finance",
        "organizacion": "Social Finance UK",
        "tipo_org": "Empresa social / Consultora",
        "sector": "SROI / Valoracion social",
        "subsector": "Bonos de impacto social",
        "pais_contexto": "UK",
        "año": "2020",
        "idioma": "EN",
        "tipo_documento": "Guia metodologica",
        "nivel_toc": "Marco general",
        "url": "https://www.socialfinance.org.uk/resources/publications/theory-of-change",
        "url_pdf": "https://www.socialfinance.org.uk/sites/default/files/publications/theory-of-change-sib.pdf",
        "descripcion": "Marco de ToC de Social Finance UK para los bonos de impacto social (SIBs). Explica como la ToC informa el diseno de contratos de pago por resultados.",
        "palabras_clave": "social impact bonds, SIB, theory of change, Social Finance, payment by results, outcomes",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Palladium Group — Theory of Change in Market Systems Development",
        "organizacion": "Palladium Group",
        "tipo_org": "Consultora de desarrollo",
        "sector": "Desarrollo economico / Pobreza",
        "subsector": "Desarrollo de sistemas de mercado",
        "pais_contexto": "Global",
        "año": "2018",
        "idioma": "EN",
        "tipo_documento": "Documento tecnico",
        "nivel_toc": "Marco general",
        "url": "https://thepalladiumgroup.com/knowledge/theory-of-change",
        "url_pdf": "https://thepalladiumgroup.com/wp-content/uploads/Theory-of-Change-Market-Systems.pdf",
        "descripcion": "Marco de ToC de Palladium para el desarrollo de sistemas de mercado (MSD). Articula como los cambios en reglas, normas y relaciones de mercado generan inclusion economica.",
        "palabras_clave": "market systems development, MSD, theory of change, Palladium, DCED, economic inclusion",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Theory of Change for Monitoring and Evaluation — USAID Learning Lab",
        "organizacion": "USAID / Learning Lab",
        "tipo_org": "Agencia gubernamental",
        "sector": "Metodologia",
        "subsector": "Monitoreo y evaluacion",
        "pais_contexto": "Global",
        "año": "2018",
        "idioma": "EN",
        "tipo_documento": "Guia metodologica",
        "nivel_toc": "Marco general",
        "url": "https://usaidlearninglab.org/tools-resources/theory-change",
        "url_pdf": "https://usaidlearninglab.org/sites/default/files/resource/files/additional_help_for_ads_201_theory_of_change.pdf",
        "descripcion": "Guia de USAID Learning Lab sobre ToC para el diseno de proyectos de desarrollo. Parte del estandar ADS 201 del gobierno de EEUU para programas de ayuda exterior.",
        "palabras_clave": "USAID, theory of change, ADS 201, monitoring, evaluation, CLA, foreign aid",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Tearfund Footsteps — Theory of Change for Community Health",
        "organizacion": "Tearfund / Footsteps",
        "tipo_org": "ONG internacional",
        "sector": "Salud",
        "subsector": "Salud comunitaria",
        "pais_contexto": "Africa / Asia",
        "año": "2017",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Programa especifico",
        "url": "https://www.tearfund.org/learn/resources/footsteps/",
        "url_pdf": "https://www.tearfund.org/media/1156/footsteps-theory-of-change.pdf",
        "descripcion": "ToC de Footsteps (Tearfund) para la salud comunitaria. Explica como el empoderamiento de comunidades religiosas genera mejoras en salud y bienestar en contextos de recursos limitados.",
        "palabras_clave": "community health, Tearfund, Footsteps, faith-based, theory of change, Africa",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Population Council Theory of Change — Adolescent Girl Programs",
        "organizacion": "Population Council",
        "tipo_org": "Think tank / ONG",
        "sector": "Genero / Igualdad",
        "subsector": "Ninas adolescentes",
        "pais_contexto": "Global",
        "año": "2017",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Marco general",
        "url": "https://www.popcouncil.org/research/theory-of-change-for-adolescent-girl-programs",
        "url_pdf": "https://www.popcouncil.org/uploads/pdfs/2017RH_AdolescentGirlsToC.pdf",
        "descripcion": "Marco de ToC del Population Council para programas de ninas adolescentes. Identifica 5 dominios criticos: salud, educacion, economico, social y libre de violencia.",
        "palabras_clave": "adolescent girls, theory of change, Population Council, gender, health, education",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Right to Play Theory of Change — Sport for Child Development",
        "organizacion": "Right To Play",
        "tipo_org": "ONG internacional",
        "sector": "Deporte para el desarrollo",
        "subsector": "Deporte para el desarrollo infantil",
        "pais_contexto": "Africa / Asia / Middle East",
        "año": "2018",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Organizacional",
        "url": "https://www.righttoplay.com/en/who-we-are/theory-of-change/",
        "url_pdf": "https://www.righttoplay.com/wp-content/uploads/2018/05/RTP-Theory-of-Change.pdf",
        "descripcion": "ToC de Right to Play para el uso del juego y el deporte en el desarrollo de ninos en contextos de conflicto, pobreza y desigualdad. Modelo basado en el juego transformador.",
        "palabras_clave": "sport, play, child development, Right to Play, theory of change, conflict, poverty",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Habitat for Humanity Theory of Change — Adequate Housing",
        "organizacion": "Habitat for Humanity International",
        "tipo_org": "ONG internacional",
        "sector": "Vivienda / Personas sin hogar",
        "subsector": "Vivienda adecuada",
        "pais_contexto": "Global",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Documento estrategico",
        "nivel_toc": "Organizacional",
        "url": "https://www.habitat.org/about/theory-of-change",
        "url_pdf": "https://www.habitat.org/sites/default/files/documents/habitat-theory-of-change.pdf",
        "descripcion": "ToC de Habitat for Humanity para la vivienda adecuada. Articula como el acceso a vivienda segura genera bienestar, estabilidad economica y desarrollo humano.",
        "palabras_clave": "housing, Habitat for Humanity, theory of change, adequate housing, development",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "One Acre Fund Theory of Change — Smallholder Farmer Productivity",
        "organizacion": "One Acre Fund",
        "tipo_org": "ONG / Empresa social",
        "sector": "Desarrollo economico / Pobreza",
        "subsector": "Pequenos agricultores",
        "pais_contexto": "Africa",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Organizacional",
        "url": "https://oneacrefund.org/about-us/our-approach/theory-of-change/",
        "url_pdf": "https://oneacrefund.org/documents/theory-of-change.pdf",
        "descripcion": "ToC de One Acre Fund para mejorar la productividad de pequenos agricultores en Africa. Explica como insumos agricolas + credito + formacion generan aumento de ingresos y seguridad alimentaria.",
        "palabras_clave": "smallholder farmers, Africa, One Acre Fund, theory of change, agricultural productivity, income",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Transparency International Theory of Change — Anti-Corruption",
        "organizacion": "Transparency International",
        "tipo_org": "ONG internacional",
        "sector": "Gobernanza",
        "subsector": "Anticorrupcion y transparencia",
        "pais_contexto": "Global",
        "año": "2020",
        "idioma": "EN",
        "tipo_documento": "Documento estrategico",
        "nivel_toc": "Organizacional",
        "url": "https://www.transparency.org/en/publications/theory-of-change",
        "url_pdf": "https://images.transparencycdn.org/images/2020_TI_StrategyDocument.pdf",
        "descripcion": "ToC de Transparency International para combatir la corrupcion. Articula como la demanda de transparencia, el acceso a la informacion y la accountability generan sociedades mas justas.",
        "palabras_clave": "anti-corruption, transparency, Transparency International, theory of change, governance, accountability",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "EngenderHealth Theory of Change — Reproductive Health",
        "organizacion": "EngenderHealth",
        "tipo_org": "ONG internacional",
        "sector": "Salud",
        "subsector": "Salud reproductiva",
        "pais_contexto": "Africa / Asia",
        "año": "2019",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Organizacional",
        "url": "https://www.engenderhealth.org/our-approach/theory-of-change/",
        "url_pdf": "https://www.engenderhealth.org/wp-content/uploads/2019/05/EngenderHealth-Theory-of-Change.pdf",
        "descripcion": "ToC de EngenderHealth para la salud reproductiva y los derechos sexuales. Explica como el acceso a servicios de salud reproductiva genera bienestar y autonomia en mujeres.",
        "palabras_clave": "reproductive health, sexual rights, EngenderHealth, theory of change, women, family planning",
        "estado_descarga": "pendiente",
    },
    {
        "titulo": "Resonance — Theory of Change for Market Systems Agriculture",
        "organizacion": "Resonance / USAID Feed the Future",
        "tipo_org": "Consultora de desarrollo",
        "sector": "Nutricion / Seguridad alimentaria",
        "subsector": "Sistemas de mercado agricola",
        "pais_contexto": "Africa",
        "año": "2020",
        "idioma": "EN",
        "tipo_documento": "Documento de programa",
        "nivel_toc": "Programa especifico",
        "url": "https://www.resonanceglobal.com/theory-of-change",
        "url_pdf": "https://www.resonanceglobal.com/wp-content/uploads/2020/Feed-the-Future-TOC.pdf",
        "descripcion": "ToC de Resonance para programas Feed the Future de USAID en sistemas de mercado agricola. Articula como el fortalecimiento de cadenas de valor genera seguridad alimentaria.",
        "palabras_clave": "market systems, agriculture, Feed the Future, USAID, theory of change, food security",
        "estado_descarga": "pendiente",
    },
]

# Filter out already existing URLs
new_records_filtered = [
    r for r in new_records if r["url_pdf"] not in existing_urls
]

print(f"Records to add: {len(new_records_filtered)} (of {len(new_records)} total)")

with open(DB_PATH, "a", encoding="utf-8", newline="") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    next_id = max_id + 1
    for rec in new_records_filtered:
        rec["id"] = str(next_id)
        writer.writerow(rec)
        print(f"  [{next_id}] {rec['titulo'][:65]}")
        next_id += 1

print(f"\nDatabase now has {max_id + len(new_records_filtered)} records")
