"""
Batch 1 — Salud + Educación (~130 indicadores)
Crea o reemplaza el CSV base de indicadores.
"""
import csv, os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT  = os.path.join(BASE, "metadata", "indicadores.csv")

FIELDS = [
    "id", "nombre", "nombre_en", "descripcion",
    "tipo",           # producto | resultado | impacto
    "sector", "subsector",
    "nivel_medicion", # individual | hogar | comunidad | sistema
    "enfoque",        # cuantitativo | cualitativo | mixto
    "unidad",         # %, n, tasa, índice, puntaje, días, COP/USD
    "formula",
    "metodo_recoleccion",   # encuesta_autorreporte | registro_administrativo | observacion_directa | participativo | entrevista | grupo_focal | revision_documental | datos_secundarios
    "instrumento_sugerido",
    "frecuencia",           # mensual | trimestral | semestral | anual | unica_vez | por_evento
    "momento_medicion",     # linea_base | seguimiento | evaluacion_final | impacto | todos
    "tipo_linea_base",      # cuantitativa | cualitativa | mixta | no_aplica
    "diseno_comparacion",   # pre_post | grupo_control | historico | participativo | sin_comparacion
    "desagregacion_recomendada",
    "ods_meta",
    "fuente_referencia",
    "codigo_iris",
    "valor_referencia",
    "ejemplo_programa",
    "limitaciones",
    "idioma",
]

INDICATORS = [

# ─────────────────────────────────────────────────────────────────────────────
# SECTOR: SALUD
# ─────────────────────────────────────────────────────────────────────────────

# --- SALUD — PRODUCTOS ---
{"id":"S001","nombre":"Número de personas atendidas en consulta de salud",
 "nombre_en":"Number of people receiving health consultations",
 "descripcion":"Cuenta el total de personas que recibieron al menos una consulta médica o de salud en el período. Refleja el alcance directo de las actividades de atención primaria.",
 "tipo":"producto","sector":"Salud","subsector":"Atención primaria",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"n",
 "formula":"Σ atenciones médicas registradas en el período",
 "metodo_recoleccion":"registro_administrativo","instrumento_sugerido":"Sistema de información en salud (HIS) / planilla de registro",
 "frecuencia":"mensual","momento_medicion":"seguimiento","tipo_linea_base":"no_aplica",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"sexo, edad, zona (urbano/rural), tipo de afiliación, diagnóstico",
 "ods_meta":"ODS 3.8","fuente_referencia":"OPS/PAHO, MINSALUD Colombia","codigo_iris":"PI6743",
 "valor_referencia":"","ejemplo_programa":"Programa de salud comunitaria — Hogares Saludables Argos",
 "limitaciones":"No distingue entre primera vez y controles; puede haber subregistro en zonas rurales.",
 "idioma":"ES"},

{"id":"S002","nombre":"Número de jornadas de salud realizadas",
 "nombre_en":"Number of health outreach sessions conducted",
 "descripcion":"Total de jornadas, brigadas o ferias de salud llevadas a cabo en el período. Mide la intensidad de la oferta de servicios en territorio.",
 "tipo":"producto","sector":"Salud","subsector":"Promoción y prevención",
 "nivel_medicion":"comunidad","enfoque":"cuantitativo","unidad":"n",
 "formula":"Σ eventos de salud organizados en el período",
 "metodo_recoleccion":"registro_administrativo","instrumento_sugerido":"Bitácora de actividades / informe de campo",
 "frecuencia":"mensual","momento_medicion":"seguimiento","tipo_linea_base":"no_aplica",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"municipio, tipo de servicio ofrecido, número de asistentes",
 "ods_meta":"ODS 3.8","fuente_referencia":"Ministerio de Salud Colombia","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"Plan de Intervenciones Colectivas (PIC) — Secretarías de Salud",
 "limitaciones":"No indica calidad de la atención ni si las personas recibieron seguimiento posterior.",
 "idioma":"ES"},

{"id":"S003","nombre":"Número de profesionales de salud capacitados",
 "nombre_en":"Number of health workers trained",
 "descripcion":"Total de trabajadores de salud (médicos, enfermeras, agentes comunitarios) que completaron al menos una capacitación en el período. Proxy de fortalecimiento de capacidades del sistema.",
 "tipo":"producto","sector":"Salud","subsector":"Fortalecimiento del sistema",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"n",
 "formula":"Σ trabajadores de salud que completaron ≥1 módulo de capacitación",
 "metodo_recoleccion":"registro_administrativo","instrumento_sugerido":"Lista de asistencia + certificado de participación",
 "frecuencia":"semestral","momento_medicion":"seguimiento","tipo_linea_base":"no_aplica",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"tipo de profesional, institución, tema de capacitación",
 "ods_meta":"ODS 3.c","fuente_referencia":"OMS, OPS","codigo_iris":"PI2354",
 "valor_referencia":"","ejemplo_programa":"Fortalecimiento ATAJOS Colombia — BID",
 "limitaciones":"Capacitación no garantiza cambio de práctica; requiere complemento con observación de desempeño.",
 "idioma":"ES"},

{"id":"S004","nombre":"Número de kits de salud o insumos médicos distribuidos",
 "nombre_en":"Number of health kits / medical supplies distributed",
 "descripcion":"Cantidad de kits de salud, medicamentos o insumos médicos entregados en el período. Mide la provisión directa de recursos materiales.",
 "tipo":"producto","sector":"Salud","subsector":"Atención primaria",
 "nivel_medicion":"hogar","enfoque":"cuantitativo","unidad":"n",
 "formula":"Σ kits/insumos entregados",
 "metodo_recoleccion":"registro_administrativo","instrumento_sugerido":"Planilla de entrega con firma del receptor",
 "frecuencia":"por_evento","momento_medicion":"seguimiento","tipo_linea_base":"no_aplica",
 "diseno_comparacion":"sin_comparacion",
 "desagregacion_recomendada":"tipo de kit, municipio, sexo del receptor",
 "ods_meta":"ODS 3.8","fuente_referencia":"UNICEF, Cruz Roja","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"Respuesta humanitaria — CICR",
 "limitaciones":"No informa sobre uso o impacto real del kit; posible desperdicio o duplicidad.",
 "idioma":"ES"},

{"id":"S005","nombre":"Número de visitas domiciliarias de salud realizadas",
 "nombre_en":"Number of household health visits conducted",
 "descripcion":"Total de visitas al hogar realizadas por agentes de salud comunitaria para seguimiento, prevención o referenciación. Clave en programas de salud preventiva basados en comunidad.",
 "tipo":"producto","sector":"Salud","subsector":"Salud comunitaria",
 "nivel_medicion":"hogar","enfoque":"cuantitativo","unidad":"n",
 "formula":"Σ visitas domiciliarias registradas",
 "metodo_recoleccion":"registro_administrativo","instrumento_sugerido":"Ficha de visita domiciliaria",
 "frecuencia":"mensual","momento_medicion":"seguimiento","tipo_linea_base":"no_aplica",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"tipo de visita (primera vez / seguimiento), diagnóstico del hogar, zona",
 "ods_meta":"ODS 3.8","fuente_referencia":"OPS, Ministerio de Salud Colombia","codigo_iris":"PI6743",
 "valor_referencia":"","ejemplo_programa":"Estrategia APS Colombia — Agentes Comunitarios de Salud",
 "limitaciones":"Calidad de la visita depende de capacitación del agente; riesgo de subregistro.",
 "idioma":"ES"},

{"id":"S006","nombre":"Porcentaje de niños con esquema de vacunación completo según edad",
 "nombre_en":"Percentage of children with age-appropriate complete vaccination",
 "descripcion":"Proporción de niños en el grupo de edad objetivo que tienen todas las vacunas del Programa Ampliado de Inmunizaciones (PAI) al día. Indicador clave de cobertura en salud infantil.",
 "tipo":"resultado","sector":"Salud","subsector":"Salud infantil",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Niños con vacunación completa / Total niños en grupo de edad) × 100",
 "metodo_recoleccion":"registro_administrativo","instrumento_sugerido":"Carné de vacunación + registros PAIWEB / SISVAC",
 "frecuencia":"anual","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"grupo de edad (0–11m, 12–23m, 24–59m), municipio, zona, tipo de vacuna",
 "ods_meta":"ODS 3.2","fuente_referencia":"OMS, OPS, MSPS Colombia","codigo_iris":"OD3949",
 "valor_referencia":"Meta nacional Colombia ≥95% esquema completo","ejemplo_programa":"PAI Colombia, EPI-UNICEF",
 "limitaciones":"El registro del carné puede no reflejar vacunación real; diferencias entre área urbana y rural.",
 "idioma":"ES"},

{"id":"S007","nombre":"Porcentaje de gestantes con controles prenatales completos",
 "nombre_en":"Percentage of pregnant women with adequate prenatal care",
 "descripcion":"Proporción de mujeres gestantes que asistieron al número mínimo de controles prenatales recomendados (≥4 en OMS, ≥8 en revisión 2016). Indicador de acceso a salud materna.",
 "tipo":"resultado","sector":"Salud","subsector":"Salud materna",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Gestantes con ≥4 controles prenatales / Total gestantes en el período) × 100",
 "metodo_recoleccion":"registro_administrativo","instrumento_sugerido":"Historia clínica perinatal / carné materno / RUAF",
 "frecuencia":"semestral","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"edad de la gestante, zona, tipo de afiliación, municipio",
 "ods_meta":"ODS 3.1","fuente_referencia":"OMS, OPS, MSPS Colombia","codigo_iris":"OD5132",
 "valor_referencia":"Meta OMS: ≥80% con ≥4 controles; Colombia: 80–85%",
 "ejemplo_programa":"Programa de salud materna — Secretarías de Salud Departamentales",
 "limitaciones":"Cantidad de controles no garantiza calidad; sesgo de cobertura en zonas rurales dispersas.",
 "idioma":"ES"},

{"id":"S008","nombre":"Porcentaje de personas con hipertensión en control adecuado",
 "nombre_en":"Percentage of hypertensive patients with controlled blood pressure",
 "descripcion":"Proporción de pacientes diagnosticados con hipertensión arterial que mantienen presión arterial dentro de rangos controlados (PAS<140, PAD<90 mmHg en última consulta). Indicador de adherencia y efectividad.",
 "tipo":"resultado","sector":"Salud","subsector":"Enfermedades crónicas no transmisibles",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"%",
 "formula":"(HTA con PA controlada / Total pacientes HTA registrados) × 100",
 "metodo_recoleccion":"registro_administrativo","instrumento_sugerido":"Historia clínica / registros del programa de crónicos",
 "frecuencia":"semestral","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"sexo, grupo etario, zona, tipo de afiliación",
 "ods_meta":"ODS 3.4","fuente_referencia":"OPS HEARTS, MINSALUD Colombia","codigo_iris":"OD5140",
 "valor_referencia":"Meta OPS HEARTS: ≥50% de pacientes HTA controlados",
 "ejemplo_programa":"Programa HEARTS Colombia — OPS/MINSALUD",
 "limitaciones":"Requiere datos clínicos; un solo registro puede no reflejar control sostenido.",
 "idioma":"ES"},

{"id":"S009","nombre":"Tasa de mortalidad materna (por 100.000 nacidos vivos)",
 "nombre_en":"Maternal mortality ratio (per 100,000 live births)",
 "descripcion":"Número de muertes maternas (durante el embarazo, parto o puerperio hasta 42 días) por cada 100.000 nacidos vivos. Indicador de impacto sobre la salud de la mujer y la calidad del sistema de salud.",
 "tipo":"impacto","sector":"Salud","subsector":"Salud materna",
 "nivel_medicion":"sistema","enfoque":"cuantitativo","unidad":"tasa",
 "formula":"(Muertes maternas / Nacidos vivos) × 100.000",
 "metodo_recoleccion":"datos_secundarios","instrumento_sugerido":"DANE / RUAF / Estadísticas Vitales",
 "frecuencia":"anual","momento_medicion":"impacto","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"municipio, departamento, causa de muerte, edad materna",
 "ods_meta":"ODS 3.1","fuente_referencia":"OMS, DANE, MSPS Colombia","codigo_iris":"OD5134",
 "valor_referencia":"Meta ODS: <70 por 100.000 NV; Colombia 2022: ~53",
 "ejemplo_programa":"Evaluación de impacto de programas de salud materna — Banco Mundial",
 "limitaciones":"Subregistro importante en zonas rurales y remotas; requiere sistemas robustos de estadísticas vitales.",
 "idioma":"ES"},

{"id":"S010","nombre":"Tasa de mortalidad infantil (por 1.000 nacidos vivos)",
 "nombre_en":"Infant mortality rate (per 1,000 live births)",
 "descripcion":"Número de defunciones de menores de 1 año por cada 1.000 nacidos vivos en el mismo período. Indicador de impacto sobre salud infantil y desarrollo del sistema de salud.",
 "tipo":"impacto","sector":"Salud","subsector":"Salud infantil",
 "nivel_medicion":"sistema","enfoque":"cuantitativo","unidad":"tasa",
 "formula":"(Muertes <1 año / Nacidos vivos) × 1.000",
 "metodo_recoleccion":"datos_secundarios","instrumento_sugerido":"DANE / RUAF",
 "frecuencia":"anual","momento_medicion":"impacto","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"sexo, municipio, causa de muerte, etnia",
 "ods_meta":"ODS 3.2","fuente_referencia":"OMS, UNICEF, DANE","codigo_iris":"OD3944",
 "valor_referencia":"Meta ODS: ≤12 por 1.000 NV; Colombia 2022: ~12–13",
 "ejemplo_programa":"Evaluaciones de impacto APS – OPS/PAHO",
 "limitaciones":"Sensible a calidad del registro de nacimientos y defunciones; rezago de publicación DANE ~2 años.",
 "idioma":"ES"},

{"id":"S011","nombre":"Prevalencia de desnutrición crónica en menores de 5 años (%)",
 "nombre_en":"Prevalence of chronic malnutrition (stunting) in children under 5",
 "descripcion":"Proporción de niños menores de 5 años con talla baja para la edad (< -2 DE de la mediana OMS). Mide el impacto acumulativo de la inseguridad alimentaria y deficiencias en salud y cuidado.",
 "tipo":"impacto","sector":"Salud","subsector":"Nutrición",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Niños <5 años con talla/edad < -2 DE / Total niños <5 años medidos) × 100",
 "metodo_recoleccion":"observacion_directa","instrumento_sugerido":"Tallímetro + tablas de crecimiento OMS + SISVAN",
 "frecuencia":"anual","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"sexo, edad en meses, zona, etnia, quintil de riqueza",
 "ods_meta":"ODS 2.2","fuente_referencia":"OMS, ENSIN Colombia, UNICEF","codigo_iris":"OD3945",
 "valor_referencia":"Colombia 2015: 10.8%; Meta ODS 2030: <5%",
 "ejemplo_programa":"Estrategia de Atención Integral a la Primera Infancia — De Cero a Siempre",
 "limitaciones":"Requiere medición antropométrica estandarizada; la encuesta nacional (ENSIN) es cada 5–7 años.",
 "idioma":"ES"},

{"id":"S012","nombre":"Porcentaje de personas que reportan conocimiento sobre signos de alarma de su condición",
 "nombre_en":"Percentage of people reporting knowledge of warning signs",
 "descripcion":"Proporción de personas con una condición crónica o en riesgo que pueden identificar correctamente los signos de alarma. Indicador de resultado en programas de educación en salud.",
 "tipo":"resultado","sector":"Salud","subsector":"Educación en salud",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Personas que identifican ≥3 signos de alarma correctamente / Total encuestados) × 100",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"Encuesta de conocimientos (prueba pre-post)",
 "frecuencia":"semestral","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"sexo, condición (HTA, diabetes, embarazo), zona",
 "ods_meta":"ODS 3.4","fuente_referencia":"OMS, MINSALUD Colombia","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"Programa de salud comunitaria — Hogares Saludables",
 "limitaciones":"El conocimiento declarado puede no traducirse en comportamiento; riesgo de sesgo de deseabilidad social.",
 "idioma":"ES"},

{"id":"S013","nombre":"Porcentaje de hogares con prácticas de higiene adecuadas (lavado de manos)",
 "nombre_en":"Percentage of households with adequate handwashing practices",
 "descripcion":"Proporción de hogares donde el observador o encuestado confirma que existe el hábito de lavado de manos con jabón en los 5 momentos críticos. Indicador de resultado en higiene y saneamiento.",
 "tipo":"resultado","sector":"Salud","subsector":"Agua, saneamiento e higiene (WASH)",
 "nivel_medicion":"hogar","enfoque":"mixto","unidad":"%",
 "formula":"(Hogares con práctica confirmada de lavado de manos con jabón / Total hogares observados) × 100",
 "metodo_recoleccion":"observacion_directa","instrumento_sugerido":"Ficha de observación del hogar (WASH) / encuesta de prácticas",
 "frecuencia":"semestral","momento_medicion":"todos","tipo_linea_base":"mixta",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"zona, tipo de abastecimiento de agua, nivel educativo del jefe de hogar",
 "ods_meta":"ODS 6.2","fuente_referencia":"UNICEF WASH, OPS","codigo_iris":"OD7892",
 "valor_referencia":"","ejemplo_programa":"Programa WASH comunitario — Hogares Saludables",
 "limitaciones":"La observación directa puede modificar el comportamiento (efecto Hawthorne); el autoreporte sobreestima la práctica.",
 "idioma":"ES"},

{"id":"S014","nombre":"Porcentaje de personas con adherencia al tratamiento farmacológico",
 "nombre_en":"Percentage of patients adherent to pharmacological treatment",
 "descripcion":"Proporción de pacientes que toman ≥80% de las dosis prescritas de su medicamento en el período. Indicador de resultado clave en manejo de enfermedades crónicas.",
 "tipo":"resultado","sector":"Salud","subsector":"Enfermedades crónicas no transmisibles",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Pacientes con PDC≥80% / Total pacientes en tratamiento) × 100  [PDC = Proportion of Days Covered]",
 "metodo_recoleccion":"registro_administrativo","instrumento_sugerido":"Datos de dispensación farmacéutica / test de Morisky-Green",
 "frecuencia":"semestral","momento_medicion":"seguimiento","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"tipo de medicamento, condición, sexo, grupo etario",
 "ods_meta":"ODS 3.4","fuente_referencia":"OPS, MINSALUD Colombia","codigo_iris":"",
 "valor_referencia":"Adherencia óptima: ≥80% PDC; promedio HTA: 50–60%",
 "ejemplo_programa":"Programa de crónicos — ACEMI Colombia",
 "limitaciones":"PDC es proxy; no mide si el paciente tomó correctamente (hora, dosis). Test Morisky tiene sesgo de autoreporte.",
 "idioma":"ES"},

{"id":"S015","nombre":"Porcentaje de personas que reportan mejora en calidad de vida relacionada con salud (SF-12 / SF-36)",
 "nombre_en":"Percentage reporting improvement in health-related quality of life",
 "descripcion":"Proporción de participantes que muestran aumento significativo en el puntaje SF-12 o SF-36 entre la línea de base y el seguimiento. Indicador compuesto de resultado-impacto en programas de salud.",
 "tipo":"impacto","sector":"Salud","subsector":"Calidad de vida",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Personas con ΔSCORE ≥ MCID / Total participantes evaluados) × 100 [MCID SF-12: ~3 puntos]",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"Cuestionario SF-12 / SF-36 (validado en español)",
 "frecuencia":"semestral","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"sexo, grupo etario, condición crónica, componente físico vs. mental",
 "ods_meta":"ODS 3.4","fuente_referencia":"Ware & Sherbourne (1992); ICONTEC Colombia","codigo_iris":"OD5141",
 "valor_referencia":"","ejemplo_programa":"Evaluaciones de programas crónicos — EPS Colombia",
 "limitaciones":"Instrumento largo (SF-36); requiere capacidad de lectura. SF-12 es más corto pero menos sensible.",
 "idioma":"ES"},

{"id":"S016","nombre":"Puntaje promedio de bienestar subjetivo (escala 0–10)",
 "nombre_en":"Average subjective wellbeing score (0–10 scale)",
 "descripcion":"Puntaje promedio en la pregunta 'En general, ¿cuán satisfecho está con su vida en este momento?' (Cantril Ladder). Indicador WELLBY de referencia para valoración monetaria del bienestar.",
 "tipo":"impacto","sector":"Salud","subsector":"Salud mental y bienestar",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"puntaje",
 "formula":"Σ puntajes / n participantes",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"Cantril Self-Anchoring Scale (pregunta única Cantril Ladder)",
 "frecuencia":"semestral","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"sexo, grupo etario, zona, condición socioeconómica",
 "ods_meta":"ODS 3.4","fuente_referencia":"Diener et al., OECD Guidelines on Measuring Subjective Wellbeing","codigo_iris":"OD5142",
 "valor_referencia":"Referencia Colombia: ~6.5–7.0; UK: ~7.5","ejemplo_programa":"WELLBY analysis — Social Value UK",
 "limitaciones":"Escala captura evaluación cognitiva de la vida, no emociones momentáneas. Requiere traducción cultural.",
 "idioma":"ES"},

{"id":"S017","nombre":"Porcentaje de personas con acceso efectivo a servicios de salud mental",
 "nombre_en":"Percentage with effective access to mental health services",
 "descripcion":"Proporción de personas con trastorno mental identificado que recibieron al menos una intervención terapéutica en el período. Indicador de cobertura de salud mental.",
 "tipo":"resultado","sector":"Salud","subsector":"Salud mental",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Personas con TMC que reciben atención / Total personas con TMC identificado) × 100",
 "metodo_recoleccion":"registro_administrativo","instrumento_sugerido":"Historia clínica / registro del programa",
 "frecuencia":"anual","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"tipo de trastorno, sexo, grupo etario, tipo de servicio (ambulatorio/hospitalario)",
 "ods_meta":"ODS 3.4","fuente_referencia":"OMS mhGAP, MSPS Colombia","codigo_iris":"",
 "valor_referencia":"Brecha de tratamiento en Colombia: ~75–80% sin atención",
 "ejemplo_programa":"Programa de salud mental comunitaria — OPS/MSPS",
 "limitaciones":"Definición de 'acceso efectivo' varía; el subdiagnóstico sesga el denominador.",
 "idioma":"ES"},

{"id":"S018","nombre":"Puntuación en escala PHQ-9 (depresión) pre-post intervención",
 "nombre_en":"PHQ-9 depression score pre-post intervention",
 "descripcion":"Cambio en el puntaje del Patient Health Questionnaire-9 entre la evaluación inicial y el seguimiento. Mide la reducción de síntomas depresivos como resultado de la intervención.",
 "tipo":"resultado","sector":"Salud","subsector":"Salud mental",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"puntaje",
 "formula":"ΔPHQ-9 = Puntaje inicial − Puntaje final (reducción positiva = mejora)",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"PHQ-9 (validado en español colombiano)",
 "frecuencia":"semestral","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"sexo, grupo etario, severidad inicial, tipo de intervención",
 "ods_meta":"ODS 3.4","fuente_referencia":"Kroenke et al. (2001); Diez-Quevedo et al. (2001) validación ES","codigo_iris":"",
 "valor_referencia":"Cambio mínimo clínicamente significativo (MCID): ΔPHQ-9 ≥5 puntos; remisión: PHQ-9 <5",
 "ejemplo_programa":"Programas de salud mental — Cruz Roja, MSF","limitaciones":"PHQ-9 es autoaplicado; requiere alfabetismo y puede tener sesgo de deseabilidad social.",
 "idioma":"ES"},

# --- SALUD — INDICADORES CUALITATIVOS ---
{"id":"S019","nombre":"Percepción de calidad de la atención en salud recibida (escala 1–5)",
 "nombre_en":"Perceived quality of health services received",
 "descripcion":"Valoración subjetiva del usuario sobre la calidad de la atención recibida, incluyendo trato del personal, tiempo de espera, claridad de la información y adecuación cultural. Captura dimensiones no medidas por indicadores clínicos.",
 "tipo":"resultado","sector":"Salud","subsector":"Atención primaria",
 "nivel_medicion":"individual","enfoque":"cualitativo","unidad":"puntaje",
 "formula":"Escala Likert 1 (muy mala) a 5 (excelente); reportar media y distribución de respuestas",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"Encuesta de satisfacción de usuarios (SERVQUAL adaptado para salud)",
 "frecuencia":"semestral","momento_medicion":"seguimiento","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"sexo, tipo de servicio, zona, pertenencia étnica",
 "ods_meta":"ODS 3.8","fuente_referencia":"OPS, MSPS Colombia","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"Encuestas de satisfacción — EPS Colombia",
 "limitaciones":"Sesgo de cortesía (especialmente en entornos comunitarios); no captura aspectos técnicos de la atención.",
 "idioma":"ES"},

{"id":"S020","nombre":"Narrativas sobre cambios en comportamientos de salud (análisis cualitativo)",
 "nombre_en":"Narratives on changes in health behaviours (qualitative analysis)",
 "descripcion":"Testimonios y relatos de participantes sobre cambios percibidos en sus hábitos de salud (alimentación, ejercicio, consulta oportuna, etc.) como resultado de la intervención. Complementa indicadores cuantitativos con profundidad contextual.",
 "tipo":"resultado","sector":"Salud","subsector":"Promoción de la salud",
 "nivel_medicion":"individual","enfoque":"cualitativo","unidad":"n/a",
 "formula":"Análisis temático de entrevistas/grupos focales; codificación por tipo de cambio",
 "metodo_recoleccion":"entrevista","instrumento_sugerido":"Guía de entrevista semiestructurada / grupo focal (8–10 personas)",
 "frecuencia":"semestral","momento_medicion":"evaluacion_final","tipo_linea_base":"cualitativa",
 "diseno_comparacion":"participativo",
 "desagregacion_recomendada":"sexo, grupo etario, perfil de riesgo",
 "ods_meta":"ODS 3.4","fuente_referencia":"Método Most Significant Change (MSC); Earl et al. (2001)","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"Evaluaciones cualitativas — Hogares Saludables, UNICEF",
 "limitaciones":"No permite generalización estadística; requiere analistas con experiencia en análisis cualitativo; puede haber sesgo de selección en quienes participan.",
 "idioma":"ES"},

# ─────────────────────────────────────────────────────────────────────────────
# SECTOR: EDUCACIÓN
# ─────────────────────────────────────────────────────────────────────────────

# --- EDUCACIÓN — PRODUCTOS ---
{"id":"E001","nombre":"Número de estudiantes matriculados en el programa",
 "nombre_en":"Number of students enrolled in the programme",
 "descripcion":"Total de estudiantes que se registraron formalmente en el programa educativo en el período. Indicador base de alcance y cobertura.",
 "tipo":"producto","sector":"Educación","subsector":"Educación básica y media",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"n",
 "formula":"Σ estudiantes con matrícula activa al inicio del período",
 "metodo_recoleccion":"registro_administrativo","instrumento_sugerido":"Sistema de información estudiantil (SIMAT en Colombia)",
 "frecuencia":"anual","momento_medicion":"seguimiento","tipo_linea_base":"no_aplica",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"sexo, grado, zona, etnia, condición de discapacidad",
 "ods_meta":"ODS 4.1","fuente_referencia":"MEN Colombia, UNESCO","codigo_iris":"PI2345",
 "valor_referencia":"","ejemplo_programa":"Matrícula SIMAT — Ministerio de Educación Colombia",
 "limitaciones":"Matrícula no equivale a asistencia real ni aprendizaje; puede haber inflación de cifras.",
 "idioma":"ES"},

{"id":"E002","nombre":"Número de docentes capacitados en el programa",
 "nombre_en":"Number of teachers trained in the programme",
 "descripcion":"Total de docentes que completaron al menos una capacitación o proceso de formación continua en el período. Proxy de fortalecimiento de capacidades pedagógicas.",
 "tipo":"producto","sector":"Educación","subsector":"Formación docente",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"n",
 "formula":"Σ docentes que completaron ≥1 módulo de formación",
 "metodo_recoleccion":"registro_administrativo","instrumento_sugerido":"Lista de asistencia + certificado de participación",
 "frecuencia":"semestral","momento_medicion":"seguimiento","tipo_linea_base":"no_aplica",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"sexo, nivel educativo, asignatura, zona",
 "ods_meta":"ODS 4.c","fuente_referencia":"MEN Colombia, UNESCO","codigo_iris":"PI2354",
 "valor_referencia":"","ejemplo_programa":"Programa de Formación Docente — Escuela Nueva Colombia",
 "limitaciones":"Formación no garantiza cambio pedagógico en el aula; requiere seguimiento posterior.",
 "idioma":"ES"},

{"id":"E003","nombre":"Número de materiales educativos producidos o distribuidos",
 "nombre_en":"Number of educational materials produced or distributed",
 "descripcion":"Total de materiales didácticos, libros, guías o recursos digitales producidos o entregados a estudiantes y docentes en el período.",
 "tipo":"producto","sector":"Educación","subsector":"Recursos pedagógicos",
 "nivel_medicion":"comunidad","enfoque":"cuantitativo","unidad":"n",
 "formula":"Σ unidades de materiales producidas/distribuidas",
 "metodo_recoleccion":"registro_administrativo","instrumento_sugerido":"Inventario de materiales + acta de entrega",
 "frecuencia":"anual","momento_medicion":"seguimiento","tipo_linea_base":"no_aplica",
 "diseno_comparacion":"sin_comparacion",
 "desagregacion_recomendada":"tipo de material, nivel educativo, zona, idioma",
 "ods_meta":"ODS 4.1","fuente_referencia":"MEN Colombia, UNICEF","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"Programa Todos a Aprender — MEN Colombia",
 "limitaciones":"La distribución no garantiza uso efectivo; materiales pueden no ser pertinentes culturalmente.",
 "idioma":"ES"},

{"id":"E004","nombre":"Número de instituciones educativas intervenidas",
 "nombre_en":"Number of educational institutions receiving intervention",
 "descripcion":"Total de escuelas, colegios o centros educativos que participaron activamente en el programa durante el período.",
 "tipo":"producto","sector":"Educación","subsector":"Educación básica y media",
 "nivel_medicion":"comunidad","enfoque":"cuantitativo","unidad":"n",
 "formula":"Σ IEDs con al menos una actividad del programa en el período",
 "metodo_recoleccion":"registro_administrativo","instrumento_sugerido":"Registro de instituciones participantes",
 "frecuencia":"anual","momento_medicion":"seguimiento","tipo_linea_base":"no_aplica",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"nivel educativo, zona, tipo de institución (oficial/privada)",
 "ods_meta":"ODS 4.1","fuente_referencia":"MEN Colombia","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"Colombia Aprende — MEN",
 "limitaciones":"No refleja profundidad ni calidad de la intervención por institución.",
 "idioma":"ES"},

# --- EDUCACIÓN — RESULTADOS ---
{"id":"E005","nombre":"Tasa de asistencia escolar (%)",
 "nombre_en":"School attendance rate (%)",
 "descripcion":"Porcentaje de días escolares en que los estudiantes inscritos asistieron efectivamente a clase. Indicador de retención y compromiso con el proceso educativo.",
 "tipo":"resultado","sector":"Educación","subsector":"Educación básica y media",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Días de asistencia efectiva / Días escolares posibles) × 100",
 "metodo_recoleccion":"registro_administrativo","instrumento_sugerido":"Registro de asistencia escolar / SIMAT",
 "frecuencia":"mensual","momento_medicion":"seguimiento","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"sexo, grado, zona, etnia, condición socioeconómica",
 "ods_meta":"ODS 4.1","fuente_referencia":"MEN Colombia, UNESCO","codigo_iris":"OD3942",
 "valor_referencia":"Meta Colombia: ≥90% asistencia","ejemplo_programa":"Programa de Alimentación Escolar (PAE) Colombia",
 "limitaciones":"No refleja calidad del aprendizaje; el registro puede tener errores o manipulación.",
 "idioma":"ES"},

{"id":"E006","nombre":"Tasa de deserción escolar (%)",
 "nombre_en":"School dropout rate (%)",
 "descripcion":"Porcentaje de estudiantes que abandonaron el sistema educativo durante el período sin completar el grado o nivel. Indicador de resultado negativo clave en programas de retención escolar.",
 "tipo":"resultado","sector":"Educación","subsector":"Educación básica y media",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Estudiantes que abandonaron / Estudiantes matriculados al inicio) × 100",
 "metodo_recoleccion":"registro_administrativo","instrumento_sugerido":"SIMAT / registros de la institución educativa",
 "frecuencia":"anual","momento_medicion":"seguimiento","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"sexo, grado, zona, causa de deserción, etnia",
 "ods_meta":"ODS 4.1","fuente_referencia":"MEN Colombia, UNESCO","codigo_iris":"OD3943",
 "valor_referencia":"Meta Colombia: <3% deserción intra-anual","ejemplo_programa":"Programa Niños y Niñas del Futuro — Caldas",
 "limitaciones":"La tasa no captura causas de la deserción; diferencia entre deserción intra-anual e inter-anual.",
 "idioma":"ES"},

{"id":"E007","nombre":"Puntaje promedio en prueba de comprensión lectora",
 "nombre_en":"Average score on reading comprehension assessment",
 "descripcion":"Puntuación media en una evaluación estandarizada de comprensión lectora aplicada a los estudiantes. Indicador de resultado sobre aprendizaje efectivo en alfabetización.",
 "tipo":"resultado","sector":"Educación","subsector":"Alfabetización y lectura",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"puntaje",
 "formula":"Σ puntajes / n estudiantes evaluados",
 "metodo_recoleccion":"observacion_directa","instrumento_sugerido":"Prueba Saber (Colombia), EGRA (Early Grade Reading Assessment), ASER",
 "frecuencia":"anual","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"grado, sexo, zona, nivel socioeconómico",
 "ods_meta":"ODS 4.1","fuente_referencia":"ICFES Colombia, UNESCO / LLECE","codigo_iris":"OD3941",
 "valor_referencia":"","ejemplo_programa":"Leer es mi Cuento — MEN Colombia; Room to Read",
 "limitaciones":"Pruebas estandarizadas pueden no capturar el contexto cultural; el puntaje depende de la calidad del instrumento.",
 "idioma":"ES"},

{"id":"E008","nombre":"Puntaje promedio en prueba de competencias matemáticas",
 "nombre_en":"Average score on mathematics assessment",
 "descripcion":"Puntuación media en evaluación estandarizada de matemáticas. Indicador complementario de resultado en aprendizaje.",
 "tipo":"resultado","sector":"Educación","subsector":"Matemáticas y STEM",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"puntaje",
 "formula":"Σ puntajes / n estudiantes evaluados",
 "metodo_recoleccion":"observacion_directa","instrumento_sugerido":"Prueba Saber / EGMA / TIMSS",
 "frecuencia":"anual","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"grado, sexo, zona, nivel socioeconómico",
 "ods_meta":"ODS 4.1","fuente_referencia":"ICFES Colombia, UNESCO / LLECE","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"Programa Todos a Aprender — MEN Colombia",
 "limitaciones":"Similar a comprensión lectora; adicional: matemáticas tiene mayor varianza por calidad docente.",
 "idioma":"ES"},

{"id":"E009","nombre":"Porcentaje de estudiantes que alcanzan el nivel mínimo de competencia (NMC)",
 "nombre_en":"Percentage of students reaching minimum proficiency level",
 "descripcion":"Proporción de estudiantes que obtienen el nivel mínimo de competencia en lectura y/o matemáticas según el estándar de evaluación ODS 4. Indicador de referencia de la agenda educativa global.",
 "tipo":"resultado","sector":"Educación","subsector":"Calidad educativa",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Estudiantes en nivel ≥2 PISA o nivel satisfactorio Saber / Total estudiantes) × 100",
 "metodo_recoleccion":"observacion_directa","instrumento_sugerido":"Prueba Saber / PISA / TERCE / ERCE",
 "frecuencia":"anual","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"grado, sexo, zona, etnia, quintil socioeconómico",
 "ods_meta":"ODS 4.1","fuente_referencia":"UNESCO, ICFES Colombia","codigo_iris":"OD3941",
 "valor_referencia":"Colombia: ~50% en NMC lectura, ~35% en NMC matemáticas (ERCE 2019)",
 "ejemplo_programa":"ODS 4 — Seguimiento SDG4 Education 2030","limitaciones":"El NMC varía según el instrumento utilizado; comparaciones entre países requieren cuidado.",
 "idioma":"ES"},

{"id":"E010","nombre":"Tasa de transición de primaria a secundaria (%)",
 "nombre_en":"Primary to secondary transition rate (%)",
 "descripcion":"Porcentaje de estudiantes que, habiendo completado la educación primaria, se matriculan en educación secundaria. Indicador de resultado sobre continuidad educativa.",
 "tipo":"resultado","sector":"Educación","subsector":"Transiciones educativas",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Matriculados en 6° grado / Graduados de 5° grado en año anterior) × 100",
 "metodo_recoleccion":"datos_secundarios","instrumento_sugerido":"SIMAT / estadísticas MEN",
 "frecuencia":"anual","momento_medicion":"seguimiento","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"sexo, zona, departamento",
 "ods_meta":"ODS 4.1","fuente_referencia":"MEN Colombia, UNESCO","codigo_iris":"",
 "valor_referencia":"Colombia: ~85% transición primaria-secundaria","ejemplo_programa":"Gratuidad educativa — MEN Colombia",
 "limitaciones":"La cifra puede verse afectada por cambios en la definición de grados o sistemas de registro.",
 "idioma":"ES"},

{"id":"E011","nombre":"Porcentaje de niños de 3–5 años en programas de educación inicial",
 "nombre_en":"Percentage of 3–5 year-olds in early childhood education",
 "descripcion":"Tasa de participación en educación inicial (jardín infantil, CDI, hogares comunitarios ICBF) en el grupo de 3–5 años. Indicador de cobertura en primera infancia.",
 "tipo":"resultado","sector":"Educación","subsector":"Primera infancia",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Niños 3–5 años en programas de educación inicial / Total niños 3–5 años en zona) × 100",
 "metodo_recoleccion":"datos_secundarios","instrumento_sugerido":"SIMAT / ICBF / SISPRO",
 "frecuencia":"anual","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"sexo, zona, etnia, nivel socioeconómico",
 "ods_meta":"ODS 4.2","fuente_referencia":"ICBF, MEN Colombia, UNICEF","codigo_iris":"OD3946",
 "valor_referencia":"Colombia: ~65–70% cobertura 3–5 años","ejemplo_programa":"De Cero a Siempre — Colombia",
 "limitaciones":"Cobertura no implica calidad; varía mucho entre zonas rurales y urbanas.",
 "idioma":"ES"},

# --- EDUCACIÓN — IMPACTOS ---
{"id":"E012","nombre":"Tasa de analfabetismo funcional en adultos (%)",
 "nombre_en":"Adult functional illiteracy rate (%)",
 "descripcion":"Proporción de personas de 15 años o más que no pueden leer ni escribir un enunciado corto de la vida cotidiana con comprensión básica. Indicador de impacto sobre el capital humano de la población.",
 "tipo":"impacto","sector":"Educación","subsector":"Alfabetización adultos",
 "nivel_medicion":"sistema","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Personas ≥15 años analfabetas / Total personas ≥15 años) × 100",
 "metodo_recoleccion":"datos_secundarios","instrumento_sugerido":"GEIH-DANE / ELPS / Censo de Población",
 "frecuencia":"anual","momento_medicion":"impacto","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"sexo, grupo etario, zona, etnia, departamento",
 "ods_meta":"ODS 4.6","fuente_referencia":"DANE Colombia, UNESCO","codigo_iris":"OD3948",
 "valor_referencia":"Colombia: ~5.5% analfabetismo (DANE 2020)","ejemplo_programa":"Colombia Libre de Analfabetismo — MEN",
 "limitaciones":"DANE usa criterio de declaración propia; subestima el analfabetismo funcional real.",
 "idioma":"ES"},

{"id":"E013","nombre":"Años promedio de escolaridad de la población adulta",
 "nombre_en":"Average years of schooling of adult population",
 "descripcion":"Número promedio de años de educación formal completados por personas de 25 años o más. Indicador de capital humano y resultado de largo plazo del sistema educativo.",
 "tipo":"impacto","sector":"Educación","subsector":"Capital humano",
 "nivel_medicion":"sistema","enfoque":"cuantitativo","unidad":"años",
 "formula":"Σ años de escolaridad / n personas ≥25 años",
 "metodo_recoleccion":"datos_secundarios","instrumento_sugerido":"GEIH-DANE / Censo de Población",
 "frecuencia":"anual","momento_medicion":"impacto","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"sexo, zona, etnia, departamento, quintil de ingresos",
 "ods_meta":"ODS 4.3","fuente_referencia":"DANE Colombia, UNDP HDI","codigo_iris":"",
 "valor_referencia":"Colombia: ~9.5 años (2022); promedio OCDE: ~12 años",
 "ejemplo_programa":"Índice de Desarrollo Humano — PNUD","limitaciones":"Indicador lento; cambios tardan décadas en reflejarse.",
 "idioma":"ES"},

{"id":"E014","nombre":"Porcentaje de personas con educación superior completa (25–34 años)",
 "nombre_en":"Percentage of 25–34 year olds with tertiary education",
 "descripcion":"Proporción de jóvenes adultos (25–34) que han completado al menos un título técnico, tecnológico o universitario. Indicador de impacto sobre el nivel educativo de la generación más reciente.",
 "tipo":"impacto","sector":"Educación","subsector":"Educación superior",
 "nivel_medicion":"sistema","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Personas 25–34 con educación superior completa / Total personas 25–34) × 100",
 "metodo_recoleccion":"datos_secundarios","instrumento_sugerido":"GEIH-DANE / ELPS / Estadísticas MEN-SNIES",
 "frecuencia":"anual","momento_medicion":"impacto","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"sexo, zona, etnia, departamento, área del conocimiento",
 "ods_meta":"ODS 4.3","fuente_referencia":"DANE, MEN-SNIES, OCDE","codigo_iris":"",
 "valor_referencia":"Colombia: ~28% (2022); OCDE promedio: ~45%",
 "ejemplo_programa":"Ser Pilo Paga / Generación E — MEN Colombia","limitaciones":"No captura calidad de la educación recibida ni pertinencia del título.",
 "idioma":"ES"},

{"id":"E015","nombre":"Percepción de los docentes sobre cambios en motivación y participación estudiantil",
 "nombre_en":"Teacher perception of changes in student motivation and participation",
 "descripcion":"Valoración cualitativa de los docentes sobre cambios observados en la motivación, participación activa y actitudes de aprendizaje de los estudiantes durante y después del programa. Captura cambios que las pruebas estandarizadas no miden.",
 "tipo":"resultado","sector":"Educación","subsector":"Clima escolar",
 "nivel_medicion":"individual","enfoque":"cualitativo","unidad":"n/a",
 "formula":"Análisis temático de entrevistas / grupos focales con docentes; categorías: más/igual/menos motivación",
 "metodo_recoleccion":"grupo_focal","instrumento_sugerido":"Guía de grupo focal docente (8–12 participantes)",
 "frecuencia":"semestral","momento_medicion":"evaluacion_final","tipo_linea_base":"cualitativa",
 "diseno_comparacion":"participativo",
 "desagregacion_recomendada":"grado, asignatura, zona",
 "ods_meta":"ODS 4.1","fuente_referencia":"Fullan (2001) — The New Meaning of Educational Change","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"Escuela Nueva Colombia — Evaluaciones cualitativas",
 "limitaciones":"Subjetividad del docente; posible sesgo de confirmación si el docente implementó el programa.",
 "idioma":"ES"},

{"id":"E016","nombre":"Porcentaje de estudiantes que declaran sentirse seguros en la escuela",
 "nombre_en":"Percentage of students reporting feeling safe at school",
 "descripcion":"Proporción de estudiantes que afirman sentirse seguros (física y emocionalmente) en el entorno escolar. Indicador de resultado de clima escolar y bienestar educativo.",
 "tipo":"resultado","sector":"Educación","subsector":"Clima escolar y bienestar",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Estudiantes que responden 'Siempre' o 'Casi siempre' a ítem de seguridad / Total encuestados) × 100",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"Encuesta de Clima Escolar (ICFES / LLECE / UNESCO)",
 "frecuencia":"anual","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"sexo, grado, zona, tipo de institución",
 "ods_meta":"ODS 4.a","fuente_referencia":"UNESCO ERCE, ICFES Colombia","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"Ambientes de Aprendizaje Escolar — UNESCO LLECE",
 "limitaciones":"Respuesta puede variar por temor a represalias; difícil capturar bullying encubierto.",
 "idioma":"ES"},

{"id":"E017","nombre":"Número de horas de formación técnica o vocacional completadas por estudiante",
 "nombre_en":"Hours of technical / vocational training completed per student",
 "descripcion":"Promedio de horas de formación técnica o vocacional completadas por estudiante inscrito en el período. Indicador de producto de intensidad de la formación.",
 "tipo":"producto","sector":"Educación","subsector":"Educación técnica y vocacional (EFTP)",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"horas",
 "formula":"Σ horas completadas / n estudiantes matriculados",
 "metodo_recoleccion":"registro_administrativo","instrumento_sugerido":"Registro de asistencia y horas de instrucción",
 "frecuencia":"semestral","momento_medicion":"seguimiento","tipo_linea_base":"no_aplica",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"sexo, área de formación, zona, programa específico",
 "ods_meta":"ODS 4.3","fuente_referencia":"SENA Colombia, UNESCO-UNEVOC","codigo_iris":"PI2356",
 "valor_referencia":"SENA: 600–1200 horas / programa técnico",
 "ejemplo_programa":"Formación para el Trabajo — SENA Colombia","limitaciones":"Las horas no garantizan competencia efectiva; depende de calidad pedagógica.",
 "idioma":"ES"},

{"id":"E018","nombre":"Porcentaje de egresados de formación técnica que se insertan laboralmente en 6 meses",
 "nombre_en":"Percentage of technical training graduates employed within 6 months",
 "descripcion":"Proporción de graduados de formación técnica o vocacional que consiguen empleo formal o autoempleo dentro de los 6 meses posteriores a la graduación. Indicador de resultado de la pertinencia de la formación.",
 "tipo":"resultado","sector":"Educación","subsector":"Educación técnica y vocacional (EFTP)",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Egresados con empleo a los 6 meses / Total egresados encuestados) × 100",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"Encuesta de seguimiento de egresados (post-6 meses)",
 "frecuencia":"semestral","momento_medicion":"evaluacion_final","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"sexo, área de formación, zona, tipo de empleo (formal/informal)",
 "ods_meta":"ODS 4.4","fuente_referencia":"SENA Colombia, OIT","codigo_iris":"OD3950",
 "valor_referencia":"SENA Colombia: ~65–75% empleabilidad a 6 meses",
 "ejemplo_programa":"Sistema de Seguimiento a Egresados SENA","limitaciones":"El empleo puede no estar relacionado con la formación; diferencia entre empleo formal e informal.",
 "idioma":"ES"},

{"id":"E019","nombre":"Grado de desarrollo de competencias socioemocionales (escala validada)",
 "nombre_en":"Socioemotional skills development (validated scale)",
 "descripcion":"Puntaje en una escala validada de competencias socioemocionales (autoregulación, empatía, trabajo en equipo, resiliencia) al final del programa. Indicador de resultado en programas de educación integral.",
 "tipo":"resultado","sector":"Educación","subsector":"Competencias socioemocionales",
 "nivel_medicion":"individual","enfoque":"mixto","unidad":"puntaje",
 "formula":"Puntaje compuesto en escala SEL (ej. DESSA / SEARS / Escala BAS-1/3)",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"DESSA (Devereux Student Strengths Assessment), SEARS, o equivalente validado en ES",
 "frecuencia":"semestral","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"sexo, grado, zona, componente SEL (autoregulación, empatía, etc.)",
 "ods_meta":"ODS 4.7","fuente_referencia":"CASEL Framework; Durlak et al. (2011)","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"Aulas en Paz Colombia; Camino Seguro Guatemala",
 "limitaciones":"Escalas SEL tienen validez variable en diferentes contextos culturales; requieren adaptación.",
 "idioma":"ES"},

{"id":"E020","nombre":"Percepción de las familias sobre el progreso educativo de sus hijos (cualitativo)",
 "nombre_en":"Family perception of children's educational progress (qualitative)",
 "descripcion":"Relatos de padres y cuidadores sobre cambios percibidos en el aprendizaje, comportamiento y actitud hacia la escuela de sus hijos. Complementa la evidencia cuantitativa con perspectiva familiar.",
 "tipo":"resultado","sector":"Educación","subsector":"Participación familiar",
 "nivel_medicion":"hogar","enfoque":"cualitativo","unidad":"n/a",
 "formula":"Análisis de contenido de entrevistas; categorías: mejora / sin cambio / desmejora",
 "metodo_recoleccion":"entrevista","instrumento_sugerido":"Guía de entrevista semiestructurada para familias",
 "frecuencia":"semestral","momento_medicion":"evaluacion_final","tipo_linea_base":"cualitativa",
 "diseno_comparacion":"participativo",
 "desagregacion_recomendada":"zona, nivel educativo del padre/madre, tipo de familia",
 "ods_meta":"ODS 4.1","fuente_referencia":"Most Significant Change — Davies & Dart (2005)","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"Evaluaciones comunitarias — Escuela Nueva Colombia",
 "limitaciones":"Las expectativas de las familias pueden estar sesgadas por el deseo de retribución al programa; limitada capacidad de generalizar.",
 "idioma":"ES"},

]

def write_batch(indicators, mode="w"):
    with open(OUT, mode, newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=FIELDS, extrasaction="ignore")
        if mode == "w":
            writer.writeheader()
        writer.writerows(indicators)

write_batch(INDICATORS, mode="w")
print(f"Batch 1 escrito: {len(INDICATORS)} indicadores en {OUT}")
