"""
Batch 2 — Empleo + Género e igualdad + Infancia y derechos (~135 indicadores)
Añade al CSV existente (modo append).
"""
import csv, os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT  = os.path.join(BASE, "metadata", "indicadores.csv")

FIELDS = [
    "id","nombre","nombre_en","descripcion",
    "tipo","sector","subsector",
    "nivel_medicion","enfoque","unidad","formula",
    "metodo_recoleccion","instrumento_sugerido",
    "frecuencia","momento_medicion","tipo_linea_base","diseno_comparacion",
    "desagregacion_recomendada","ods_meta","fuente_referencia","codigo_iris",
    "valor_referencia","ejemplo_programa","limitaciones","idioma",
]

INDICATORS = [

# ─────────────────────────────────────────────────────────────────────────────
# SECTOR: EMPLEO E INGRESOS
# ─────────────────────────────────────────────────────────────────────────────

# PRODUCTOS
{"id":"EMP001","nombre":"Número de personas capacitadas para el empleo",
 "nombre_en":"Number of people trained for employment",
 "descripcion":"Total de personas que completaron al menos un proceso de formación para el trabajo (técnica, habilidades blandas, emprendimiento) en el período.",
 "tipo":"producto","sector":"Empleo e ingresos","subsector":"Formación para el trabajo",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"n",
 "formula":"Σ personas que completaron ≥1 módulo de formación laboral",
 "metodo_recoleccion":"registro_administrativo","instrumento_sugerido":"Lista de participantes con fecha de graduación",
 "frecuencia":"trimestral","momento_medicion":"seguimiento","tipo_linea_base":"no_aplica",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"sexo, grupo etario, zona, tipo de formación, nivel educativo previo",
 "ods_meta":"ODS 8.6","fuente_referencia":"SENA Colombia, OIT","codigo_iris":"PI9456",
 "valor_referencia":"","ejemplo_programa":"Jóvenes en Acción — SENA/DPS Colombia",
 "limitaciones":"Completar el curso no garantiza inserción laboral; puede haber deserción tardía.",
 "idioma":"ES"},

{"id":"EMP002","nombre":"Número de empresas sensibilizadas o articuladas con el programa",
 "nombre_en":"Number of employers engaged with the programme",
 "descripcion":"Total de empresas, empleadores o cooperativas que participaron en ferias, mesas de trabajo o convenios con el programa de empleo en el período.",
 "tipo":"producto","sector":"Empleo e ingresos","subsector":"Articulación con el mercado laboral",
 "nivel_medicion":"sistema","enfoque":"cuantitativo","unidad":"n",
 "formula":"Σ empresas con ≥1 interacción formal con el programa",
 "metodo_recoleccion":"registro_administrativo","instrumento_sugerido":"Base de datos de contactos empresariales",
 "frecuencia":"semestral","momento_medicion":"seguimiento","tipo_linea_base":"no_aplica",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"sector económico, tamaño empresa, zona",
 "ods_meta":"ODS 8.3","fuente_referencia":"OIT, SENA Colombia","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"Pacto por el Empleo — Ministerio de Trabajo Colombia",
 "limitaciones":"La articulación no garantiza que las empresas contraten; es un proxy de actividad, no de resultado.",
 "idioma":"ES"},

{"id":"EMP003","nombre":"Número de intermediaciones laborales realizadas",
 "nombre_en":"Number of job placements facilitated",
 "descripcion":"Total de gestiones de intermediación laboral donde el programa conectó a un candidato con una oferta de empleo, independientemente del resultado final de contratación.",
 "tipo":"producto","sector":"Empleo e ingresos","subsector":"Intermediación laboral",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"n",
 "formula":"Σ procesos de intermediación iniciados en el período",
 "metodo_recoleccion":"registro_administrativo","instrumento_sugerido":"Sistema de gestión de empleo (ej. SPE Colombia)",
 "frecuencia":"mensual","momento_medicion":"seguimiento","tipo_linea_base":"no_aplica",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"sexo, grupo etario, zona, sector económico",
 "ods_meta":"ODS 8.5","fuente_referencia":"Ministerio de Trabajo Colombia, SPE","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"Servicio Público de Empleo (SPE) — Colombia",
 "limitaciones":"Una intermediación puede contar varias gestiones para la misma persona; riesgo de doble conteo.",
 "idioma":"ES"},

# RESULTADOS EMPLEO
{"id":"EMP004","nombre":"Tasa de inserción laboral formal a 3 meses de graduados (%)",
 "nombre_en":"Formal employment rate at 3 months post-graduation (%)",
 "descripcion":"Proporción de egresados del programa de formación que obtuvieron empleo formal (con contrato y afiliación a seguridad social) dentro de los 3 meses posteriores a la graduación.",
 "tipo":"resultado","sector":"Empleo e ingresos","subsector":"Inserción laboral",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Egresados con empleo formal a 3 meses / Total egresados encuestados) × 100",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"Encuesta de seguimiento de egresados (llamada/formulario a 3 meses)",
 "frecuencia":"trimestral","momento_medicion":"evaluacion_final","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"sexo, grupo etario, zona, área de formación, tipo de contrato",
 "ods_meta":"ODS 8.5","fuente_referencia":"SENA Colombia, OIT","codigo_iris":"OD5876",
 "valor_referencia":"SENA Colombia: ~60–70% en empleo formal a 6 meses",
 "ejemplo_programa":"Seguimiento SENA / Jóvenes en Acción Colombia",
 "limitaciones":"Diferencia entre empleo formal e informal; difícil atribuir el empleo solo al programa.",
 "idioma":"ES"},

{"id":"EMP005","nombre":"Ingreso mensual promedio de participantes post-intervención (COP)",
 "nombre_en":"Average monthly income of participants post-intervention (local currency)",
 "descripcion":"Ingreso laboral mensual promedio de los participantes, medido 6 meses después de graduarse. Indicador de resultado sobre mejora económica directa.",
 "tipo":"resultado","sector":"Empleo e ingresos","subsector":"Ingresos y condiciones laborales",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"COP",
 "formula":"Σ ingresos laborales mensuales / n participantes empleados",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"Encuesta de seguimiento de egresados — módulo ingresos",
 "frecuencia":"semestral","momento_medicion":"evaluacion_final","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"sexo, zona, área de formación, tipo de empleo",
 "ods_meta":"ODS 8.5","fuente_referencia":"DANE-GEIH, OIT","codigo_iris":"OD5877",
 "valor_referencia":"Referencia SMMLV Colombia 2024: $1.300.000 COP/mes",
 "ejemplo_programa":"Evaluaciones de impacto de formación para el empleo — BID",
 "limitaciones":"Los ingresos son autodeclarados; posible sub o sobredeclaración. No distingue tipo de empleo.",
 "idioma":"ES"},

{"id":"EMP006","nombre":"Cambio porcentual en ingresos laborales pre-post intervención (%)",
 "nombre_en":"Percentage change in labour income pre-post intervention",
 "descripcion":"Variación relativa en el ingreso laboral mensual entre la línea de base (antes del programa) y el seguimiento. Indicador clave para evaluaciones con datos de panel.",
 "tipo":"resultado","sector":"Empleo e ingresos","subsector":"Ingresos y condiciones laborales",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"%",
 "formula":"((Ingreso_post − Ingreso_pre) / Ingreso_pre) × 100",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"Encuesta panel de participantes (misma persona en t0 y t1)",
 "frecuencia":"semestral","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"sexo, grupo etario, zona, tipo de programa",
 "ods_meta":"ODS 8.5","fuente_referencia":"J-PAL, IPA, BID Lab","codigo_iris":"",
 "valor_referencia":"Impactos típicos en programas activos de empleo: 10–35% incremento (J-PAL meta-análisis)",
 "ejemplo_programa":"Jóvenes en Acción — evaluación de impacto BID-DNP Colombia",
 "limitaciones":"Requiere seguimiento de la misma persona; alta tasa de atrición puede sesgar resultados.",
 "idioma":"ES"},

{"id":"EMP007","nombre":"Porcentaje de trabajadores con contrato formal y acceso a seguridad social",
 "nombre_en":"Percentage of workers with formal contract and social security access",
 "descripcion":"Proporción de participantes empleados que tienen contrato laboral escrito y afiliación a pensión, salud y riesgos laborales. Indicador de calidad del empleo.",
 "tipo":"resultado","sector":"Empleo e ingresos","subsector":"Trabajo decente",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Empleados con contrato formal + SS / Total empleados) × 100",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"Encuesta de condiciones laborales / PILA Colombia",
 "frecuencia":"anual","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"sexo, grupo etario, zona, sector económico, tipo de contrato",
 "ods_meta":"ODS 8.3","fuente_referencia":"DANE-GEIH, Ministerio de Trabajo Colombia, OIT","codigo_iris":"OD5878",
 "valor_referencia":"Informalidad laboral Colombia: ~57% (2023)",
 "ejemplo_programa":"Programa de Formalización Laboral — MTE Colombia",
 "limitaciones":"Las personas pueden tener acceso a SS sin contrato formal (independientes cotizantes).",
 "idioma":"ES"},

{"id":"EMP008","nombre":"Tasa de desempleo de los participantes al final del programa (%)",
 "nombre_en":"Participant unemployment rate at programme end (%)",
 "descripcion":"Proporción de participantes que, al final del período de intervención, se encuentran desempleados (sin empleo y en búsqueda activa). Indicador de resultado sobre situación laboral.",
 "tipo":"resultado","sector":"Empleo e ingresos","subsector":"Situación laboral",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Participantes desempleados activos / Total PEA participantes) × 100",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"Encuesta de seguimiento (adaptada de GEIH)",
 "frecuencia":"semestral","momento_medicion":"evaluacion_final","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"sexo, grupo etario, zona, nivel educativo",
 "ods_meta":"ODS 8.5","fuente_referencia":"DANE-GEIH, OIT","codigo_iris":"",
 "valor_referencia":"Tasa desempleo Colombia 2023: ~10–11%",
 "ejemplo_programa":"Programas de empleo juvenil — OIT/SENA",
 "limitaciones":"PEA puede ser difícil de definir en contextos de informalidad alta.",
 "idioma":"ES"},

{"id":"EMP009","nombre":"Número de emprendimientos creados o formalizados",
 "nombre_en":"Number of businesses created or formalized",
 "descripcion":"Total de negocios, microempresas o emprendimientos nuevos registrados legalmente o que iniciaron operaciones como resultado del apoyo del programa.",
 "tipo":"resultado","sector":"Empleo e ingresos","subsector":"Emprendimiento y autoempleo",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"n",
 "formula":"Σ emprendimientos con registro o comprobante de inicio de operaciones",
 "metodo_recoleccion":"registro_administrativo","instrumento_sugerido":"Base de datos de beneficiarios + RUES Colombia",
 "frecuencia":"semestral","momento_medicion":"evaluacion_final","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"sexo, sector económico, zona, tipo (formal/informal)",
 "ods_meta":"ODS 8.3","fuente_referencia":"CCBC, RUES Colombia, OIT","codigo_iris":"OD5879",
 "valor_referencia":"","ejemplo_programa":"Fondo Emprender SENA / Rutas de Empleo — Colombia",
 "limitaciones":"Registro no garantiza supervivencia; muchos emprendimientos cierran en el primer año.",
 "idioma":"ES"},

{"id":"EMP010","nombre":"Tasa de supervivencia de emprendimientos a 12 meses (%)",
 "nombre_en":"Business survival rate at 12 months (%)",
 "descripcion":"Proporción de emprendimientos creados con apoyo del programa que siguen activos a los 12 meses. Indicador de resultado sobre sostenibilidad del emprendimiento.",
 "tipo":"resultado","sector":"Empleo e ingresos","subsector":"Emprendimiento y autoempleo",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Emprendimientos activos a 12 meses / Total emprendimientos creados) × 100",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"Encuesta de seguimiento a emprendedores (12 meses post-creación)",
 "frecuencia":"anual","momento_medicion":"impacto","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"sexo, sector económico, zona, acceso a crédito",
 "ods_meta":"ODS 8.3","fuente_referencia":"Confecámaras Colombia, OCDE","codigo_iris":"",
 "valor_referencia":"Supervivencia 1 año en Colombia: ~55–60%; OCDE: ~65%",
 "ejemplo_programa":"iNNpulsa Colombia / Fondo Emprender SENA",
 "limitaciones":"Sesgo de supervivencia; los que cierran son más difíciles de localizar para el seguimiento.",
 "idioma":"ES"},

# IMPACTOS EMPLEO
{"id":"EMP011","nombre":"Incremento en el ingreso del hogar atribuible al programa (COP/USD)",
 "nombre_en":"Programme-attributable increase in household income",
 "descripcion":"Cambio neto en el ingreso total del hogar atribuible al programa, descontando deadweight, atribución a otros factores y efectos de desplazamiento. Indicador de impacto económico neto.",
 "tipo":"impacto","sector":"Empleo e ingresos","subsector":"Bienestar económico del hogar",
 "nivel_medicion":"hogar","enfoque":"cuantitativo","unidad":"COP",
 "formula":"ΔIngreso_hogar × (1 − deadweight) × attribution × (1 − displacement)",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"Encuesta de ingresos del hogar (panel) + análisis contrafactual",
 "frecuencia":"anual","momento_medicion":"impacto","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"grupo_control",
 "desagregacion_recomendada":"sexo del jefe de hogar, zona, quintil de ingreso, número de miembros",
 "ods_meta":"ODS 1.2","fuente_referencia":"J-PAL, IPA, BID — evaluaciones de impacto","codigo_iris":"OD5880",
 "valor_referencia":"","ejemplo_programa":"Jóvenes en Acción — evaluación RCT BID/DNP",
 "limitaciones":"Requiere diseño de evaluación riguroso (RCT o cuasi-experimental); difícil de medir sin contrafactual.",
 "idioma":"ES"},

{"id":"EMP012","nombre":"Reducción de la tasa de pobreza monetaria en la población objetivo (%)",
 "nombre_en":"Reduction in monetary poverty rate in target population",
 "descripcion":"Cambio en la proporción de hogares bajo la línea de pobreza monetaria antes y después de la intervención, en la población objetivo. Indicador de impacto sobre bienestar económico.",
 "tipo":"impacto","sector":"Empleo e ingresos","subsector":"Reducción de la pobreza",
 "nivel_medicion":"hogar","enfoque":"cuantitativo","unidad":"%",
 "formula":"Δ(Hogares bajo LPM / Total hogares) × 100",
 "metodo_recoleccion":"datos_secundarios","instrumento_sugerido":"DANE-GEIH / ELPS / encuesta de condiciones de vida",
 "frecuencia":"anual","momento_medicion":"impacto","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"grupo_control",
 "desagregacion_recomendada":"zona, etnia, tipo de hogar, departamento",
 "ods_meta":"ODS 1.2","fuente_referencia":"DANE, DNP Colombia, Banco Mundial","codigo_iris":"",
 "valor_referencia":"LPM Colombia per cápita mensual 2023: ~$372.000 COP",
 "ejemplo_programa":"Red Unidos / Más Familias en Acción — Colombia","limitaciones":"Requiere muestra representativa; sensible a la definición de la línea de pobreza.",
 "idioma":"ES"},

{"id":"EMP013","nombre":"Experiencia de búsqueda de empleo y barreras percibidas (cualitativo)",
 "nombre_en":"Job search experience and perceived barriers (qualitative)",
 "descripcion":"Narrativas de participantes sobre su experiencia en el mercado laboral: barreras encontradas (discriminación, falta de experiencia, requisitos), estrategias de búsqueda y expectativas. Complementa datos cuantitativos de inserción.",
 "tipo":"resultado","sector":"Empleo e ingresos","subsector":"Inserción laboral",
 "nivel_medicion":"individual","enfoque":"cualitativo","unidad":"n/a",
 "formula":"Análisis temático de entrevistas; categorías: tipos de barrera, estrategias usadas, cambios en percepción de empleabilidad",
 "metodo_recoleccion":"entrevista","instrumento_sugerido":"Guía de entrevista semiestructurada (15–45 min)",
 "frecuencia":"semestral","momento_medicion":"evaluacion_final","tipo_linea_base":"cualitativa",
 "diseno_comparacion":"participativo",
 "desagregacion_recomendada":"sexo, grupo etario, zona, pertenencia a grupo vulnerable",
 "ods_meta":"ODS 8.5","fuente_referencia":"OIT — Barreras de Empleo; JPAL — Job Training RCTs","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"Evaluaciones cualitativas — Youth Employment Network",
 "limitaciones":"No generalizable estadísticamente; requiere analistas con experiencia en investigación cualitativa.",
 "idioma":"ES"},

# ─────────────────────────────────────────────────────────────────────────────
# SECTOR: GÉNERO E IGUALDAD
# ─────────────────────────────────────────────────────────────────────────────

{"id":"GEN001","nombre":"Número de mujeres que participaron en el programa",
 "nombre_en":"Number of women participating in the programme",
 "descripcion":"Total de mujeres que se inscribieron y participaron activamente en el programa. Primer indicador de igualdad de género en la cobertura.",
 "tipo":"producto","sector":"Género e igualdad","subsector":"Empoderamiento de la mujer",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"n",
 "formula":"Σ participantes mujeres",
 "metodo_recoleccion":"registro_administrativo","instrumento_sugerido":"Base de datos de participantes desagregada por sexo",
 "frecuencia":"mensual","momento_medicion":"seguimiento","tipo_linea_base":"no_aplica",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"grupo etario, zona, etnia, nivel educativo, condición de vulnerabilidad",
 "ods_meta":"ODS 5","fuente_referencia":"ONU Mujeres, CEDAW","codigo_iris":"PI9460",
 "valor_referencia":"","ejemplo_programa":"Todos los programas con enfoque de género — ONU Mujeres",
 "limitaciones":"La participación no implica empoderamiento real; requiere indicadores de resultado complementarios.",
 "idioma":"ES"},

{"id":"GEN002","nombre":"Brecha de género en la participación del programa (ratio M:H)",
 "nombre_en":"Gender participation gap in programme (F:M ratio)",
 "descripcion":"Ratio entre el porcentaje de mujeres y hombres participantes en el programa, relativo a su proporción en la población objetivo. Mide la equidad de acceso.",
 "tipo":"producto","sector":"Género e igualdad","subsector":"Acceso equitativo",
 "nivel_medicion":"sistema","enfoque":"cuantitativo","unidad":"ratio",
 "formula":"(% mujeres participantes / % mujeres en población objetivo) / (% hombres participantes / % hombres en población objetivo)",
 "metodo_recoleccion":"registro_administrativo","instrumento_sugerido":"Base de datos de participantes + datos censo/DANE",
 "frecuencia":"anual","momento_medicion":"seguimiento","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"zona, etnia, grupo etario",
 "ods_meta":"ODS 5.b","fuente_referencia":"ONU Mujeres, PNUD GII","codigo_iris":"",
 "valor_referencia":"Ratio = 1: paridad perfecta; <1: subrepresentación de mujeres",
 "ejemplo_programa":"Gender Equality Marker — OCDE/DAC",
 "limitaciones":"El ratio no captura calidad de participación ni barreras para acceder.",
 "idioma":"ES"},

{"id":"GEN003","nombre":"Porcentaje de mujeres con mayor control sobre sus ingresos",
 "nombre_en":"Percentage of women with increased control over household income",
 "descripcion":"Proporción de mujeres participantes que reportan tener más decisión sobre el uso de sus ingresos propios o del hogar después del programa. Indicador de empoderamiento económico.",
 "tipo":"resultado","sector":"Género e igualdad","subsector":"Empoderamiento económico",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Mujeres con mayor control declarado / Total mujeres encuestadas) × 100",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"Women's Empowerment in Agriculture Index (WEAI) — módulo de agencia; o encuesta adaptada",
 "frecuencia":"semestral","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"grupo etario, zona, nivel educativo, estado civil",
 "ods_meta":"ODS 5.a","fuente_referencia":"ONU Mujeres, WEAI — IFPRI","codigo_iris":"OD7910",
 "valor_referencia":"","ejemplo_programa":"CARE Women's Economic Empowerment; ONU Mujeres Colombia",
 "limitaciones":"Medida de autoreporte; el 'control' puede estar influido por normas sociales que dificultan reconocerlo.",
 "idioma":"ES"},

{"id":"GEN004","nombre":"Tasa de prevalencia de violencia basada en género (últimos 12 meses, %)",
 "nombre_en":"Prevalence rate of gender-based violence (past 12 months, %)",
 "descripcion":"Proporción de mujeres que reportan haber experimentado algún tipo de violencia (física, psicológica, sexual, económica) por su pareja o ex-pareja en los últimos 12 meses. Indicador de resultado-impacto.",
 "tipo":"impacto","sector":"Género e igualdad","subsector":"Violencia basada en género",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Mujeres con ≥1 acto de VBG en últimos 12 meses / Total mujeres encuestadas) × 100",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"WHO Multi-Country Study questionnaire / ENVIGMU Colombia (DANE)",
 "frecuencia":"anual","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"tipo de violencia, grupo etario, zona, etnia, nivel educativo",
 "ods_meta":"ODS 5.2","fuente_referencia":"OMS, ONU Mujeres, DANE-ENVIGMU Colombia","codigo_iris":"OD7911",
 "valor_referencia":"Colombia: ~34% VBG física/sexual por pareja (ENVIGMU 2019)",
 "ejemplo_programa":"Programa Entornos Seguros — ONU Mujeres/Colombia",
 "limitaciones":"Subnotificación severa; encuesta requiere protocolos de seguridad para las encuestadas; definiciones varían.",
 "idioma":"ES"},

{"id":"GEN005","nombre":"Porcentaje de mujeres con participación activa en espacios de toma de decisiones comunitarios",
 "nombre_en":"Percentage of women actively participating in community decision-making",
 "descripcion":"Proporción de mujeres que participaron en al menos una reunión, asamblea o espacio de decisión comunitaria en los últimos 3 meses. Indicador de empoderamiento y agencia social.",
 "tipo":"resultado","sector":"Género e igualdad","subsector":"Liderazgo y participación política",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Mujeres con ≥1 participación en espacio de decisión / Total mujeres encuestadas) × 100",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"Encuesta de participación ciudadana / social",
 "frecuencia":"semestral","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"grupo etario, zona, nivel educativo, etnia",
 "ods_meta":"ODS 5.5","fuente_referencia":"ONU Mujeres, IPU, PNUD","codigo_iris":"OD7912",
 "valor_referencia":"","ejemplo_programa":"Programa Mujeres Líderes — ONU Mujeres Colombia",
 "limitaciones":"Participar en un espacio no equivale a tener influencia real en las decisiones.",
 "idioma":"ES"},

{"id":"GEN006","nombre":"Puntaje de agencia de las mujeres (escala validada de empoderamiento)",
 "nombre_en":"Women's agency score (validated empowerment scale)",
 "descripcion":"Puntaje compuesto en una escala validada de agencia femenina que evalúa capacidad de tomar decisiones, moverse libremente, acceder a recursos y rechazar demandas no deseadas.",
 "tipo":"resultado","sector":"Género e igualdad","subsector":"Empoderamiento de la mujer",
 "nivel_medicion":"individual","enfoque":"mixto","unidad":"puntaje",
 "formula":"Puntaje WEAI (5 componentes) / adaptación de GS Scores (Gender Score)",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"WEAI — Women's Empowerment in Agriculture Index (IFPRI); Women Empowerment Index (USAID)",
 "frecuencia":"anual","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"zona, grupo etario, nivel educativo, tipo de hogar",
 "ods_meta":"ODS 5","fuente_referencia":"IFPRI WEAI, ONU Mujeres, USAID","codigo_iris":"OD7913",
 "valor_referencia":"WEAI: puntaje 0–1; 0.8+ = alto empoderamiento",
 "ejemplo_programa":"CARE Gender Equity Marker; USAID Women in Development",
 "limitaciones":"WEAI fue diseñado para contextos agrícolas; requiere adaptación para contextos urbanos.",
 "idioma":"ES"},

{"id":"GEN007","nombre":"Testimonios sobre cambios en relaciones de poder y autonomía (cualitativo)",
 "nombre_en":"Testimonies on changes in power relations and autonomy (qualitative)",
 "descripcion":"Relatos de mujeres participantes sobre cambios en cómo toman decisiones, cómo son tratadas en el hogar y la comunidad, y si sienten mayor control sobre su vida. Captura dimensiones del empoderamiento que las escalas no logran medir.",
 "tipo":"resultado","sector":"Género e igualdad","subsector":"Empoderamiento de la mujer",
 "nivel_medicion":"individual","enfoque":"cualitativo","unidad":"n/a",
 "formula":"Análisis de género narrativo; categorías: decisiones sobre cuerpo, movilidad, trabajo, vida familiar",
 "metodo_recoleccion":"entrevista","instrumento_sugerido":"Entrevistas semiestructuradas con guía de género (en privado, por encuestadora mujer)",
 "frecuencia":"semestral","momento_medicion":"evaluacion_final","tipo_linea_base":"cualitativa",
 "diseno_comparacion":"participativo",
 "desagregacion_recomendada":"grupo etario, zona, condición (sobreviviente VBG, jefa de hogar, etc.)",
 "ods_meta":"ODS 5","fuente_referencia":"ONU Mujeres — Gender-Responsive Evaluation; Most Significant Change","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"CARE Women's Empowerment evaluations",
 "limitaciones":"Entorno de confianza es crítico para la honestidad de los testimonios; riesgo de sesgo de complacencia.",
 "idioma":"ES"},

{"id":"GEN008","nombre":"Porcentaje de carga de trabajo doméstico no remunerado asumida por mujeres (%)",
 "nombre_en":"Percentage of unpaid domestic work carried by women",
 "descripcion":"Proporción de las horas de trabajo doméstico no remunerado (cuidado, labores del hogar, crianza) que asumen las mujeres del hogar respecto al total de horas dedicadas por todos los miembros adultos.",
 "tipo":"impacto","sector":"Género e igualdad","subsector":"Trabajo no remunerado y cuidado",
 "nivel_medicion":"hogar","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Horas trabajo no remunerado mujeres / Horas totales trabajo no remunerado hogar) × 100",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"Encuesta de Uso del Tiempo (ENUT-DANE Colombia)",
 "frecuencia":"anual","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"zona, nivel educativo, número de hijos, tipo de hogar",
 "ods_meta":"ODS 5.4","fuente_referencia":"DANE-ENUT Colombia, ONU Mujeres","codigo_iris":"",
 "valor_referencia":"Colombia: ~75–80% trabajo no remunerado es asumido por mujeres (ENUT 2016–17)",
 "ejemplo_programa":"Política Nacional de Cuidado — Colombia 2023",
 "limitaciones":"Encuesta de Uso del Tiempo es costosa; no se aplica frecuentemente a nivel local.",
 "idioma":"ES"},

# ─────────────────────────────────────────────────────────────────────────────
# SECTOR: INFANCIA Y DERECHOS
# ─────────────────────────────────────────────────────────────────────────────

{"id":"INF001","nombre":"Porcentaje de niños registrados con documento de identidad al nacer",
 "nombre_en":"Percentage of children registered with identity document at birth",
 "descripcion":"Proporción de nacidos vivos con registro civil (y tarjeta de identidad para mayores de 7 años) emitido. Indicador fundamental de acceso a derechos.",
 "tipo":"resultado","sector":"Infancia y derechos","subsector":"Registro e identidad",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Niños con registro civil / Nacidos vivos registrados en RUAF) × 100",
 "metodo_recoleccion":"datos_secundarios","instrumento_sugerido":"DANE-RUAF / RNEC Colombia",
 "frecuencia":"anual","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"zona, etnia, municipio",
 "ods_meta":"ODS 16.9","fuente_referencia":"UNICEF, DANE, RNEC Colombia","codigo_iris":"",
 "valor_referencia":"Colombia: ~97% de nacimientos registrados (DANE 2022)",
 "ejemplo_programa":"Registro Universal al Nacer — UNICEF/RNEC",
 "limitaciones":"Existen subregistros en comunidades indígenas y zonas rurales remotas.",
 "idioma":"ES"},

{"id":"INF002","nombre":"Porcentaje de niños con desarrollo adecuado para su edad (escala EAD / Denver)",
 "nombre_en":"Percentage of children with age-appropriate development (developmental screener)",
 "descripcion":"Proporción de niños que muestran desarrollo adecuado en las dimensiones cognitiva, motora, comunicación y socio-afectiva para su grupo de edad según tamizaje estandarizado.",
 "tipo":"resultado","sector":"Infancia y derechos","subsector":"Desarrollo infantil temprano",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Niños con desarrollo adecuado por área / Total niños evaluados en el grupo etario) × 100",
 "metodo_recoleccion":"observacion_directa","instrumento_sugerido":"Escala Abreviada de Desarrollo (EAD-1) Colombia / Denver II / ASQ-3",
 "frecuencia":"semestral","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"grupo etario (0–12m, 13–24m, 25–36m), sexo, zona, área del desarrollo",
 "ods_meta":"ODS 4.2","fuente_referencia":"ICBF Colombia, UNICEF, OPS","codigo_iris":"OD3951",
 "valor_referencia":"","ejemplo_programa":"De Cero a Siempre / CDI — ICBF Colombia",
 "limitaciones":"Tamizajes detectan riesgo, no diagnóstico; requieren personal capacitado en su aplicación.",
 "idioma":"ES"},

{"id":"INF003","nombre":"Tasa de trabajo infantil (%)",
 "nombre_en":"Child labour rate (%)",
 "descripcion":"Proporción de niños de 5–17 años que realizan trabajo infantil (trabajo peligroso o que interfiere con la escolaridad), según definición OIT. Indicador de impacto sobre protección de derechos.",
 "tipo":"impacto","sector":"Infancia y derechos","subsector":"Protección y trabajo infantil",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Niños 5–17 en trabajo infantil / Total niños 5–17) × 100",
 "metodo_recoleccion":"datos_secundarios","instrumento_sugerido":"DANE-ENTI (Encuesta Nacional de Trabajo Infantil) / GEIH módulo trabajo infantil",
 "frecuencia":"anual","momento_medicion":"impacto","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"sexo, grupo etario, zona, rama de actividad",
 "ods_meta":"ODS 8.7","fuente_referencia":"DANE-ENTI, OIT, UNICEF","codigo_iris":"OD3952",
 "valor_referencia":"Colombia: ~5.8% trabajo infantil (ENTI 2022); Meta: <1% al 2025",
 "ejemplo_programa":"Política Pública de Erradicación del Trabajo Infantil — ICBF",
 "limitaciones":"Subregistro en zonas rurales y en trabajo doméstico no remunerado; la ENTI se aplica cada 2–3 años.",
 "idioma":"ES"},

{"id":"INF004","nombre":"Porcentaje de niños que experimentan prácticas de crianza positiva",
 "nombre_en":"Percentage of children experiencing positive parenting practices",
 "descripcion":"Proporción de niños cuyos cuidadores principales reportan usar métodos de disciplina positiva y no violenta. Indicador de resultado en programas de crianza y protección infantil.",
 "tipo":"resultado","sector":"Infancia y derechos","subsector":"Crianza y cuidado",
 "nivel_medicion":"hogar","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Cuidadores que usan solo disciplina positiva / Total cuidadores encuestados) × 100",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"UNICEF MICS módulo disciplina infantil / Cuestionario de Crianza Parental",
 "frecuencia":"semestral","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"sexo del cuidador, zona, grupo etario del niño, nivel educativo",
 "ods_meta":"ODS 16.2","fuente_referencia":"UNICEF MICS, Save the Children","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"Crianza con Amor — ICBF Colombia; Positive Parenting Program (Triple P)",
 "limitaciones":"Alto sesgo de deseabilidad social; los cuidadores evitan reportar prácticas punitivas.",
 "idioma":"ES"},

{"id":"INF005","nombre":"Número de casos de violencia infantil reportados y atendidos",
 "nombre_en":"Number of child abuse cases reported and attended",
 "descripcion":"Total de casos de violencia física, psicológica, sexual o negligencia hacia niños que fueron reportados al sistema de protección y recibieron atención en el período.",
 "tipo":"producto","sector":"Infancia y derechos","subsector":"Protección y violencia",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"n",
 "formula":"Σ casos reportados + Σ casos con atención registrada",
 "metodo_recoleccion":"registro_administrativo","instrumento_sugerido":"ICBF SIPOD / Fiscalía / Comisaría de Familia",
 "frecuencia":"mensual","momento_medicion":"seguimiento","tipo_linea_base":"no_aplica",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"sexo, grupo etario, tipo de violencia, agresor, zona",
 "ods_meta":"ODS 16.2","fuente_referencia":"ICBF Colombia, Save the Children","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"Sistemas de Alerta Temprana ICBF Colombia",
 "limitaciones":"El número de casos reportados puede aumentar por mejora en la denuncia, no necesariamente por más violencia. Subregistro alto.",
 "idioma":"ES"},

{"id":"INF006","nombre":"Puntaje de bienestar subjetivo de niños y adolescentes",
 "nombre_en":"Children's subjective wellbeing score",
 "descripcion":"Puntaje promedio en escala de bienestar subjetivo adaptada para niños (Children's Worlds / ISCWeB). Mide satisfacción con la vida, relaciones, escuela y hogar desde la perspectiva del propio niño.",
 "tipo":"resultado","sector":"Infancia y derechos","subsector":"Bienestar infantil",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"puntaje",
 "formula":"Puntaje promedio en escala validada (Children's Worlds — 11 ítems, 0–10)",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"Children's Worlds International Survey (ISCWeB) — versión ES validada",
 "frecuencia":"anual","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"sexo, grupo etario (8–12 / 13–17 años), zona",
 "ods_meta":"ODS 3.4","fuente_referencia":"ISCWeB — Rees et al.; UNICEF","codigo_iris":"",
 "valor_referencia":"Puntaje global Children's Worlds: ~8.0/10 en promedio internacional",
 "ejemplo_programa":"Children's Worlds Colombia — ICBF/Rees",
 "limitaciones":"Comprensión de las preguntas varía con la edad; instrumento debe adaptarse a nivel de lectura del niño.",
 "idioma":"ES"},

{"id":"INF007","nombre":"Porcentaje de niños con seguridad alimentaria en el hogar",
 "nombre_en":"Percentage of children in food-secure households",
 "descripcion":"Proporción de niños que viven en hogares clasificados como con seguridad alimentaria (sin restricción en cantidad ni calidad de alimentos) según escala ELCSA.",
 "tipo":"resultado","sector":"Infancia y derechos","subsector":"Seguridad alimentaria infantil",
 "nivel_medicion":"hogar","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Hogares con niños clasificados ELCSA 'Seguro' / Total hogares con niños) × 100",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"ELCSA — Escala Latinoamericana y Caribeña de Seguridad Alimentaria",
 "frecuencia":"semestral","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"zona, nivel socioeconómico, jefatura femenina, departamento",
 "ods_meta":"ODS 2.1","fuente_referencia":"FAO ELCSA, ICBF Colombia","codigo_iris":"",
 "valor_referencia":"Colombia: ~42% hogares con inseguridad alimentaria leve/moderada/severa (ENSIN 2015)",
 "ejemplo_programa":"Programa PAE / De Cero a Siempre — ICBF Colombia",
 "limitaciones":"ELCSA mide percepción del hogar, no consumo real; la escala tiene respuestas binarias que pueden perder matices.",
 "idioma":"ES"},

{"id":"INF008","nombre":"Percepción de las y los niños sobre su participación y ser escuchados (cualitativo)",
 "nombre_en":"Children's perception of participation and being heard (qualitative)",
 "descripcion":"Testimonios de niños y adolescentes sobre si sienten que sus opiniones son tomadas en cuenta en el hogar, la escuela y la comunidad. Captura la dimensión de agencia infantil.",
 "tipo":"resultado","sector":"Infancia y derechos","subsector":"Participación infantil",
 "nivel_medicion":"individual","enfoque":"cualitativo","unidad":"n/a",
 "formula":"Análisis temático de grupos focales con niños; categorías: voz en hogar, escuela, comunidad, programa",
 "metodo_recoleccion":"grupo_focal","instrumento_sugerido":"Guía de grupo focal con niños (adaptar lenguaje por edad; máx 8 personas; facilitador entrenado)",
 "frecuencia":"semestral","momento_medicion":"evaluacion_final","tipo_linea_base":"cualitativa",
 "diseno_comparacion":"participativo",
 "desagregacion_recomendada":"grupo etario (5–9 / 10–14 / 15–17), sexo, zona",
 "ods_meta":"ODS 16.7","fuente_referencia":"Convención sobre los Derechos del Niño (CDN) Art. 12; UNICEF","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"Participatory Monitoring with Children — Save the Children",
 "limitaciones":"Grupos focales con niños requieren consentimiento de padres y protocolos de salvaguarda; los niños más pequeños necesitan herramientas lúdicas.",
 "idioma":"ES"},

]

with open(OUT, "a", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=FIELDS, extrasaction="ignore")
    writer.writerows(INDICATORS)

print(f"Batch 2 agregado: {len(INDICATORS)} indicadores en {OUT}")
