"""
Batch 3 — Seguridad alimentaria + Medio ambiente + Gobernanza +
           Desarrollo económico + Vivienda + Inclusión financiera +
           Paz/Reconciliación + Capital social (~150 indicadores)
Añade al CSV existente.
"""
import csv, os

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT  = os.path.join(BASE, "metadata", "indicadores.csv")

FIELDS = [
    "id","nombre","nombre_en","descripcion",
    "tipo","sector","subsector",
    "nivel_medicion","enfoque","unidad","formula",
    "metodo_recoleccion","instrumento_sugerido",
    "frecuencia","momento_medicion","tipo_linea_base","diseno_comparacion",
    "desagregacion_recomendada","ods_meta","fuente_referencia","codigo_iris",
    "valor_referencia","ejemplo_programa","limitaciones","idioma",
]

INDICATORS = [

# ─────────────────────────────────────────────────────────────────────────────
# SECTOR: SEGURIDAD ALIMENTARIA Y NUTRICIÓN
# ─────────────────────────────────────────────────────────────────────────────

{"id":"ALI001","nombre":"Puntaje de diversidad alimentaria del hogar (PDAH)",
 "nombre_en":"Household Dietary Diversity Score (HDDS)",
 "descripcion":"Número de grupos de alimentos consumidos por el hogar en las últimas 24 horas. Proxy simple y validado de la calidad nutricional de la dieta.",
 "tipo":"resultado","sector":"Seguridad alimentaria","subsector":"Diversidad y calidad alimentaria",
 "nivel_medicion":"hogar","enfoque":"cuantitativo","unidad":"puntaje",
 "formula":"Σ grupos de alimentos consumidos (de 12 posibles) en las últimas 24h",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"FANTA HDDS — questionnaire (FAO/USAID)",
 "frecuencia":"semestral","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"zona, nivel socioeconómico, jefatura femenina, temporada",
 "ods_meta":"ODS 2.1","fuente_referencia":"FAO FANTA Guidelines, IFPRI","codigo_iris":"OD3960",
 "valor_referencia":"PDAH ≥6 = diversidad adecuada (FAO); promedio comunidades rurales Colombia: ~5–6",
 "ejemplo_programa":"Programas de seguridad alimentaria FAO Colombia / MADR",
 "limitaciones":"No distingue cantidad ni calidad nutricional específica; sensible al recall de 24h.",
 "idioma":"ES"},

{"id":"ALI002","nombre":"Puntuación de consumo de alimentos (PCA / FCS)",
 "nombre_en":"Food Consumption Score (FCS)",
 "descripcion":"Indicador compuesto del PMA que combina frecuencia de consumo (7 días) de 8 grupos de alimentos con pesos nutricionales. Clasifica hogares en consumo 'pobre', 'límite' o 'aceptable'.",
 "tipo":"resultado","sector":"Seguridad alimentaria","subsector":"Consumo y calidad alimentaria",
 "nivel_medicion":"hogar","enfoque":"cuantitativo","unidad":"puntaje",
 "formula":"Σ (frecuencia de consumo × peso nutricional del grupo) para 8 grupos en 7 días",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"WFP Food Consumption Score questionnaire",
 "frecuencia":"semestral","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"zona, nivel socioeconómico, etnia, temporada",
 "ods_meta":"ODS 2.1","fuente_referencia":"PMA/WFP FCS Technical Guidance","codigo_iris":"OD3961",
 "valor_referencia":"FCS <21: pobre; 21–35: límite; >35: aceptable",
 "ejemplo_programa":"Monitoreo de seguridad alimentaria — PMA Colombia",
 "limitaciones":"El recall de 7 días tiene variación estacional; los pesos nutricionales son fijos y pueden no reflejar contexto local.",
 "idioma":"ES"},

{"id":"ALI003","nombre":"Escala de inseguridad alimentaria basada en experiencias (FIES)",
 "nombre_en":"Food Insecurity Experience Scale (FIES)",
 "descripcion":"Escala de 8 preguntas (FAO/Gallup) sobre experiencias de inseguridad alimentaria en el hogar durante el último año. Es el indicador oficial del ODS 2.1.2.",
 "tipo":"resultado","sector":"Seguridad alimentaria","subsector":"Inseguridad alimentaria",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"puntaje",
 "formula":"Modelo Rasch sobre 8 ítems dicotómicos; produce puntaje y clasifica severidad (leve/moderada/severa)",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"FIES — FAO (módulo de 8 preguntas, validado en español)",
 "frecuencia":"anual","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"zona, sexo del responsable del hogar, nivel educativo",
 "ods_meta":"ODS 2.1","fuente_referencia":"FAO FIES — Ballard et al. (2013)","codigo_iris":"OD3962",
 "valor_referencia":"Colombia: ~53% inseguridad alimentaria (FIES 2022, moderada+severa)",
 "ejemplo_programa":"Encuesta Nacional de Seguridad Alimentaria — FAO/DANE",
 "limitaciones":"Requiere calibración estadística Rasch para comparabilidad; no captura causas.",
 "idioma":"ES"},

{"id":"ALI004","nombre":"Porcentaje de niños menores de 5 años con desnutrición aguda (SAM/MAM)",
 "nombre_en":"Percentage of children under 5 with acute malnutrition (SAM/MAM)",
 "descripcion":"Proporción de niños menores de 5 años con bajo peso para la talla (< -2 DE para MAM; < -3 DE para SAM). Indicador de emergencia nutricional.",
 "tipo":"impacto","sector":"Seguridad alimentaria","subsector":"Nutrición infantil",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Niños <5 con P/T < -2 DE / Total niños <5 medidos) × 100",
 "metodo_recoleccion":"observacion_directa","instrumento_sugerido":"Balanza + cinta MUAC + tablas WHO + SISVAN",
 "frecuencia":"semestral","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"sexo, grupo etario, zona, etnia",
 "ods_meta":"ODS 2.2","fuente_referencia":"OMS, UNICEF, ICBF-ENSIN Colombia","codigo_iris":"OD3963",
 "valor_referencia":"Umbral de emergencia OMS: >15% desnutrición aguda",
 "ejemplo_programa":"CMAM Colombia — MSPS/UNICEF/WFP",
 "limitaciones":"Medición puntual no captura estacionalidad; requiere personal entrenado en antropometría.",
 "idioma":"ES"},

{"id":"ALI005","nombre":"Rendimiento agrícola promedio de cultivos principales (kg/ha)",
 "nombre_en":"Average crop yield for main crops (kg/ha)",
 "descripcion":"Producción media por hectárea de los principales cultivos de los beneficiarios del programa. Indicador de resultado de programas de seguridad alimentaria con enfoque productivo.",
 "tipo":"resultado","sector":"Seguridad alimentaria","subsector":"Producción agrícola",
 "nivel_medicion":"hogar","enfoque":"cuantitativo","unidad":"kg/ha",
 "formula":"Producción total (kg) / Área sembrada (ha) por cultivo",
 "metodo_recoleccion":"observacion_directa","instrumento_sugerido":"Aforo de cosecha / encuesta de producción agrícola",
 "frecuencia":"anual","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"tipo de cultivo, zona, acceso a riego, uso de semilla mejorada",
 "ods_meta":"ODS 2.3","fuente_referencia":"FAO, MADR Colombia, UPRA","codigo_iris":"",
 "valor_referencia":"Colombia maíz: ~2–3 t/ha; papa: ~20–25 t/ha; arroz: ~6–7 t/ha",
 "ejemplo_programa":"Programa PESA-FAO Colombia / Agricultura Familiar MADR",
 "limitaciones":"Alta variabilidad por condiciones climáticas y de suelo; el aforo requiere visita de campo.",
 "idioma":"ES"},

# ─────────────────────────────────────────────────────────────────────────────
# SECTOR: MEDIO AMBIENTE Y CLIMA
# ─────────────────────────────────────────────────────────────────────────────

{"id":"MA001","nombre":"Hectáreas restauradas o reforestadas",
 "nombre_en":"Hectares restored or reforested",
 "descripcion":"Total de hectáreas intervenidas con acciones de restauración ecológica o reforestación en el período. Indicador de producto de programas de restauración ambiental.",
 "tipo":"producto","sector":"Medio ambiente","subsector":"Restauración de ecosistemas",
 "nivel_medicion":"sistema","enfoque":"cuantitativo","unidad":"ha",
 "formula":"Σ hectáreas con plantación establecida o restauración activa",
 "metodo_recoleccion":"observacion_directa","instrumento_sugerido":"Verificación de campo + mapas satelitales (Sentinel/Planet)",
 "frecuencia":"anual","momento_medicion":"seguimiento","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"tipo de ecosistema, especie plantada, zona, cuenca hidrográfica",
 "ods_meta":"ODS 15.2","fuente_referencia":"MADS Colombia, IAVH, FAO","codigo_iris":"OD7901",
 "valor_referencia":"Meta Bosques y Biodiversidad Colombia: 180.000 ha/año restauradas",
 "ejemplo_programa":"Acuerdo Climático Colombia — Restauración Nacional",
 "limitaciones":"Área plantada no garantiza supervivencia de árboles (requiere monitoreo a 3–5 años).",
 "idioma":"ES"},

{"id":"MA002","nombre":"Toneladas de CO2 equivalente reducidas o capturadas",
 "nombre_en":"Tonnes of CO2 equivalent reduced or sequestered",
 "descripcion":"Reducción neta de emisiones de GEI (mitigación) o absorción de carbono (secuestro) atribuibles al programa, en toneladas de CO2 equivalente.",
 "tipo":"impacto","sector":"Medio ambiente","subsector":"Cambio climático y mitigación",
 "nivel_medicion":"sistema","enfoque":"cuantitativo","unidad":"tCO2e",
 "formula":"Emisiones_BAU − Emisiones_con_proyecto (metodología IPCC o Gold Standard)",
 "metodo_recoleccion":"revision_documental","instrumento_sugerido":"Inventario de GEI + modelos de carbono (IPCC Tier 2); verificación Gold Standard / VCS",
 "frecuencia":"anual","momento_medicion":"impacto","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"fuente de emisión, actividad del programa, tipo de GEI",
 "ods_meta":"ODS 13.2","fuente_referencia":"IPCC, Gold Standard, VCS Verra, IDEAM Colombia","codigo_iris":"OD7902",
 "valor_referencia":"Precio sombra carbono Colombia: USD 5–15/tCO2e (mercado voluntario 2023)",
 "ejemplo_programa":"Proyectos REDD+ Colombia / Fondo Acción",
 "limitaciones":"El cálculo requiere modelación especializada; el carbono secuestrado puede revertirse (riesgo de reversión).",
 "idioma":"ES"},

{"id":"MA003","nombre":"Porcentaje de hogares que adoptan prácticas de gestión sostenible de residuos",
 "nombre_en":"Percentage of households adopting sustainable waste management practices",
 "descripcion":"Proporción de hogares que separan residuos en la fuente, hacen compostaje o reducen residuos sólidos como resultado del programa.",
 "tipo":"resultado","sector":"Medio ambiente","subsector":"Residuos sólidos",
 "nivel_medicion":"hogar","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Hogares con práctica verificada de separación o compostaje / Total hogares) × 100",
 "metodo_recoleccion":"observacion_directa","instrumento_sugerido":"Visita domiciliaria + lista de chequeo de prácticas",
 "frecuencia":"semestral","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"zona, tipo de práctica, nivel educativo",
 "ods_meta":"ODS 12.5","fuente_referencia":"MADS Colombia, ONU Ambiente","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"Basura Cero — Alcaldía Bogotá / programas comunitarios",
 "limitaciones":"La observación puede generar el efecto Hawthorne; la práctica puede no ser sostenida.",
 "idioma":"ES"},

{"id":"MA004","nombre":"Porcentaje de comunidades con acceso a agua potable de calidad",
 "nombre_en":"Percentage of communities with access to quality drinking water",
 "descripcion":"Proporción de comunidades donde las fuentes de agua usadas para consumo cumplen estándares mínimos de calidad (ausencia de E. coli, turbidez aceptable). Indicador de resultado en WASH y salud ambiental.",
 "tipo":"resultado","sector":"Medio ambiente","subsector":"Agua y saneamiento",
 "nivel_medicion":"comunidad","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Comunidades con agua de calidad / Total comunidades intervenidas) × 100",
 "metodo_recoleccion":"observacion_directa","instrumento_sugerido":"Muestras de agua + kit de prueba microbiológica + IRCA (Colombia)",
 "frecuencia":"semestral","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"fuente de agua, zona, municipio, temporada (lluvia/seca)",
 "ods_meta":"ODS 6.1","fuente_referencia":"MAVDT/MADS Colombia, SIVICAP-INS, OPS","codigo_iris":"OD7903",
 "valor_referencia":"Meta ODS 6.1: acceso universal a agua potable gestionada de forma segura al 2030",
 "ejemplo_programa":"Programa Agua Para la Prosperidad — MinVivienda Colombia",
 "limitaciones":"La calidad del agua varía estacionalmente; el IRCA mide puntualmente, no de forma continua.",
 "idioma":"ES"},

{"id":"MA005","nombre":"Percepción comunitaria de cambios en el entorno ambiental (cualitativo)",
 "nombre_en":"Community perception of environmental changes (qualitative)",
 "descripcion":"Relatos de comunidades sobre cambios observados en el estado del ambiente local (ríos, bosques, suelo, aire) antes y después del programa. Captura conocimiento ecológico local.",
 "tipo":"resultado","sector":"Medio ambiente","subsector":"Gestión ambiental comunitaria",
 "nivel_medicion":"comunidad","enfoque":"cualitativo","unidad":"n/a",
 "formula":"Mapeo participativo de recursos + análisis de cambio ambiental percibido por la comunidad",
 "metodo_recoleccion":"participativo","instrumento_sugerido":"Mapa de recursos naturales comunitario + grupo focal (10–15 personas)",
 "frecuencia":"anual","momento_medicion":"evaluacion_final","tipo_linea_base":"cualitativa",
 "diseno_comparacion":"participativo",
 "desagregacion_recomendada":"género, generación (adultos vs. jóvenes), vereda/barrio",
 "ods_meta":"ODS 15.1","fuente_referencia":"FAO NRSA, IIED Participatory Learning and Action","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"Monitoreo comunitario de biodiversidad — WWF Colombia",
 "limitaciones":"La percepción puede diferir de las mediciones técnicas; sesgos por narrativas dominantes en la comunidad.",
 "idioma":"ES"},

# ─────────────────────────────────────────────────────────────────────────────
# SECTOR: GOBERNANZA Y PARTICIPACIÓN CIUDADANA
# ─────────────────────────────────────────────────────────────────────────────

{"id":"GOB001","nombre":"Número de personas capacitadas en participación ciudadana y derechos",
 "nombre_en":"Number of people trained in civic participation and rights",
 "descripcion":"Total de ciudadanos que completaron procesos de formación en derechos, mecanismos de participación (veeduría, control social, consulta previa) en el período.",
 "tipo":"producto","sector":"Gobernanza","subsector":"Capacitación ciudadana",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"n",
 "formula":"Σ participantes que completaron ≥1 módulo de formación ciudadana",
 "metodo_recoleccion":"registro_administrativo","instrumento_sugerido":"Lista de asistencia + pre-post prueba de conocimientos",
 "frecuencia":"semestral","momento_medicion":"seguimiento","tipo_linea_base":"no_aplica",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"sexo, grupo etario, zona, etnia",
 "ods_meta":"ODS 16.7","fuente_referencia":"DNP Colombia, Transparencia Internacional","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"Escuelas de Gobierno — DNP / DAP Colombia",
 "limitaciones":"La capacitación no garantiza participación efectiva posterior.",
 "idioma":"ES"},

{"id":"GOB002","nombre":"Porcentaje de ciudadanos que reportan confianza en instituciones públicas",
 "nombre_en":"Percentage of citizens reporting trust in public institutions",
 "descripcion":"Proporción de ciudadanos que tienen confianza en al menos 3 instituciones públicas clave (alcaldía, consejo, policía, justicia). Indicador de resultado sobre capital institucional.",
 "tipo":"resultado","sector":"Gobernanza","subsector":"Confianza institucional",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Ciudadanos con confianza en ≥3 instituciones / Total encuestados) × 100",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"Encuesta de Cultura Política (DANE) / Latinobarómetro / encuesta de percepción local",
 "frecuencia":"anual","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"sexo, zona, grupo etario, nivel educativo",
 "ods_meta":"ODS 16.6","fuente_referencia":"DANE Cultura Política, Latinobarómetro, Observatorio Democracia","codigo_iris":"",
 "valor_referencia":"Colombia: ~21% confianza en instituciones (Latinobarómetro 2023)",
 "ejemplo_programa":"Confianza Ciudadana — Alcaldía Bogotá",
 "limitaciones":"La confianza es multidimensional y volátil; un evento puntual puede alterarla significativamente.",
 "idioma":"ES"},

{"id":"GOB003","nombre":"Porcentaje de presupuesto público ejecutado con participación ciudadana",
 "nombre_en":"Percentage of public budget executed with citizen participation",
 "descripcion":"Proporción del presupuesto de inversión municipal o departamental que fue priorizado o monitoreado con mecanismos de participación ciudadana (presupuesto participativo, cabildos).",
 "tipo":"resultado","sector":"Gobernanza","subsector":"Transparencia y rendición de cuentas",
 "nivel_medicion":"sistema","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Presupuesto con participación ciudadana / Presupuesto total de inversión) × 100",
 "metodo_recoleccion":"revision_documental","instrumento_sugerido":"POT / POAI / informes de presupuesto participativo",
 "frecuencia":"anual","momento_medicion":"impacto","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"sector de inversión (salud, educación, vías), municipio",
 "ods_meta":"ODS 16.6","fuente_referencia":"DNP Colombia, Contraloría General","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"Presupuesto Participativo Medellín / Bogotá",
 "limitaciones":"La 'participación' puede ser formal sin influencia real en las decisiones de asignación.",
 "idioma":"ES"},

{"id":"GOB004","nombre":"Índice de Transparencia Municipal (ITM) — puntaje",
 "nombre_en":"Municipal Transparency Index — score",
 "descripcion":"Puntaje compuesto que mide la transparencia, control institucional y sanción a la corrupción en municipios colombianos (0–100). Indicador de impacto sobre gobernanza local.",
 "tipo":"impacto","sector":"Gobernanza","subsector":"Transparencia y anticorrupción",
 "nivel_medicion":"sistema","enfoque":"cuantitativo","unidad":"puntaje",
 "formula":"Puntaje ITM Transparencia por Colombia (componentes: visibilidad, institucionalidad, control y sanción)",
 "metodo_recoleccion":"datos_secundarios","instrumento_sugerido":"Índice de Transparencia de las Entidades Públicas — Transparencia por Colombia",
 "frecuencia":"anual","momento_medicion":"impacto","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"municipio, departamento, categoría de riesgo",
 "ods_meta":"ODS 16.6","fuente_referencia":"Transparencia por Colombia","codigo_iris":"",
 "valor_referencia":"ITM: 0–100; <40 = riesgo alto; >70 = nivel medio; >85 = bajo riesgo",
 "ejemplo_programa":"Transparencia por Colombia — ITM 2022–2023",
 "limitaciones":"El ITM mide normas e instituciones, no corrupción real. Publicación bienal.",
 "idioma":"ES"},

{"id":"GOB005","nombre":"Narrativas sobre cambios en la participación comunitaria en decisiones locales (cualitativo)",
 "nombre_en":"Narratives on changes in community participation in local decisions (qualitative)",
 "descripcion":"Relatos de líderes comunitarios y ciudadanos sobre si sienten que tienen más voz en las decisiones que les afectan, y qué cambios concretos lograron a través de la participación.",
 "tipo":"resultado","sector":"Gobernanza","subsector":"Participación ciudadana",
 "nivel_medicion":"comunidad","enfoque":"cualitativo","unidad":"n/a",
 "formula":"Most Significant Change (MSC): recolectar historias de cambio + triangulación con líderes",
 "metodo_recoleccion":"entrevista","instrumento_sugerido":"Protocolo MSC (Davies & Dart) + entrevistas a líderes comunitarios",
 "frecuencia":"anual","momento_medicion":"evaluacion_final","tipo_linea_base":"cualitativa",
 "diseno_comparacion":"participativo",
 "desagregacion_recomendada":"sexo, zona, grupo (líderes / ciudadanos comunes / autoridades)",
 "ods_meta":"ODS 16.7","fuente_referencia":"Davies & Dart (2005) — MSC Guide","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"Evaluaciones de gobernanza — GIZ Colombia",
 "limitaciones":"La selección de historias puede estar sesgada hacia los resultados más visibles.",
 "idioma":"ES"},

# ─────────────────────────────────────────────────────────────────────────────
# SECTOR: DESARROLLO ECONÓMICO Y REDUCCIÓN DE POBREZA
# ─────────────────────────────────────────────────────────────────────────────

{"id":"DE001","nombre":"Índice de Pobreza Multidimensional (IPM) de la población beneficiaria",
 "nombre_en":"Multidimensional Poverty Index (MPI) of beneficiary population",
 "descripcion":"Proporción de privaciones en 5 dimensiones (educación, niñez, trabajo, salud, vivienda) de los hogares beneficiarios. Indicador de impacto multidimensional sobre el bienestar.",
 "tipo":"impacto","sector":"Desarrollo económico","subsector":"Pobreza multidimensional",
 "nivel_medicion":"hogar","enfoque":"cuantitativo","unidad":"índice",
 "formula":"IPM = Incidencia (H) × Intensidad (A); privación si ≥33% de las 15 dimensiones ponderadas",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"DANE-ENCV / Módulo IPM Colombia (15 indicadores, 5 dimensiones)",
 "frecuencia":"anual","momento_medicion":"impacto","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"zona, etnia, región, tipo de hogar",
 "ods_meta":"ODS 1.2","fuente_referencia":"DANE-IPM Colombia, OPHI-Oxford, PNUD","codigo_iris":"",
 "valor_referencia":"Colombia IPM 2022: ~12.9% (urbano: 7.7%; rural: 29.5%)",
 "ejemplo_programa":"Red Unidos / SISBEN — DNP Colombia",
 "limitaciones":"El IPM no captura profundidad de las privaciones; las dimensiones son binarias.",
 "idioma":"ES"},

{"id":"DE002","nombre":"Coeficiente de Gini de los ingresos de la comunidad intervenida",
 "nombre_en":"Gini coefficient of household incomes in target community",
 "descripcion":"Medida de desigualdad en la distribución de ingresos dentro de la población beneficiaria (0 = perfecta igualdad; 1 = máxima desigualdad). Indicador de impacto sobre equidad económica.",
 "tipo":"impacto","sector":"Desarrollo económico","subsector":"Desigualdad e inequidad",
 "nivel_medicion":"sistema","enfoque":"cuantitativo","unidad":"índice",
 "formula":"Coeficiente de Gini calculado sobre distribución de ingresos del hogar",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"DANE-GEIH / encuesta de ingresos del hogar",
 "frecuencia":"anual","momento_medicion":"impacto","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"zona, región, grupo étnico",
 "ods_meta":"ODS 10.1","fuente_referencia":"DANE, Banco Mundial","codigo_iris":"",
 "valor_referencia":"Colombia Gini 2022: 0.54 (uno de los más altos de América Latina); OCDE promedio: 0.31",
 "ejemplo_programa":"Evaluaciones de programas de inclusión económica — BID, PNUD",
 "limitaciones":"El Gini requiere muestras grandes y representativas; muy sensible a ingresos extremos.",
 "idioma":"ES"},

{"id":"DE003","nombre":"Ingreso per cápita del hogar (COP/mes)",
 "nombre_en":"Household per capita income (local currency/month)",
 "descripcion":"Ingreso total mensual del hogar dividido por el número de miembros. Indicador de resultado económico que permite seguimiento a nivel de hogar.",
 "tipo":"resultado","sector":"Desarrollo económico","subsector":"Ingresos del hogar",
 "nivel_medicion":"hogar","enfoque":"cuantitativo","unidad":"COP",
 "formula":"Ingreso total hogar (mes) / Número de miembros",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"Módulo de ingresos DANE-GEIH / encuesta de hogares del programa",
 "frecuencia":"semestral","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"zona, tipo de fuente de ingreso (laboral, transferencias, autoconsumo), jefatura femenina",
 "ods_meta":"ODS 1.1","fuente_referencia":"DANE-GEIH, Banco Mundial","codigo_iris":"OD5890",
 "valor_referencia":"Línea pobreza extrema per cápita Colombia 2023: ~$180.000 COP/mes",
 "ejemplo_programa":"Encuestas de hogares — Banco Mundial / BID evaluaciones",
 "limitaciones":"Ingresos son sensibles al período de referencia; las transferencias y el autoconsumo son difíciles de valorar.",
 "idioma":"ES"},

# ─────────────────────────────────────────────────────────────────────────────
# SECTOR: VIVIENDA Y HÁBITAT
# ─────────────────────────────────────────────────────────────────────────────

{"id":"VIV001","nombre":"Número de viviendas mejoradas o construidas",
 "nombre_en":"Number of housing units improved or constructed",
 "descripcion":"Total de soluciones de vivienda (mejoramiento o construcción nueva) completadas en el período por el programa.",
 "tipo":"producto","sector":"Vivienda","subsector":"Acceso a vivienda digna",
 "nivel_medicion":"hogar","enfoque":"cuantitativo","unidad":"n",
 "formula":"Σ soluciones de vivienda con acta de entrega",
 "metodo_recoleccion":"registro_administrativo","instrumento_sugerido":"Base de datos de beneficiarios + acta de entrega",
 "frecuencia":"semestral","momento_medicion":"seguimiento","tipo_linea_base":"no_aplica",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"tipo de solución (mejora/nueva), zona, tipo de hogar, municipio",
 "ods_meta":"ODS 11.1","fuente_referencia":"MinVivienda Colombia, DANE","codigo_iris":"PI9470",
 "valor_referencia":"Déficit habitacional Colombia 2022: ~3.1 millones de hogares",
 "ejemplo_programa":"Subsidio Familiar de Vivienda — MinVivienda Colombia",
 "limitaciones":"Número de soluciones no garantiza adecuación cultural o calidad de la construcción.",
 "idioma":"ES"},

{"id":"VIV002","nombre":"Porcentaje de hogares en déficit habitacional cuantitativo",
 "nombre_en":"Percentage of households in quantitative housing deficit",
 "descripcion":"Proporción de hogares que requieren una unidad de vivienda nueva por cohabitación excesiva o habitación en vivienda no apta (refugio, cambuche, etc.).",
 "tipo":"resultado","sector":"Vivienda","subsector":"Déficit habitacional",
 "nivel_medicion":"hogar","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Hogares en déficit cuantitativo / Total hogares) × 100",
 "metodo_recoleccion":"datos_secundarios","instrumento_sugerido":"DANE-CNPV / ECV / SISBEN",
 "frecuencia":"anual","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"zona, municipio, tipo de déficit, jefatura femenina",
 "ods_meta":"ODS 11.1","fuente_referencia":"DANE, MinVivienda Colombia","codigo_iris":"",
 "valor_referencia":"Colombia: ~9.7% déficit cuantitativo (CNPV 2018)",
 "ejemplo_programa":"Política de Vivienda — DNP/MinVivienda Colombia",
 "limitaciones":"Los censos son decenales; el déficit puede cambiar rápidamente por movimientos de población.",
 "idioma":"ES"},

{"id":"VIV003","nombre":"Porcentaje de hogares con acceso a servicios básicos (agua, alcantarillado, energía)",
 "nombre_en":"Percentage of households with access to basic services",
 "descripcion":"Proporción de hogares con acceso simultáneo a agua potable por red, sistema de alcantarillado y energía eléctrica. Indicador compuesto de hábitat digno.",
 "tipo":"resultado","sector":"Vivienda","subsector":"Servicios públicos domiciliarios",
 "nivel_medicion":"hogar","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Hogares con los 3 servicios / Total hogares) × 100",
 "metodo_recoleccion":"datos_secundarios","instrumento_sugerido":"DANE-ENCV / ECV / SUI (SSPD Colombia)",
 "frecuencia":"anual","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"zona, municipio, estrato socioeconómico",
 "ods_meta":"ODS 11.1","fuente_referencia":"DANE, SSPD Colombia","codigo_iris":"",
 "valor_referencia":"Colombia: ~90% cobertura agua, ~87% alcantarillado, ~97% energía (urbano, 2022)",
 "ejemplo_programa":"Plan Departamental de Agua — MinVivienda Colombia",
 "limitaciones":"El acceso no implica continuidad ni calidad del servicio.",
 "idioma":"ES"},

{"id":"VIV004","nombre":"Percepción de seguridad y dignidad en el espacio habitacional (cualitativo)",
 "nombre_en":"Perception of safety and dignity in living space (qualitative)",
 "descripcion":"Relatos de los hogares sobre cómo el mejoramiento de su vivienda cambió su sensación de seguridad, privacidad, bienestar familiar y dignidad. Captura dimensiones que los indicadores físicos no revelan.",
 "tipo":"resultado","sector":"Vivienda","subsector":"Bienestar y dignidad habitacional",
 "nivel_medicion":"hogar","enfoque":"cualitativo","unidad":"n/a",
 "formula":"Análisis temático de entrevistas; categorías: seguridad, privacidad, orgullo, salud percibida, relaciones familiares",
 "metodo_recoleccion":"entrevista","instrumento_sugerido":"Guía de entrevista semi-estructurada en el hogar",
 "frecuencia":"semestral","momento_medicion":"evaluacion_final","tipo_linea_base":"cualitativa",
 "diseno_comparacion":"participativo",
 "desagregacion_recomendada":"sexo del jefe de hogar, número de miembros, zona",
 "ods_meta":"ODS 11.1","fuente_referencia":"Habitat for Humanity Impact Framework; ONU-Hábitat","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"Techo para mi País — Evaluaciones cualitativas",
 "limitaciones":"El bienestar habitacional es muy subjetivo y cultural; comparación entre comunidades difícil.",
 "idioma":"ES"},

# ─────────────────────────────────────────────────────────────────────────────
# SECTOR: INCLUSIÓN FINANCIERA
# ─────────────────────────────────────────────────────────────────────────────

{"id":"FIN001","nombre":"Porcentaje de personas con cuenta financiera activa",
 "nombre_en":"Percentage of people with active financial account",
 "descripcion":"Proporción de adultos (18+) que tienen al menos una cuenta en institución financiera formal (banco, cooperativa, billetera digital) con al menos una transacción en los últimos 3 meses.",
 "tipo":"resultado","sector":"Inclusión financiera","subsector":"Acceso a productos financieros",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Adultos con cuenta financiera activa / Total adultos) × 100",
 "metodo_recoleccion":"datos_secundarios","instrumento_sugerido":"Global Findex (Banco Mundial) / Encuesta Banca de Oportunidades Colombia",
 "frecuencia":"anual","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"sexo, zona, grupo etario, nivel educativo, quintil de ingresos",
 "ods_meta":"ODS 8.10","fuente_referencia":"Banco Mundial Global Findex, Banca de Oportunidades Colombia","codigo_iris":"OD5895",
 "valor_referencia":"Colombia: ~91% con cuenta (2022 Findex); brecha rural: ~80%",
 "ejemplo_programa":"Banca de Oportunidades / Daviplata — Colombia",
 "limitaciones":"Tener cuenta no implica uso activo; las billeteras digitales pueden tener bajas transacciones.",
 "idioma":"ES"},

{"id":"FIN002","nombre":"Porcentaje de MIPYME con acceso a crédito formal",
 "nombre_en":"Percentage of SMEs with access to formal credit",
 "descripcion":"Proporción de micro, pequeñas y medianas empresas que obtuvieron al menos un crédito de una entidad financiera formal en los últimos 12 meses.",
 "tipo":"resultado","sector":"Inclusión financiera","subsector":"Financiamiento a empresas",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"%",
 "formula":"(MIPYME con crédito formal / Total MIPYME encuestadas) × 100",
 "metodo_recoleccion":"datos_secundarios","instrumento_sugerido":"DANE-EAM / encuesta MIPYME / Asobancaria Colombia",
 "frecuencia":"anual","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"tamaño (micro/pequeña/mediana), sector económico, zona, sexo del propietario",
 "ods_meta":"ODS 8.10","fuente_referencia":"Asobancaria, BancoMundial, Banca de Oportunidades","codigo_iris":"",
 "valor_referencia":"Brecha de financiamiento MIPYME Colombia: ~USD 10 mil millones",
 "ejemplo_programa":"Garantías iNNpulsa / Fondo Nacional de Garantías Colombia",
 "limitaciones":"Las MIPYME informales no están en los registros; sesgo hacia empresas más formalizadas.",
 "idioma":"ES"},

{"id":"FIN003","nombre":"Número de personas que acceden a microseguros o protección financiera básica",
 "nombre_en":"Number of people accessing microinsurance or basic financial protection",
 "descripcion":"Total de personas de bajos ingresos que adquirieron o renovaron un producto de microseguro (vida, salud, agrícola, catástrofe) como resultado del programa.",
 "tipo":"resultado","sector":"Inclusión financiera","subsector":"Gestión del riesgo financiero",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"n",
 "formula":"Σ pólizas de microseguro activas entre beneficiarios del programa",
 "metodo_recoleccion":"registro_administrativo","instrumento_sugerido":"Datos del asegurador + registros del programa",
 "frecuencia":"semestral","momento_medicion":"seguimiento","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"sexo, zona, tipo de microseguro, nivel de ingreso",
 "ods_meta":"ODS 8.10","fuente_referencia":"IAIS, Microinsurance Network, Fasecolda Colombia","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"Seguro de Vida Colectivo — Bancamía / Fundación BBVA",
 "limitaciones":"La tenencia de un seguro no implica que el titular lo comprenda o lo use en caso de siniestro.",
 "idioma":"ES"},

# ─────────────────────────────────────────────────────────────────────────────
# SECTOR: PAZ, RECONCILIACIÓN Y CONSTRUCCIÓN DE TEJIDO SOCIAL
# ─────────────────────────────────────────────────────────────────────────────

{"id":"PAZ001","nombre":"Número de personas desmovilizadas o reincorporadas atendidas por el programa",
 "nombre_en":"Number of demobilized / reintegrated persons attended by programme",
 "descripcion":"Total de excombatientes o personas en proceso de reintegración que participaron activamente en el programa de construcción de paz en el período.",
 "tipo":"producto","sector":"Paz y reconciliación","subsector":"Reintegración y DDR",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"n",
 "formula":"Σ personas en proceso de reintegración con participación activa",
 "metodo_recoleccion":"registro_administrativo","instrumento_sugerido":"ARN Colombia — Sistema de información de reintegración",
 "frecuencia":"trimestral","momento_medicion":"seguimiento","tipo_linea_base":"no_aplica",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"sexo, grupo etario, grupo armado de procedencia, municipio",
 "ods_meta":"ODS 16.1","fuente_referencia":"ARN Colombia, UNODC","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"Ruta de Reintegración — ARN Colombia",
 "limitaciones":"Las definiciones de 'activo' en el proceso varían; riesgo de subregistro por movilidad.",
 "idioma":"ES"},

{"id":"PAZ002","nombre":"Tasa de homicidios por 100.000 habitantes en la zona de intervención",
 "nombre_en":"Homicide rate per 100,000 inhabitants in intervention area",
 "descripcion":"Número de homicidios por cada 100.000 habitantes en el territorio de intervención del programa. Indicador de impacto sobre seguridad y violencia.",
 "tipo":"impacto","sector":"Paz y reconciliación","subsector":"Seguridad y violencia",
 "nivel_medicion":"sistema","enfoque":"cuantitativo","unidad":"tasa",
 "formula":"(Homicidios / Población) × 100.000",
 "metodo_recoleccion":"datos_secundarios","instrumento_sugerido":"INMLCF Colombia / Policía Nacional / SIEDCO",
 "frecuencia":"anual","momento_medicion":"impacto","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"sexo, grupo etario, municipio, zona",
 "ods_meta":"ODS 16.1","fuente_referencia":"INMLCF, Policía Nacional Colombia, OEA","codigo_iris":"",
 "valor_referencia":"Colombia 2022: ~26 por 100.000 (promedio nacional; ciudades como Cali superan 50)",
 "ejemplo_programa":"Programa Integral de Seguridad Ciudadana — PNUD/Colombia",
 "limitaciones":"La tasa de homicidios puede verse afectada por cambios en el registro policial, no solo cambios reales.",
 "idioma":"ES"},

{"id":"PAZ003","nombre":"Índice de cohesión social comunitaria (escala validada)",
 "nombre_en":"Community social cohesion index (validated scale)",
 "descripcion":"Puntaje compuesto que mide confianza entre vecinos, redes de apoyo, reciprocidad y sentido de pertenencia a la comunidad. Indicador de resultado en programas de paz y convivencia.",
 "tipo":"resultado","sector":"Paz y reconciliación","subsector":"Tejido social y convivencia",
 "nivel_medicion":"comunidad","enfoque":"mixto","unidad":"puntaje",
 "formula":"Puntaje promedio en escala de cohesión social (5–7 ítems tipo Likert, 1–5)",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"Escala de Cohesión Social (UNDP Social Cohesion Index) / adaptación local",
 "frecuencia":"anual","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"sexo, etnia, zona, condición (receptor de comunidad / retornado / reintegrado)",
 "ods_meta":"ODS 16.1","fuente_referencia":"PNUD, UNDP Social Cohesion Framework","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"Reconciliación Colombia — PNUD/Gobierno Colombia",
 "limitaciones":"La cohesión social varía significativamente por el contexto histórico del conflicto; difícil de comparar entre comunidades.",
 "idioma":"ES"},

{"id":"PAZ004","nombre":"Testimonios de reconciliación y cambios en la relación con el 'otro' (cualitativo)",
 "nombre_en":"Testimonies of reconciliation and changes in relations with 'the other' (qualitative)",
 "descripcion":"Relatos de personas de grupos históricamente enfrentados (excombatientes, víctimas, comunidades receptoras) sobre cambios en cómo se relacionan, confían y construyen futuro en conjunto.",
 "tipo":"resultado","sector":"Paz y reconciliación","subsector":"Reconciliación y construcción de paz",
 "nivel_medicion":"individual","enfoque":"cualitativo","unidad":"n/a",
 "formula":"Historias de cambio más significativo (MSC) + análisis de narrativas de reconciliación",
 "metodo_recoleccion":"entrevista","instrumento_sugerido":"Entrevistas a profundidad individuales (60–90 min) con protocolo de seguridad y trauma",
 "frecuencia":"anual","momento_medicion":"evaluacion_final","tipo_linea_base":"cualitativa",
 "diseno_comparacion":"participativo",
 "desagregacion_recomendada":"condición (víctima/excombatiente/receptor), sexo, zona",
 "ods_meta":"ODS 16.1","fuente_referencia":"International Alert — Reconciliation Framework; ICTJ","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"Colombia Renace — Cruz Roja / Reconciliación Colombia",
 "limitaciones":"Estas conversaciones requieren entrevistadores con formación en trauma; los participantes pueden autocensurarse por seguridad.",
 "idioma":"ES"},

# ─────────────────────────────────────────────────────────────────────────────
# SECTOR: CAPITAL SOCIAL Y COMUNIDAD
# ─────────────────────────────────────────────────────────────────────────────

{"id":"CS001","nombre":"Número de redes, asociaciones u organizaciones comunitarias fortalecidas",
 "nombre_en":"Number of community networks, associations or organizations strengthened",
 "descripcion":"Total de organizaciones de base (JAC, asociaciones productivas, colectivos culturales) que mejoraron su capacidad organizativa como resultado del acompañamiento del programa.",
 "tipo":"resultado","sector":"Capital social","subsector":"Organizaciones de base",
 "nivel_medicion":"comunidad","enfoque":"cuantitativo","unidad":"n",
 "formula":"Σ organizaciones con diagnóstico de capacidad mejorada (pre-post OCA o equivalente)",
 "metodo_recoleccion":"revision_documental","instrumento_sugerido":"Organizational Capacity Assessment (OCA) — ICAP/USAID; o equivalente adaptado",
 "frecuencia":"anual","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"tipo de organización, zona, municipio, sexo del liderazgo",
 "ods_meta":"ODS 11.3","fuente_referencia":"ICAP OCA Tool, USAID","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"Programa de Fortalecimiento de Organizaciones Sociales — Mininterior Colombia",
 "limitaciones":"La OCA es subjetiva y puede inflarse por expectativas de financiamiento continuado.",
 "idioma":"ES"},

{"id":"CS002","nombre":"Nivel de capital social de la comunidad (índice compuesto)",
 "nombre_en":"Community social capital level (composite index)",
 "descripcion":"Índice compuesto que mide confianza interpersonal, participación en grupos, reciprocidad y acceso a redes de apoyo. Captura el tejido social como activo comunitario.",
 "tipo":"resultado","sector":"Capital social","subsector":"Capital social y redes",
 "nivel_medicion":"comunidad","enfoque":"mixto","unidad":"puntaje",
 "formula":"Promedio de puntajes estandarizados en: confianza, redes, reciprocidad, acción colectiva (World Bank Social Capital Assessment Tool — SOCAT)",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"SOCAT (Banco Mundial) / versión abreviada ICS Social Capital Questionnaire",
 "frecuencia":"anual","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"sexo, grupo etario, zona, etnia",
 "ods_meta":"ODS 11.3","fuente_referencia":"Banco Mundial SOCAT, Putnam (2000)","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"Proyectos de desarrollo comunitario — Banco Mundial / PNUD",
 "limitaciones":"El capital social es un concepto multidimensional; diferentes culturas valoran el 'buen tejido social' de manera distinta.",
 "idioma":"ES"},

{"id":"CS003","nombre":"Porcentaje de personas que reportan sentido de pertenencia a su comunidad",
 "nombre_en":"Percentage of people reporting sense of community belonging",
 "descripcion":"Proporción de participantes que afirman sentirse parte activa de su comunidad y que sus vecinos se ayudan mutuamente. Indicador de capital social bonding.",
 "tipo":"resultado","sector":"Capital social","subsector":"Cohesión e identidad comunitaria",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Personas con puntaje ≥4 en escala de pertenencia / Total encuestados) × 100",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"Encuesta de Percepción Ciudadana / Brevísima escala de pertenencia (3 ítems)",
 "frecuencia":"anual","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"sexo, grupo etario, tiempo de residencia, zona",
 "ods_meta":"ODS 11.3","fuente_referencia":"Measuring the Good Society — Stiglitz et al.; ONU-Hábitat","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"Cultura Ciudadana — Medellín / Bogotá",
 "limitaciones":"El sentido de pertenencia puede cambiar rápido ante eventos de conflicto o crisis; muy sensible a noticias recientes.",
 "idioma":"ES"},

# ─────────────────────────────────────────────────────────────────────────────
# SECTOR: SALUD MENTAL / BIENESTAR (adicionales)
# ─────────────────────────────────────────────────────────────────────────────

{"id":"SM001","nombre":"Puntaje en escala de resiliencia (Connor-Davidson o BRCS)",
 "nombre_en":"Resilience scale score (Connor-Davidson or BRCS)",
 "descripcion":"Puntaje en una escala validada de resiliencia psicológica. Mide la capacidad de las personas para recuperarse de adversidades. Indicador de resultado en programas psicosociales.",
 "tipo":"resultado","sector":"Salud mental","subsector":"Resiliencia psicosocial",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"puntaje",
 "formula":"Puntaje total CD-RISC (25 ítems, 0–100) o BRCS (4 ítems, 4–20)",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"CD-RISC (Connor & Davidson, 2003) / BRCS (versión breve) — validados en español",
 "frecuencia":"semestral","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"sexo, grupo etario, condición de víctima, zona",
 "ods_meta":"ODS 3.4","fuente_referencia":"Connor & Davidson (2003); Friborg et al. (2003)","codigo_iris":"",
 "valor_referencia":"CD-RISC: promedio población general: ~65/100; grupos traumatizados: ~55/100",
 "ejemplo_programa":"Programas de apoyo psicosocial — Cruz Roja, MSF Colombia",
 "limitaciones":"El CD-RISC es largo (25 ítems); los BRCS son menos sensibles al cambio.",
 "idioma":"ES"},

{"id":"SM002","nombre":"Puntaje en escala GAD-7 (ansiedad generalizada) pre-post",
 "nombre_en":"GAD-7 generalized anxiety score pre-post intervention",
 "descripcion":"Cambio en el puntaje del Generalized Anxiety Disorder 7-item scale entre la evaluación inicial y el seguimiento. Mide reducción de síntomas de ansiedad.",
 "tipo":"resultado","sector":"Salud mental","subsector":"Trastornos de ansiedad",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"puntaje",
 "formula":"ΔGAD-7 = Puntaje inicial − Puntaje final (reducción = mejora)",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"GAD-7 (Spitzer et al., 2006) — validado en español colombiano",
 "frecuencia":"semestral","momento_medicion":"todos","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"sexo, grupo etario, tipo de intervención, severidad inicial",
 "ods_meta":"ODS 3.4","fuente_referencia":"Spitzer et al. (2006); García-Campayo et al. validación ES","codigo_iris":"",
 "valor_referencia":"MCID GAD-7: Δ≥4 puntos; remisión: GAD-7 <5",
 "ejemplo_programa":"Programas de salud mental — MSPS / EPS Colombia","limitaciones":"Puede confundirse con síntomas somáticos; requiere alfabetismo básico.",
 "idioma":"ES"},

# ─────────────────────────────────────────────────────────────────────────────
# SECTOR: INNOVACIÓN Y EMPRENDIMIENTO SOCIAL
# ─────────────────────────────────────────────────────────────────────────────

{"id":"INN001","nombre":"Número de soluciones o prototipos desarrollados por los participantes",
 "nombre_en":"Number of solutions or prototypes developed by participants",
 "descripcion":"Total de soluciones prototipadas (productos, servicios, procesos) que surgieron de los participantes del programa de innovación o emprendimiento social.",
 "tipo":"producto","sector":"Innovación","subsector":"Emprendimiento e innovación social",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"n",
 "formula":"Σ prototipos o soluciones documentadas con ficha técnica",
 "metodo_recoleccion":"registro_administrativo","instrumento_sugerido":"Ficha de registro de prototipo / portafolio del participante",
 "frecuencia":"semestral","momento_medicion":"seguimiento","tipo_linea_base":"no_aplica",
 "diseno_comparacion":"historico",
 "desagregacion_recomendada":"tipo de solución, sector de aplicación, sexo del emprendedor",
 "ods_meta":"ODS 9.b","fuente_referencia":"iNNpulsa Colombia, ANDE (Aspen Network)","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"Reto Innova Colombia — iNNpulsa / MCIT",
 "limitaciones":"El número de prototipos no garantiza viabilidad comercial o impacto social.",
 "idioma":"ES"},

{"id":"INN002","nombre":"Porcentaje de emprendedores que aplican metodologías de diseño centrado en el usuario",
 "nombre_en":"Percentage of entrepreneurs applying human-centred design methods",
 "descripcion":"Proporción de participantes que, después del programa, reportan aplicar al menos una metodología de design thinking o diseño centrado en el usuario en sus proyectos.",
 "tipo":"resultado","sector":"Innovación","subsector":"Capacidades de innovación",
 "nivel_medicion":"individual","enfoque":"cuantitativo","unidad":"%",
 "formula":"(Emprendedores con uso confirmado de HCD / Total participantes) × 100",
 "metodo_recoleccion":"encuesta_autorreporte","instrumento_sugerido":"Encuesta de seguimiento de prácticas de innovación (post-programa)",
 "frecuencia":"semestral","momento_medicion":"evaluacion_final","tipo_linea_base":"cuantitativa",
 "diseno_comparacion":"pre_post",
 "desagregacion_recomendada":"sexo, zona, sector de aplicación, nivel educativo",
 "ods_meta":"ODS 9.b","fuente_referencia":"IDEO.org, Nesta UK","codigo_iris":"",
 "valor_referencia":"","ejemplo_programa":"Centro de Innovación Social — EAFIT / iNNpulsa",
 "limitaciones":"El autoreporte de uso de metodologías puede no reflejar correcta aplicación.",
 "idioma":"ES"},

]

with open(OUT, "a", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=FIELDS, extrasaction="ignore")
    writer.writerows(INDICATORS)

print(f"Batch 3 agregado: {len(INDICATORS)} indicadores en {OUT}")
