<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.34">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Argos — Teatro Talita Cumi – Valor Público — VALOR·IA</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<link href="../images/favicon.svg" rel="icon" type="image/svg+xml">
<script src="../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-48057c8318adb0cac17b2c26210119c4.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap-89389a2c49bf2118c955aca41aa8c1dc.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin="">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800;900&amp;family=JetBrains+Mono:wght@400;500&amp;display=swap" rel="stylesheet">


<meta property="og:title" content="Valor Público — VALOR·IA · CVP EAFIT">
<meta property="og:description" content="Plataforma de inteligencia para la medicion de valor social — SROI, CBA, WELLBY">
<meta property="og:image" content="images/og-image.png">
<meta property="og:site_name" content="Valor Público — VALOR·IA">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Valor Público — VALOR·IA</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Inicio</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../metodologia.html"> 
<span class="menu-text">Metodología</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../literatura.html"> 
<span class="menu-text">Literatura</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../evidencia.html"> 
<span class="menu-text">Evidencia Internacional</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../herramientas.html"> 
<span class="menu-text">Servicios</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../aplicaciones.html"> 
<span class="menu-text">Aplicaciones</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://www.eafit.edu.co"> 
<span class="menu-text">CVP · EAFIT</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content column-page" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Argos — Teatro Talita Cumi</h1>
</div>



<div class="quarto-title-meta column-page">

    
  
    
  </div>
  


</header>


<!-- BACK NAV -->
<div style="background: #0F172A; padding: 0.9rem 2rem; border-bottom: 1px solid rgba(255,255,255,0.07);">
<div style="max-width: 950px; margin: 0 auto;">
<p><a href="../aplicaciones.html" style="color: #5EEAD4; font-size: 0.82rem; font-weight: 600; text-decoration: none; display: inline-flex; align-items: center; gap: 0.4rem; opacity: 0.85; transition: opacity 0.2s;" onmouseover="this.style.opacity='1'" onmouseout="this.style.opacity='0.85'"> ← Portafolio de aplicaciones </a></p>
</div>
</div>
<!-- HEADER -->
<div style="background: linear-gradient(135deg, #0F172A 0%, #1a2f4a 60%, #0D4D4A 100%); padding: 3rem 2rem; position: relative; overflow: hidden;">
<div style="position: absolute; top: 0; left: 0; right: 0; bottom: 0; background: radial-gradient(ellipse at 70% 30%, rgba(13,148,136,0.15) 0%, transparent 55%); pointer-events: none;">

</div>
<div style="max-width: 950px; margin: 0 auto; display: flex; justify-content: space-between; align-items: flex-end; gap: 2rem; flex-wrap: wrap; position: relative; z-index: 1;">
<div>
<div style="display: flex; align-items: center; gap: 0.6rem; margin-bottom: 0.75rem; flex-wrap: wrap;">
<p><span style="font-size: 0.63rem; font-weight: 700; letter-spacing: 0.15em; text-transform: uppercase; color: #5EEAD4; background: rgba(13,148,136,0.15); border: 1px solid rgba(13,148,136,0.3); padding: 0.25rem 0.7rem; border-radius: 2rem;">Infraestructura comunitaria</span> <span style="font-size: 0.63rem; font-weight: 700; letter-spacing: 0.12em; text-transform: uppercase; color: #34D399; background: rgba(52,211,153,0.12); border: 1px solid rgba(52,211,153,0.25); padding: 0.25rem 0.7rem; border-radius: 2rem;">Placemaking</span></p>
</div>
<h1 style="color: white; font-size: clamp(1.6rem, 4vw, 2.2rem); margin-bottom: 0.4rem; letter-spacing: -0.03em; font-weight: 800;">
Teatro Talita Cumi
</h1>
<h2 style="color: #CBD5E1; font-size: 1.05rem; font-weight: 400; margin-bottom: 0.5rem;" class="anchored">
Sueños que Transforman — Fundación Grupo Argos
</h2>
<div style="color: #64748B; font-size: 0.85rem;">
Barrio Manrique · Medellín · Ciclo 2024–2025 · Centro Valor Público EAFIT
</div>
</div>
<div style="display: flex; gap: 1rem; flex-wrap: wrap; align-self: center;">
<div style="background: rgba(148,163,184,0.1); border: 1px solid rgba(148,163,184,0.25); border-radius: 0.75rem; padding: 1.1rem 1.4rem; text-align: center; min-width: 105px;">
<div style="font-size: 0.6rem; font-weight: 700; letter-spacing: 0.12em; text-transform: uppercase; color: #64748B; margin-bottom: 0.25rem;">
SROI Reportado
</div>
<div style="font-size: 2.3rem; font-weight: 900; color: #94A3B8; letter-spacing: -0.04em; line-height: 1;">
0.52×
</div>
<div style="font-size: 0.68rem; color: #475569; margin-top: 0.2rem;">
3 años · base
</div>
</div>
<div style="background: rgba(13,148,136,0.15); border: 1px solid rgba(13,148,136,0.4); border-radius: 0.75rem; padding: 1.1rem 1.4rem; text-align: center; min-width: 105px;">
<div style="font-size: 0.6rem; font-weight: 700; letter-spacing: 0.12em; text-transform: uppercase; color: #5EEAD4; margin-bottom: 0.25rem;">
SROI Central
</div>
<div style="font-size: 2.3rem; font-weight: 900; color: white; letter-spacing: -0.04em; line-height: 1;">
2.35×
</div>
<div style="font-size: 0.68rem; color: #94A3B8; margin-top: 0.2rem;">
3 años · corregido
</div>
</div>
<div style="background: rgba(245,158,11,0.12); border: 1px solid rgba(245,158,11,0.3); border-radius: 0.75rem; padding: 1.1rem 1.4rem; text-align: center; min-width: 105px;">
<div style="font-size: 0.6rem; font-weight: 700; letter-spacing: 0.12em; text-transform: uppercase; color: #FCD34D; margin-bottom: 0.25rem;">
SROI a 5 años
</div>
<div style="font-size: 2.3rem; font-weight: 900; color: #FCD34D; letter-spacing: -0.04em; line-height: 1;">
3.37×
</div>
<div style="font-size: 0.68rem; color: #94A3B8; margin-top: 0.2rem;">
vida útil infraestructura
</div>
</div>
</div>
</div>
</div>
<!-- STATS STRIP -->
<div class="stats-strip">
<div class="stats-grid">
<pre><code>&lt;div class="stat-item"&gt;
  &lt;span class="stat-number"&gt;$203M&lt;/span&gt;
  &lt;span class="stat-label"&gt;COP invertidos&lt;/span&gt;
&lt;/div&gt;
&lt;div class="stat-item"&gt;
  &lt;span class="stat-number"&gt;25&lt;/span&gt;
  &lt;span class="stat-label"&gt;años deterioro revertidos&lt;/span&gt;
&lt;/div&gt;
&lt;div class="stat-item"&gt;
  &lt;span class="stat-number"&gt;60&lt;/span&gt;
  &lt;span class="stat-label"&gt;beneficiarios (central)&lt;/span&gt;
&lt;/div&gt;
&lt;div class="stat-item"&gt;
  &lt;span class="stat-number"&gt;P38&lt;/span&gt;
  &lt;span class="stat-label"&gt;percentil global — ciclo 1&lt;/span&gt;
&lt;/div&gt;
&lt;div class="stat-item"&gt;
  &lt;span class="stat-number"&gt;383&lt;/span&gt;
  &lt;span class="stat-label"&gt;reportes SVI comparados&lt;/span&gt;
&lt;/div&gt;</code></pre>
</div>
</div>
<!-- CONTEXTO -->
<div class="content-section">
<div class="content-inner">
<span class="section-label">Contexto del programa</span>
<h2 class="section-heading anchored">
Un espacio que una comunidad esperó 25 años
</h2>
<p>
<em>Sueños que Transforman</em> (SQT) es una iniciativa de Fundación Grupo Argos que financia mejoras de infraestructura en espacios comunitarios preexistentes en barrios populares de Medellín. En este caso: el Teatro Talita Cumi, en el barrio Manrique, un espacio centenario de la Corporación Minuto de Dios que estuvo en deterioro durante 25 años sin que la comunidad lograra recuperarlo.
</p>
<p>
La intervención incluyó adecuación física del teatro (iluminación, sonido, camerinos, accesibilidad), fortalecimiento de capacidades de 20 líderes comunitarios y articulación estratégica con Fundación Grupo Argos. El acompañamiento metodológico fue realizado por el Centro Valor Público de EAFIT siguiendo la metodología SROI de Social Value International.
</p>
<div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(155px, 1fr)); gap: 1rem; margin: 1.5rem 0;">
<div style="background: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 0.5rem; padding: 1rem;">
<div style="font-size: 0.67rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.08em; color: #64748B; margin-bottom: 0.35rem;">
Inversión total
</div>
<div style="font-size: 1.3rem; font-weight: 800; color: #0F172A;">
$203M COP
</div>
<div style="font-size: 0.76rem; color: #64748B;">
Valor de obra — denominador SROI
</div>
</div>
<div style="background: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 0.5rem; padding: 1rem;">
<div style="font-size: 0.67rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.08em; color: #64748B; margin-bottom: 0.35rem;">
Muestra encuestada
</div>
<div style="font-size: 1.3rem; font-weight: 800; color: #0F172A;">
20 líderes
</div>
<div style="font-size: 0.76rem; color: #64748B;">
Proceso formativo intensivo
</div>
</div>
<div style="background: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 0.5rem; padding: 1rem;">
<div style="font-size: 0.67rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.08em; color: #64748B; margin-bottom: 0.35rem;">
Proxy WTP mediana
</div>
<div style="font-size: 1.3rem; font-weight: 800; color: #0F172A;">
$6.2M COP
</div>
<div style="font-size: 0.76rem; color: #64748B;">
por beneficiario / año
</div>
</div>
<div style="background: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 0.5rem; padding: 1rem;">
<div style="font-size: 0.67rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.08em; color: #64748B; margin-bottom: 0.35rem;">
Outcomes identificados
</div>
<div style="font-size: 1.3rem; font-weight: 800; color: #0F172A;">
5 impactos
</div>
<div style="font-size: 0.76rem; color: #64748B;">
3 monetizados este ciclo
</div>
</div>
<div style="background: #F8FAFC; border: 1px solid #E2E8F0; border-radius: 0.5rem; padding: 1rem;">
<div style="font-size: 0.67rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.08em; color: #64748B; margin-bottom: 0.35rem;">
Horizonte analizado
</div>
<div style="font-size: 1.3rem; font-weight: 800; color: #0F172A;">
3 años
</div>
<div style="font-size: 0.76rem; color: #64748B;">
Vida útil: 15–20 años
</div>
</div>
</div>
<div class="pres-banner">
<div class="pres-icon">
▶
</div>
<div class="pres-text">
<pre><code>&lt;div class="pres-titulo"&gt;Presentación ejecutiva disponible&lt;/div&gt;
&lt;div class="pres-desc"&gt;15 diapositivas para junta directiva, inversionistas y aliados — versión RevealJS&lt;/div&gt;</code></pre>
</div>
<p><a href="../../02_Aplicaciones/2026_Argos_STC/04_outputs/presentacion_sroi.html" class="pres-cta">Ver presentación →</a></p>
</div>
</div>
</div>
<!-- DASHBOARD -->
<div class="content-section alt">
<div class="content-inner">
<span class="section-label">Indicadores clave</span>
<h2 class="section-heading anchored">
Panel de resultados del programa
</h2>
<p>
Los datos primarios revelan cambios sustanciales en múltiples dimensiones. El cuadro de mando sintetiza los resultados más relevantes de la evaluación pareada pre-post (N = 20 líderes comunitarios).
</p>
<div style="text-align: center; margin: 1.5rem 0;">
<p><img src="../images/argos/fig6_dashboard.png" alt="Dashboard indicadores clave" style="max-width: 100%; border-radius: 0.625rem; border: 1px solid #E2E8F0; box-shadow: 0 4px 20px rgba(0,0,0,0.08);"></p>
</div>
<p class="chart-note">
Fuente: Diagnóstico técnico SROI — Teatro Talita Cumi. CVP EAFIT, marzo 2026. N = 20 líderes. Datos pareados pre-post.
</p>
</div>
</div>
<!-- DIAGNÓSTICO TÉCNICO -->
<div class="content-section">
<div class="content-inner">
<span class="section-label">Diagnóstico técnico</span>
<h2 class="section-heading anchored">
Por qué 0.52 no refleja el valor total generado
</h2>
<p>
El SROI reportado (0.52 a 3 años en el escenario base) es metodológicamente correcto en su mecánica de cálculo — los factores de ajuste fueron bien aplicados. El problema no está en los números, sino en las decisiones de alcance. El diagnóstico identifica tres drivers de subestimación, cada uno independiente y acumulable:
</p>
<div class="insight-box">
<div class="insight-label">
Verificación del cálculo original
</div>
<p>
Fórmula SVI: <code>BN = BB × (1 – DW) × (1 – attr_otros) × (1 – displacement)</code>. Con los datos reportados: <code>$124.9M × 0.533 × 0.738 × 0.902 = $44.3M COP</code>. SROI año 1 = 44.3M / 203M = <strong>0.218</strong>. Verificado y correcto. <em>attr_otros</em> = 26.3% significa que el 73.7% del beneficio se atribuye a SQT — razonable dado que SQT fue el agente físico de la transformación.
</p>
</div>
<div style="display: flex; flex-direction: column; border: 1px solid #E2E8F0; border-radius: 0.75rem; overflow: hidden; background: white; margin: 1.5rem 0;">
<div style="display: grid; grid-template-columns: 52px 1fr 110px; gap: 1rem; padding: 0.9rem 1.25rem; background: #0F172A;">
<div style="font-size: 0.67rem; font-weight: 700; color: #64748B; text-transform: uppercase; letter-spacing: 0.08em;">
Sev.
</div>
<div style="font-size: 0.67rem; font-weight: 700; color: #64748B; text-transform: uppercase; letter-spacing: 0.08em;">
Driver de subestimación
</div>
<div style="font-size: 0.67rem; font-weight: 700; color: #64748B; text-transform: uppercase; letter-spacing: 0.08em; text-align: right;">
Efecto SROI
</div>
</div>
<div style="display: grid; grid-template-columns: 52px 1fr 110px; gap: 1rem; align-items: start; padding: 1.25rem; border-bottom: 1px solid #F1F5F9;">
<div style="display: inline-flex; align-items: center; justify-content: center; width: 2rem; height: 2rem; background: #DC2626; color: white; font-size: 0.75rem; font-weight: 700; border-radius: 50%; flex-shrink: 0;">
A
</div>
<div>
<div style="font-weight: 700; color: #0F172A; margin-bottom: 0.35rem;">
Solo 20 beneficiarios vs.&nbsp;comunidad real
</div>
<div style="font-size: 0.83rem; color: #475569; line-height: 1.65;">
El estudio encuestó a los 20 líderes del proceso formativo intensivo. El Teatro atiende además a grupos de danza (Pilositas y Pioneros, 20 años de actividad), equipos deportivos, cursos de barbería/cocina/inglés, adultos mayores y jóvenes en prevención de riesgo. Escalar conservadoramente a 60 beneficiarios equivalentes triplica el beneficio bruto sin cambiar ningún otro supuesto.
</div>
</div>
<div style="text-align: right; font-family: monospace; font-size: 1rem; font-weight: 800; color: #DC2626;">
×2 a ×5
</div>
</div>
<div style="display: grid; grid-template-columns: 52px 1fr 110px; gap: 1rem; align-items: start; padding: 1.25rem; border-bottom: 1px solid #F1F5F9;">
<div style="display: inline-flex; align-items: center; justify-content: center; width: 2rem; height: 2rem; background: #F59E0B; color: white; font-size: 0.75rem; font-weight: 700; border-radius: 50%; flex-shrink: 0;">
A
</div>
<div>
<div style="font-weight: 700; color: #0F172A; margin-bottom: 0.35rem;">
Deadweight de 47% elevado para infraestructura con 25 años de intento fallido
</div>
<div style="font-size: 0.83rem; color: #475569; line-height: 1.65;">
El DW empírico captura la percepción de cambio personal de los líderes. Pero el proxy I4 monetiza el acceso a servicios en una infraestructura que SQT rehabilitó físicamente. Evidencia clave: el teatro estuvo deteriorado 25 años sin recuperación posible. Para infraestructura históricamente no realizada, el DW apropiado es 15–25%. La corrección de DW=47% a DW=25% incrementa el SROI un 40%.
</div>
</div>
<div style="text-align: right; font-family: monospace; font-size: 1rem; font-weight: 800; color: #F59E0B;">
×1.3 a 1.7
</div>
</div>
<div style="display: grid; grid-template-columns: 52px 1fr 110px; gap: 1rem; align-items: start; padding: 1.25rem;">
<div style="display: inline-flex; align-items: center; justify-content: center; width: 2rem; height: 2rem; background: #0EA5E9; color: white; font-size: 0.75rem; font-weight: 700; border-radius: 50%; flex-shrink: 0;">
A
</div>
<div>
<div style="font-weight: 700; color: #0F172A; margin-bottom: 0.35rem;">
Solo I4 monetizado de 5 impactos con evidencia cuantitativa
</div>
<div style="font-size: 0.83rem; color: #475569; line-height: 1.65;">
I2 (liderazgo) tiene evidencia pareada sólida: iniciativas por líder +40.9% (5.5 a 7.75). R6 (seguridad) tiene dato pareado: percepción 83% a 100% (+17pp). Ambos tienen proxies documentados y son materiales según el estándar SVI. Con 20 beneficiarios el incremento es modesto; se amplifica al escalar beneficiarios.
</div>
</div>
<div style="text-align: right; font-family: monospace; font-size: 1rem; font-weight: 800; color: #0EA5E9;">
+0.05 a 0.20
</div>
</div>
</div>
</div>
</div>
<!-- METODOLOGÍA -->
<div class="content-section alt">
<div class="content-inner">
<span class="section-label">Metodología</span>
<h2 class="section-heading anchored">
Cómo medimos: las 6 etapas del SROI
</h2>
<p>
El análisis sigue la metodología <strong>SROI de Social Value International (SVI)</strong>, el estándar global para la medición de valor social. La metodología se articula en seis etapas secuenciales que garantizan rigor, transparencia y reproducibilidad.
</p>
<div class="stage-grid">
<div class="stage-card" style="--stage-color: #0D9488;">
<pre><code>&lt;div class="stage-number"&gt;Etapa 1&lt;/div&gt;
&lt;div class="stage-title"&gt;Alcance y stakeholders&lt;/div&gt;
&lt;div class="stage-desc"&gt;Definición del perímetro del análisis y los grupos afectados. Para SQT: Fundación Argos (pagador), 20 líderes encuestados, comunidad amplia del teatro (usuarios de danza, deporte, formación), y territorio del barrio Manrique.&lt;/div&gt;</code></pre>
</div>
<div class="stage-card" style="--stage-color: #0891B2;">
<pre><code>&lt;div class="stage-number"&gt;Etapa 2&lt;/div&gt;
&lt;div class="stage-title"&gt;Mapa de impacto&lt;/div&gt;
&lt;div class="stage-desc"&gt;Construcción participativa de la Teoría del Cambio. $203M COP + metodología CVP EAFIT → recuperación del teatro → 5 tipos de cambio medibles: infraestructura (I4), liderazgo (I2), seguridad (R6), bienestar (I1), economía local (I3).&lt;/div&gt;</code></pre>
</div>
<div class="stage-card" style="--stage-color: #7C3AED;">
<pre><code>&lt;div class="stage-number"&gt;Etapa 3&lt;/div&gt;
&lt;div class="stage-title"&gt;Evidencia de los outcomes&lt;/div&gt;
&lt;div class="stage-desc"&gt;Encuesta pre-post a 20 líderes comunitarios, grupos focales y registro administrativo. Datos pareados para I2 (+41% iniciativas), R6 (+17pp percepción seguridad) e I4 (WTP directa).&lt;/div&gt;</code></pre>
</div>
<div class="stage-card" style="--stage-color: #B45309;">
<pre><code>&lt;div class="stage-number"&gt;Etapa 4&lt;/div&gt;
&lt;div class="stage-title"&gt;Establecer el valor&lt;/div&gt;
&lt;div class="stage-desc"&gt;Proxies generados directamente por los beneficiarios: WTP mediana para infraestructura ($6.24M COP/persona/año), costo de diplomado equivalente para liderazgo, costo social evitado para seguridad.&lt;/div&gt;</code></pre>
</div>
<div class="stage-card" style="--stage-color: #059669;">
<pre><code>&lt;div class="stage-number"&gt;Etapa 5&lt;/div&gt;
&lt;div class="stage-title"&gt;Calcular el impacto neto&lt;/div&gt;
&lt;div class="stage-desc"&gt;Aplicación de cuatro factores de ajuste: deadweight (25%), atribución a otros (26.25%), desplazamiento (0%), decaimiento (5% anual). VPN a 3 años / inversión = SROI central 2.35.&lt;/div&gt;</code></pre>
</div>
<div class="stage-card" style="--stage-color: #DC2626;">
<pre><code>&lt;div class="stage-number"&gt;Etapa 6&lt;/div&gt;
&lt;div class="stage-title"&gt;Reportar, verificar y actuar&lt;/div&gt;
&lt;div class="stage-desc"&gt;Informe completo con supuestos declarados, revisión por pares CVP EAFIT. Verificación formal SVI proyectada para 2027. Este caso documenta el ciclo 1 y la hoja de ruta hacia el aseguramiento.&lt;/div&gt;</code></pre>
</div>
</div>
<span class="section-label" style="margin-top: 2rem; display: inline-block;">Proxies y factores de ajuste</span>
<h3 style="font-size: 1.15rem; font-weight: 700; color: #0F172A; margin-bottom: 0.5rem; margin-top: 0.25rem;" class="anchored">
¿Cómo se valoró cada impacto y cómo se redujo el beneficio bruto?
</h3>
<div class="method-grid">
<div class="method-card" style="--method-bg: rgba(13,148,136,0.1); --method-color: #0D9488;">
<pre><code>&lt;div class="method-tag"&gt;WTP — Encuesta directa&lt;/div&gt;
&lt;div class="method-title"&gt;Infraestructura accesible (I4)&lt;/div&gt;
&lt;div class="method-desc"&gt;Disposición a pagar por servicios equivalentes en otro espacio de la ciudad. Se usó la &lt;strong&gt;mediana&lt;/strong&gt; para proteger el resultado de valores extremos.&lt;/div&gt;
&lt;div class="method-example"&gt;Mediana: $6.245.400 COP/persona/año · N = 20 líderes&lt;/div&gt;</code></pre>
</div>
<div class="method-card" style="--method-bg: rgba(8,145,178,0.1); --method-color: #0891B2;">
<pre><code>&lt;div class="method-tag"&gt;Costo del servicio equivalente&lt;/div&gt;
&lt;div class="method-title"&gt;Liderazgo comunitario (I2)&lt;/div&gt;
&lt;div class="method-desc"&gt;El incremento en iniciativas activas por líder (+41%) se valoró usando el costo de un diplomado de liderazgo comunitario equivalente en el mercado local.&lt;/div&gt;
&lt;div class="method-example"&gt;Proxy: $1.500.000 COP/liderazgo-iniciativa · Incremento: 2,25 por líder&lt;/div&gt;</code></pre>
</div>
<div class="method-card" style="--method-bg: rgba(124,58,237,0.1); --method-color: #7C3AED;">
<pre><code>&lt;div class="method-tag"&gt;Costo evitado&lt;/div&gt;
&lt;div class="method-title"&gt;Seguridad y prevención (R6)&lt;/div&gt;
&lt;div class="method-desc"&gt;Mejora en percepción de seguridad (+17 pp) aproximada mediante el costo social evitado de la inseguridad (Cruz Guzmán, 2019 — costos prevención crimen Medellín).&lt;/div&gt;
&lt;div class="method-example"&gt;Proxy: $650.000 COP/pp-mejora/persona · Cambio: de 83% a 100%&lt;/div&gt;</code></pre>
</div>
</div>
<div style="border: 1px solid #E2E8F0; border-radius: 0.75rem; overflow: hidden; background: white; margin: 1.75rem 0;">
<div style="display: grid; grid-template-columns: 150px 1fr 130px; gap: 1rem; padding: 0.7rem 1.25rem; background: #0F172A; font-size: 0.67rem; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; color: #64748B;">
<pre><code>&lt;div&gt;Factor&lt;/div&gt;&lt;div&gt;¿Qué ajusta?&lt;/div&gt;&lt;div style="text-align:right;"&gt;Valor aplicado&lt;/div&gt;</code></pre>
</div>
<div class="factor-row">
<pre><code>&lt;div class="factor-name"&gt;Peso muerto (DW)&lt;/div&gt;
&lt;div class="factor-desc"&gt;Lo que habría ocurrido sin el programa. Corregido de 47% empírico a 25%: el teatro llevaba 25 años sin recuperación posible — evidencia histórica irrefutable.&lt;/div&gt;
&lt;div class="factor-range"&gt;25%&lt;/div&gt;</code></pre>
</div>
<div class="factor-row">
<pre><code>&lt;div class="factor-name"&gt;Atribución a otros&lt;/div&gt;
&lt;div class="factor-desc"&gt;Parte del beneficio atribuible a otros actores (comunidad, Corporación Minuto de Dios, políticas municipales). SQT retiene el 73.75% como agente físico de la transformación.&lt;/div&gt;
&lt;div class="factor-range"&gt;26.25%&lt;/div&gt;</code></pre>
</div>
<div class="factor-row">
<pre><code>&lt;div class="factor-name"&gt;Desplazamiento&lt;/div&gt;
&lt;div class="factor-desc"&gt;El Teatro Talita Cumi no compite con ningún otro espacio comunitario existente en Manrique. Desplazamiento estimado en cero.&lt;/div&gt;
&lt;div class="factor-range"&gt;0%&lt;/div&gt;</code></pre>
</div>
<div class="factor-row">
<pre><code>&lt;div class="factor-name"&gt;Decaimiento&lt;/div&gt;
&lt;div class="factor-desc"&gt;Tasa de reducción anual del impacto. Infraestructura física: lenta degradación. Liderazgo: puede decaer si no hay activación continua. Estimación conservadora.&lt;/div&gt;
&lt;div class="factor-range"&gt;5% anual&lt;/div&gt;</code></pre>
</div>
<div class="factor-row" style="border-bottom: none;">
<pre><code>&lt;div class="factor-name"&gt;Tasa de descuento&lt;/div&gt;
&lt;div class="factor-desc"&gt;Costo de oportunidad del dinero en el tiempo. Referencia del Banco de la República para Colombia.&lt;/div&gt;
&lt;div class="factor-range"&gt;7% anual&lt;/div&gt;</code></pre>
</div>
</div>
</div>
</div>
<!-- RESULTADOS -->
<div class="content-section">
<div class="content-inner">
<span class="section-label">Resultados</span>
<h2 class="section-heading anchored">
El valor social generado
</h2>
<div class="sroi-resultado-panel">
<div class="sroi-item">
<pre><code>&lt;div class="sroi-label"&gt;Escenario conservador&lt;/div&gt;
&lt;div class="sroi-valor"&gt;1.59&lt;/div&gt;
&lt;div class="sroi-sub"&gt;3 años · 40 beneficiarios&lt;br&gt;infraestructura + liderazgo&lt;/div&gt;</code></pre>
</div>
<div class="sroi-item">
<pre><code>&lt;div class="sroi-label"&gt;Escenario central&lt;/div&gt;
&lt;div class="sroi-valor"&gt;2.35&lt;/div&gt;
&lt;div class="sroi-sub"&gt;3 años · 60 beneficiarios&lt;br&gt;infraestructura + liderazgo + seguridad&lt;/div&gt;</code></pre>
</div>
<div class="sroi-item">
<pre><code>&lt;div class="sroi-label"&gt;Central a 5 años&lt;/div&gt;
&lt;div class="sroi-valor"&gt;3.37&lt;/div&gt;
&lt;div class="sroi-sub"&gt;Reconociendo la vida útil&lt;br&gt;de la infraestructura (15–20 años)&lt;/div&gt;</code></pre>
</div>
</div>
<p>
Los tres escenarios superan el umbral de break-even (SROI = 1,0) — en cualquier supuesto plausible, el programa generó más valor social del que costó. La diferencia entre escenarios no refleja incertidumbre sobre si el impacto existe, sino sobre cuántos beneficiarios del espacio se capturan en la medición.
</p>
<div class="charts-2col">
<div>
<img src="../images/argos/fig1_waterfall_original.png" alt="Waterfall — de la inversión al valor social neto" style="width: 100%; border-radius: 0.625rem; border: 1px solid #E2E8F0; box-shadow: 0 4px 16px rgba(0,0,0,0.06);">
<p class="chart-note">
De la inversión al valor social neto. Los tres descuentos (DW 25%, atribución 26.25%, desplazamiento 0%) garantizan que el resultado no sobreatribuye el impacto.
</p>
</div>
<div>
<img src="../images/argos/fig5_desglose_outcomes.png" alt="Composición del valor por outcome" style="width: 100%; border-radius: 0.625rem; border: 1px solid #E2E8F0; box-shadow: 0 4px 16px rgba(0,0,0,0.06);">
<p class="chart-note">
Infraestructura (I4) representa el 83% del valor bruto. Liderazgo (14%) y seguridad (3%) ampliarán su peso al escalar la base de beneficiarios.
</p>
</div>
</div>
</div>
</div>
<!-- ESCENARIOS -->
<div class="content-section alt">
<div class="content-wide">
<span class="section-label">Escenarios</span>
<h2 class="section-heading anchored">
El espacio completo de resultados plausibles
</h2>
<div style="margin: 1.5rem 0;">
<img src="../images/argos/fig2_escenarios.png" alt="Comparación escenarios SROI" style="width: 100%; max-width: 900px; display: block; margin: 0 auto; border-radius: 0.625rem; border: 1px solid #E2E8F0; box-shadow: 0 4px 16px rgba(0,0,0,0.06);">
<p class="chart-note" style="text-align: center;">
11 escenarios SROI. Línea verde = punto de equilibrio (SROI = 1).
</p>
</div>
<div style="background: white; border: 1px solid #E2E8F0; border-radius: 0.75rem; overflow: hidden; margin: 1.5rem 0;">
<div style="padding: 0.7rem 1.25rem; background: #0F172A;">
<div style="color: white; font-size: 0.78rem; font-weight: 700; letter-spacing: 0.08em; text-transform: uppercase;">
Tabla de escenarios — SROI a 3 años
</div>
</div>
<div style="overflow-x: auto;">
<table style="margin: 0;">
<thead>
<tr>
<th>
Escenario
</th>
<th>
DW
</th>
<th>
Benef.
</th>
<th>
Outcomes
</th>
<th>
1 año
</th>
<th>
3 años
</th>
</tr>
</thead>
<tbody>
<tr style="background: #FEF3C7;">
<td>
<strong>Original base</strong>
</td>
<td>
46.7%
</td>
<td>
20
</td>
<td>
I4
</td>
<td>
0.22
</td>
<td>
<strong>0.52</strong>
</td>
</tr>
<tr>
<td>
Corr. DW (25%)
</td>
<td>
25.0%
</td>
<td>
20
</td>
<td>
I4
</td>
<td>
0.31
</td>
<td>
0.73
</td>
</tr>
<tr>
<td>
Corr. 60 beneficiarios
</td>
<td>
46.7%
</td>
<td>
60
</td>
<td>
I4
</td>
<td>
0.65
</td>
<td>
1.56
</td>
</tr>
<tr>
<td>
Combinado conservador
</td>
<td>
25.0%
</td>
<td>
40
</td>
<td>
I4+I2
</td>
<td>
0.66
</td>
<td>
1.59
</td>
</tr>
<tr style="background: #DCFCE7;">
<td>
<strong>Combinado central</strong>
</td>
<td>
25.0%
</td>
<td>
60
</td>
<td>
I4+I2+R6
</td>
<td>
0.99
</td>
<td>
<strong>2.35</strong>
</td>
</tr>
<tr>
<td>
Central, 5 años
</td>
<td>
25.0%
</td>
<td>
60
</td>
<td>
I4+I2+R6
</td>
<td>
—
</td>
<td>
3.37
</td>
</tr>
<tr>
<td>
Optimista
</td>
<td>
15.0%
</td>
<td>
100
</td>
<td>
I4+I2+R6
</td>
<td>
2.06
</td>
<td>
4.91
</td>
</tr>
</tbody>
</table>
</div>
</div>
</div>
</div>
<!-- SENSIBILIDAD -->
<div class="content-section">
<div class="content-wide">
<span class="section-label">Análisis de riesgo</span>
<h2 class="section-heading anchored">
¿El resultado es robusto?
</h2>
<p>
El mapa de calor y el gráfico tornado muestran que el resultado es sólido ante variaciones en los parámetros técnicos. El número de beneficiarios es el driver dominante — el único factor verdaderamente addressable para el próximo ciclo.
</p>
<div class="charts-2col">
<div>
<img src="../images/argos/fig3_heatmap_sensibilidad.png" alt="Heatmap sensibilidad" style="width: 100%; border-radius: 0.625rem; border: 1px solid #E2E8F0; box-shadow: 0 4px 16px rgba(0,0,0,0.06);">
<p class="chart-note">
SROI a 3 años para cada combinación de DW y número de beneficiarios. El resultado supera el break-even en prácticamente toda la superficie del mapa.
</p>
</div>
<div>
<img src="../images/argos/fig4_tornado.png" alt="Tornado chart" style="width: 100%; border-radius: 0.625rem; border: 1px solid #E2E8F0; box-shadow: 0 4px 16px rgba(0,0,0,0.06);">
<p class="chart-note">
Impacto individual de cada variable sobre el SROI. El número de beneficiarios domina — los parámetros financieros son secundarios.
</p>
</div>
</div>
</div>
</div>
<!-- VPN ACUMULADO -->
<div class="content-section alt">
<div class="content-inner">
<span class="section-label">Proyección temporal</span>
<h2 class="section-heading anchored">
VPN acumulado a 10 años
</h2>
<div style="margin: 1.5rem 0;">
<img src="../images/argos/fig8_vpn_acumulado.png" alt="VPN acumulado" style="width: 100%; max-width: 900px; display: block; margin: 0 auto; border-radius: 0.625rem; border: 1px solid #E2E8F0; box-shadow: 0 4px 16px rgba(0,0,0,0.06);">
<p class="chart-note" style="text-align: center;">
La inversión de $203M se recupera socialmente antes del año 2 en el escenario central. La infraestructura continúa generando valor durante toda su vida útil estimada (15–20 años).
</p>
</div>
</div>
</div>
<!-- BENCHMARKING (dark) -->
<div class="content-section dark">
<div class="content-wide">
<span class="section-label">Comparativa internacional</span>
<h2 class="section-heading anchored">
SQT en el contexto global
</h2>
<p>
Este análisis compara los resultados de SQT con <strong>383 reportes SROI</strong> de la base de datos internacional de Social Value UK, de los cuales 64 reportan un ratio numérico verificable. Los programas de infraestructura comunitaria, placemaking y desarrollo social tienen ratios entre 1,5 y 8,4.
</p>
<div class="metric-grid" style="max-width: 900px; margin: 1.5rem auto;">
<div class="metric-card azul">
<pre><code>&lt;span class="metric-value"&gt;383&lt;/span&gt;
&lt;span class="metric-label"&gt;reportes SVI&lt;/span&gt;
&lt;span class="metric-note"&gt;base de datos global&lt;/span&gt;</code></pre>
</div>
<div class="metric-card verde">
<pre><code>&lt;span class="metric-value"&gt;4.35&lt;/span&gt;
&lt;span class="metric-label"&gt;mediana global&lt;/span&gt;
&lt;span class="metric-note"&gt;referencia internacional&lt;/span&gt;</code></pre>
</div>
<div class="metric-card naranja">
<pre><code>&lt;span class="metric-value"&gt;P38&lt;/span&gt;
&lt;span class="metric-label"&gt;percentil SQT hoy&lt;/span&gt;
&lt;span class="metric-note"&gt;primer ciclo evaluativo&lt;/span&gt;</code></pre>
</div>
<div class="metric-card oscuro">
<pre><code>&lt;span class="metric-value"&gt;P50+&lt;/span&gt;
&lt;span class="metric-label"&gt;percentil proyectado&lt;/span&gt;
&lt;span class="metric-note"&gt;con contador + encuesta ampliada&lt;/span&gt;</code></pre>
</div>
</div>
<div style="margin: 1.5rem 0;">
<img src="../images/argos/fig9_benchmark_distribucion.png" alt="Distribución global de ratios SROI" style="width: 100%; border-radius: 0.625rem; border: 1px solid rgba(255,255,255,0.08); box-shadow: 0 4px 20px rgba(0,0,0,0.2);">
<p class="chart-note" style="text-align: center;">
Posición de SQT en la distribución global de 64 ratios verificados. Izquierda: el escenario central (2,35) se ubica en el tercio inferior — resultado esperado para un primer ciclo. Derecha: curva percentil — conservador en P22, central en P38, a 5 años en P50.
</p>
</div>
<div style="margin: 1.5rem 0;">
<img src="../images/argos/fig10_benchmark_comparables.png" alt="Programas comparables a nivel mundial" style="width: 100%; border-radius: 0.625rem; border: 1px solid rgba(255,255,255,0.08); box-shadow: 0 4px 20px rgba(0,0,0,0.2);">
<p class="chart-note" style="text-align: center;">
SQT en relación a los 17 programas más comparables de la base SVI. North Ayrshire Fab Pad (8,38) y Carmichael Centre (7,10) representan el potencial del programa con datos más completos — mismo tipo de intervención, misma lógica de impacto.
</p>
</div>
<div style="margin: 1.5rem 0;">
<img src="../images/argos/fig11_benchmark_sectores.png" alt="Rangos SROI por sector" style="width: 100%; border-radius: 0.625rem; border: 1px solid rgba(255,255,255,0.08); box-shadow: 0 4px 20px rgba(0,0,0,0.2);">
<p class="chart-note" style="text-align: center;">
Rangos SROI por sector (punto = mediana). Vivienda/infraestructura: mediana 3,1. Inclusión social: mediana 4,8. La brecha con la mediana sectorial se explica completamente por la captura parcial de beneficiarios del ciclo 1.
</p>
</div>
<div class="callout callout-style-default callout-tip callout-titled" style="background: rgba(5,150,105,0.12); border-color: #059669;">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<div class="callout-title" style="color: #34D399;">
Lo que dicen los comparables internacionales
</div>
<p style="color: #CBD5E1;">
Ningún programa de espacio comunitario o placemaking comparable tiene SROI bajo cuando usa correctamente su universo de beneficiarios. SQT tiene el mismo tipo de intervención y la misma lógica de impacto que los programas en el percentil 70–80. La diferencia hoy es exclusivamente de datos, no de impacto real.
</p>
</div>
</div>
</div>
</div>
<!-- HOJA DE RUTA -->
<div class="content-section">
<div class="content-inner">
<span class="section-label">Mejora continua</span>
<h2 class="section-heading anchored">
Hoja de ruta hacia el aseguramiento SVI
</h2>
<p>
El primer ciclo confirma que el programa genera valor social robusto. La siguiente etapa es profundizar la medición para capturar con mayor precisión un impacto que ya existe pero que los datos actuales solo capturan parcialmente.
</p>
<div class="roadmap-grid">
<div class="roadmap-fase fase-1">
<pre><code>&lt;div class="fase-label"&gt;Fase 1 · Inmediato&lt;/div&gt;
&lt;div class="fase-titulo"&gt;Documentar y publicar&lt;/div&gt;
&lt;ul&gt;
  &lt;li&gt;Documentar formalmente el outlier WTP&lt;/li&gt;
  &lt;li&gt;Cuantificar inversión total (obra + acompañamiento EAFIT)&lt;/li&gt;
  &lt;li&gt;Incluir liderazgo (I2) en el Value Map publicado&lt;/li&gt;
  &lt;li&gt;Justificar la codificación de la atribución&lt;/li&gt;
&lt;/ul&gt;</code></pre>
</div>
<div class="roadmap-fase fase-2">
<pre><code>&lt;div class="fase-label"&gt;Fase 2 · 3–6 meses&lt;/div&gt;
&lt;div class="fase-titulo"&gt;Ampliar la base de datos&lt;/div&gt;
&lt;ul&gt;
  &lt;li&gt;Instalar contador de acceso mensual al teatro&lt;/li&gt;
  &lt;li&gt;Encuesta ampliada a 60–80 usuarios (no solo líderes)&lt;/li&gt;
  &lt;li&gt;Registro de emprendimientos y ferias activos&lt;/li&gt;
&lt;/ul&gt;</code></pre>
</div>
<div class="roadmap-fase fase-3">
<pre><code>&lt;div class="fase-label"&gt;Fase 3 · Próximo ciclo 2026&lt;/div&gt;
&lt;div class="fase-titulo"&gt;Habilitar nuevos outcomes&lt;/div&gt;
&lt;ul&gt;
  &lt;li&gt;Escala Cantril (0–10) para medir bienestar subjetivo&lt;/li&gt;
  &lt;li&gt;Seguimiento de iniciativas de liderazgo a 2 años&lt;/li&gt;
  &lt;li&gt;Datos económicos de emprendimientos del espacio&lt;/li&gt;
&lt;/ul&gt;</code></pre>
</div>
<div class="roadmap-fase fase-4">
<pre><code>&lt;div class="fase-label"&gt;Fase 4 · Ciclo 2027&lt;/div&gt;
&lt;div class="fase-titulo"&gt;Aseguramiento SVI&lt;/div&gt;
&lt;ul&gt;
  &lt;li&gt;Verificación formal por Social Value International&lt;/li&gt;
  &lt;li&gt;Publicación en la base de datos global SVI&lt;/li&gt;
  &lt;li&gt;SROI proyectado: 4,5–6,0 con datos completos&lt;/li&gt;
&lt;/ul&gt;</code></pre>
</div>
</div>
<div style="margin: 1.5rem 0;">
<img src="../images/argos/fig7_roadmap.png" alt="Hoja de ruta metodológica" style="width: 100%; max-width: 1000px; display: block; margin: 0 auto; border-radius: 0.625rem; border: 1px solid #E2E8F0; box-shadow: 0 4px 16px rgba(0,0,0,0.06);">
<p class="chart-note" style="text-align: center;">
El mayor salto en precisión ocurre en la Fase 2 — la instalación de un contador de acceso y una encuesta ampliada resolverán la principal limitación del ciclo actual.
</p>
</div>
<div class="insight-box">
<div class="insight-label">
Recomendaciones inmediatas — Ciclo 2 (2026–2027)
</div>
<p>
</p><ol type="1">
<li><strong>Ampliar base de beneficiarios</strong> con registro de usuarios del espacio. 2. <strong>Revisar el deadweight</strong> separando “cambio personal” de “acceso a infraestructura” — son outcomes distintos. 3. <strong>Agregar I2 (liderazgo)</strong> al Value Map oficial. 4. <strong>Implementar escala Cantril</strong> para habilitar el outcome de bienestar (WELLBY) en el ciclo 3.
<p></p>
</li></ol></div>

</div>
</div>
<!-- PRINCIPIOS SVI -->
<div class="content-section alt">
<div class="content-inner">
<span class="section-label">Principios SVI</span>
<h2 class="section-heading anchored">
Cumplimiento de los 8 Principios de Social Value International
</h2>
<p>
Seis principios están completamente aplicados en este ciclo; dos están en proceso para el próximo.
</p>
<div class="principio-grid">
<div class="principio-card">
<pre><code>&lt;span class="num"&gt;1&lt;/span&gt;
&lt;div class="nombre"&gt;Involucrar a los stakeholders&lt;/div&gt;
&lt;div class="estado"&gt;✓ Proceso pre-post con líderes y grupos focales&lt;/div&gt;</code></pre>
</div>
<div class="principio-card">
<pre><code>&lt;span class="num"&gt;2&lt;/span&gt;
&lt;div class="nombre"&gt;Entender lo que cambia&lt;/div&gt;
&lt;div class="estado"&gt;✓ Teoría de Cambio con 5 impactos documentados&lt;/div&gt;</code></pre>
</div>
<div class="principio-card">
<pre><code>&lt;span class="num"&gt;3&lt;/span&gt;
&lt;div class="nombre"&gt;Valorar lo que importa&lt;/div&gt;
&lt;div class="estado"&gt;⚠ I4+I2+R6 monetizados. Bienestar (I1): próximo ciclo&lt;/div&gt;</code></pre>
</div>
<div class="principio-card">
<pre><code>&lt;span class="num"&gt;4&lt;/span&gt;
&lt;div class="nombre"&gt;Solo incluir lo material&lt;/div&gt;
&lt;div class="estado"&gt;✓ I5 excluido por baja confianza metodológica&lt;/div&gt;</code></pre>
</div>
<div class="principio-card">
<pre><code>&lt;span class="num"&gt;5&lt;/span&gt;
&lt;div class="nombre"&gt;No sobreatribuir&lt;/div&gt;
&lt;div class="estado"&gt;✓ DW, atribución y desplazamiento aplicados&lt;/div&gt;</code></pre>
</div>
<div class="principio-card">
<pre><code>&lt;span class="num"&gt;6&lt;/span&gt;
&lt;div class="nombre"&gt;Ser transparente&lt;/div&gt;
&lt;div class="estado"&gt;✓ Supuestos declarados, outlier documentado, rangos reportados&lt;/div&gt;</code></pre>
</div>
<div class="principio-card">
<pre><code>&lt;span class="num"&gt;7&lt;/span&gt;
&lt;div class="nombre"&gt;Verificar el resultado&lt;/div&gt;
&lt;div class="estado"&gt;⚠ Revisión por pares EAFIT. Aseguramiento SVI: Fase 4 (2027)&lt;/div&gt;</code></pre>
</div>
<div class="principio-card">
<pre><code>&lt;span class="num"&gt;8&lt;/span&gt;
&lt;div class="nombre"&gt;Ser responsivo&lt;/div&gt;
&lt;div class="estado"&gt;✓ Hoja de ruta con compromisos concretos por fase&lt;/div&gt;</code></pre>
</div>
</div>
</div>
</div>
<!-- PREGUNTAS DIFÍCILES -->
<div class="content-section">
<div class="content-inner">
<span class="section-label">Preguntas difíciles</span>
<h2 class="section-heading anchored">
Las críticas más sólidas — y nuestras respuestas
</h2>
<p>
Un análisis SROI riguroso no evita las preguntas incómodas — las confronta. Esta sección presenta las críticas más fundamentadas de la literatura académica, junto con las respuestas específicas para este análisis.
</p>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Important
</div>
</div>
<div class="callout-body-container callout-body">
<div class="callout-title">
Por qué incluir esta sección
</div>
<p>
La credibilidad de un análisis SROI se construye no solo presentando resultados favorables, sino demostrando que el equipo evaluador conoce las limitaciones del método y ha tomado decisiones conscientes para mitigarlas.
</p>
</div>
</div>
<div class="critica-card">
<div class="critica-header">
<pre><code>&lt;div class="critica-num"&gt;1&lt;/div&gt;
&lt;div class="critica-content"&gt;
  &lt;div class="critica-titulo"&gt;¿El proxy monetario realmente captura el valor del impacto?&lt;/div&gt;
  &lt;div class="critica-texto"&gt;Reducir bienestar humano a un número monetario distorsiona su naturaleza. La "disposición a pagar" mide preferencias de consumo, no el valor real del espacio para la comunidad.&lt;/div&gt;
&lt;/div&gt;</code></pre>
</div>
<div class="respuesta-header">
Respuesta del análisis
</div>
<div class="respuesta-body">
<strong>El proxy fue generado directamente por los beneficiarios del programa</strong>, no transferido de otro contexto. Los usuarios del Teatro Talita Cumi indicaron cuánto estarían dispuestos a pagar para acceder a servicios equivalentes en otros espacios. Se usó la <strong>mediana</strong> para proteger el resultado de valores extremos. El bienestar comunitario, la identidad territorial y la dignidad están documentados como outcomes no monetizados de alto valor potencial.
</div>
</div>
<div class="critica-card">
<div class="critica-header">
<pre><code>&lt;div class="critica-num"&gt;2&lt;/div&gt;
&lt;div class="critica-content"&gt;
  &lt;div class="critica-titulo"&gt;¿El "peso muerto" del 47% no es simplemente una opinión de los beneficiarios?&lt;/div&gt;
  &lt;div class="critica-texto"&gt;El contrafactual — qué hubiera pasado sin el programa — es el supuesto más determinante y el menos verificable. Los beneficiarios tienen incentivos para subestimarlo.&lt;/div&gt;
&lt;/div&gt;</code></pre>
</div>
<div class="respuesta-header">
Respuesta del análisis
</div>
<div class="respuesta-body">
<strong>Esta es la crítica más sólida, y la aceptamos parcialmente.</strong> Por eso el análisis <strong>no usa el 47% empírico como definitivo</strong>: lo corrige a 25% basado en evidencia histórica irrefutable — el Teatro llevaba 25 años en deterioro sin recuperación posible. El análisis de sensibilidad muestra el SROI para todos los valores de DW entre 15% y 50%, y supera el break-even en todos.
</div>
</div>
<div class="critica-card">
<div class="critica-header">
<pre><code>&lt;div class="critica-num"&gt;3&lt;/div&gt;
&lt;div class="critica-content"&gt;
  &lt;div class="critica-titulo"&gt;¿Solo se incluyeron los outcomes positivos fáciles de monetizar?&lt;/div&gt;
  &lt;div class="critica-texto"&gt;Los análisis SROI tienden a incluir los outcomes que el analista puede valorar y excluir los difíciles. El resultado puede ser inflado por selección.&lt;/div&gt;
&lt;/div&gt;</code></pre>
</div>
<div class="respuesta-header">
Respuesta del análisis
</div>
<div class="respuesta-body">
<strong>Los tres outcomes incluidos son los que tienen evidencia cuantitativa directa</strong>, no los que maximizan el ratio. Bienestar (I1) y economía local (I3) — que tendrían mayor valor — fueron <strong>excluidos conscientemente</strong> por no tener datos suficientemente sólidos. No se identificó displacement material — el espacio recuperado no compite con ningún otro espacio comunitario en el barrio.
</div>
</div>
<div class="critica-card">
<div class="critica-header">
<pre><code>&lt;div class="critica-num"&gt;4&lt;/div&gt;
&lt;div class="critica-content"&gt;
  &lt;div class="critica-titulo"&gt;¿Este SROI se puede comparar con el de otros programas?&lt;/div&gt;
  &lt;div class="critica-texto"&gt;Dos análisis del mismo tipo de programa pueden arrojar ratios completamente distintos dependiendo de los proxies elegidos, la tasa de descuento y el horizonte temporal. El ratio no tiene unidad de medida estable.&lt;/div&gt;
&lt;/div&gt;</code></pre>
</div>
<div class="respuesta-header">
Respuesta del análisis
</div>
<div class="respuesta-body">
<strong>Esta crítica es metodológicamente correcta y la asumimos explícitamente.</strong> Los benchmarks no pretenden demostrar que SQT es “más eficiente” — pretenden contextualizar el resultado en el rango esperado para este tipo de intervención. Los 17 programas comparables fueron seleccionados por similitud, y la comparación se hace con rangos, no con rankings. Por eso se presentan tres escenarios en lugar de un único número.
</div>
</div>
<div class="critica-card">
<div class="critica-header">
<pre><code>&lt;div class="critica-num"&gt;5&lt;/div&gt;
&lt;div class="critica-content"&gt;
  &lt;div class="critica-titulo"&gt;¿Solo participaron 20 personas en el proceso de evaluación?&lt;/div&gt;
  &lt;div class="critica-texto"&gt;El Principio 1 de SVI exige involucrar a los stakeholders — pero la muestra de 20 líderes puede ser insuficiente para representar a la comunidad real del teatro.&lt;/div&gt;
&lt;/div&gt;</code></pre>
</div>
<div class="respuesta-header">
Respuesta del análisis
</div>
<div class="respuesta-body">
<strong>Es la limitación central de este ciclo evaluativo, y la reconocemos sin reservas.</strong> Los 20 líderes son los más comprometidos e informados — no son representativos del universo de usuarios. La hoja de ruta pone como Prioridad 1 la instalación de un contador de acceso y la ampliación de la encuesta a 60–80 usuarios de distintos perfiles. Los escenarios del análisis ya incorporan esta incertidumbre.
</div>
</div>
<div class="critica-card">
<div class="critica-header">
<pre><code>&lt;div class="critica-num"&gt;6&lt;/div&gt;
&lt;div class="critica-content"&gt;
  &lt;div class="critica-titulo"&gt;¿El SROI va a cambiar alguna decisión, o es solo un informe para el financiador?&lt;/div&gt;
  &lt;div class="critica-texto"&gt;En la práctica, muchos análisis SROI se comisionan para satisfacer requerimientos de financiadores, no para informar decisiones reales de gestión.&lt;/div&gt;
&lt;/div&gt;</code></pre>
</div>
<div class="respuesta-header">
Respuesta del análisis
</div>
<div class="respuesta-body">
<strong>Respondemos con compromisos concretos.</strong> Tres decisiones específicas que cambian: (1) se instalará un contador de acceso antes del próximo ciclo; (2) el outcome de liderazgo (I2) se incorpora al Value Map oficial desde este ciclo; (3) el deadweight se revisará de forma diferenciada por tipo de outcome (físico vs.&nbsp;organizacional). El próximo informe incluirá una sección explícita de “¿Qué cambió en el programa a partir de esta evaluación?”
</div>
</div>
</div>
</div>
<!-- CONCLUSIONES (dark) -->
<div class="content-section dark">
<div class="content-inner">
<span class="section-label">Conclusiones</span>
<h2 class="section-heading anchored">
El valor está ahí — el camino para demostrarlo también
</h2>
<p>
<strong style="color: white;">Sueños que Transforman generó valor social real y robusto.</strong> El análisis establece con confianza que por cada peso invertido se generaron entre $1,59 y $2,35 en valor social — y $3,37 a cinco años. El resultado es sólido cuantitativamente (supera el break-even en todos los escenarios), comparativamente (P22–P50 global) y metodológicamente (todos los factores de ajuste fueron obtenidos empíricamente).
</p>
<p>
La única barrera entre el resultado actual (P38) y el rango mediano de programas comparables (P50–P65) es la captura incompleta de beneficiarios — una limitación de datos, no de impacto real.
</p>
<div class="sroi-resultado-panel">
<div class="sroi-item">
<pre><code>&lt;div class="sroi-label"&gt;Hoy — ciclo 1&lt;/div&gt;
&lt;div class="sroi-valor"&gt;2.35&lt;/div&gt;
&lt;div class="sroi-sub"&gt;P38 global · 20 líderes encuestados&lt;/div&gt;</code></pre>
</div>
<div class="sroi-item">
<pre><code>&lt;div class="sroi-label"&gt;Con contador + encuesta ampliada&lt;/div&gt;
&lt;div class="sroi-valor"&gt;~3.5&lt;/div&gt;
&lt;div class="sroi-sub"&gt;P50–55 estimado · 80+ beneficiarios&lt;/div&gt;</code></pre>
</div>
<div class="sroi-item">
<pre><code>&lt;div class="sroi-label"&gt;Con bienestar WELLBY (I1)&lt;/div&gt;
&lt;div class="sroi-valor"&gt;~5.0&lt;/div&gt;
&lt;div class="sroi-sub"&gt;P65 estimado · escala Cantril&lt;/div&gt;</code></pre>
</div>
</div>
<blockquote style="border-left: 3px solid #0D9488; background: rgba(13,148,136,0.1); border-radius: 0 0.625rem 0.625rem 0; padding: 1rem 1.5rem; margin: 2rem 0; font-style: italic; color: #E2E8F0; font-size: 1.03rem;" class="blockquote">
“El Teatro Talita Cumi dejó de ser un espacio físico recuperado para convertirse en un territorio de posibilidades. Hoy, 25 años después de que la comunidad empezó a soñar, SQT hizo posible lo que parecía imposible.” <cite style="display: block; font-size: 0.82rem; color: #94A3B8; margin-top: 0.5rem; font-style: normal; font-weight: 600;">— Participante del proceso evaluativo, línea final 2025</cite>
</blockquote>
</div>
</div>
<!-- FOOTER -->
<div style="background: #0F172A; border-top: 1px solid rgba(255,255,255,0.06); padding: 2rem; font-size: 0.78rem; color: #64748B;">
<div style="max-width: 950px; margin: 0 auto; display: flex; justify-content: space-between; align-items: center; gap: 1rem; flex-wrap: wrap;">
<div>
Centro Valor Público · Universidad EAFIT · Medellín, Colombia
</div>
<div>
Confidencial — Fundación Grupo Argos · Marzo 2026
</div>
</div>
</div>


</main></div>



 <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
 <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Centro Valor Público · Universidad EAFIT</p>
</div>   
    <div class="nav-footer-center">
<p>Valor Público — VALOR·IA · Midiendo lo que importa</p>
</div>
    <div class="nav-footer-right">
<p>© 2026</p>
</div>
  </div>
</footer>




<script src="../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>